insert into edw_financial_transactions.fact_replacement_transaction
(
fact_replacement_transaction_natural_key_hash_uuid,
dim_financial_transaction_natural_key_hash_uuid,
calender_dt,
replacement_type_cde,
source_replacement_type_cde,
exchange_type_cde,
source_exchange_type_cde,
replaced_agreement_nr,
replaced_company_nm,
estimated_transfer_amt,
rt_lock_dt,
rt_lock_cde,
source_rt_lock_cde,
fund_received_cde,
source_fund_received_cde,
distribution_transaction_id,
row_process_dtm,
check_sum,
restricted_row_ind,
logical_delete_ind,
source_system_id,
audit_id,
update_audit_id,
source_delete_ind
)
select
uuid_gen(
clean_string(agreement_source_cde),
clean_string(agreement_type_cde),
clean_string(agreement_nr_pfx),
clean_string(agreement_nr),
clean_string(agreement_nr_sfx),
clean_string(replacement_transaction_nr_txt1),
clean_string(financial_transaction_source),
clean_string(financial_transaction_type),
calender_dt)::uuid as fact_replacement_transaction_natural_key_hash_uuid,

uuid_gen(
clean_string(agreement_source_cde),
clean_string(agreement_type_cde),
clean_string(agreement_nr_pfx),
clean_string(agreement_nr),
clean_string(agreement_nr_sfx),
clean_string(replacement_transaction_nr_txt1),
clean_string(financial_transaction_source),
clean_string(financial_transaction_type))::uuid as dim_financial_transaction_natural_key_hash_uuid,

calender_dt,
replacement_type_cde,
source_replacement_type_cde,
exchange_type_cde,
source_exchange_type_cde,
replaced_agreement_nr,
replaced_company_nm,
estimated_transfer_amt,
rt_lock_dt,
rt_lock_cde,
source_rt_lock_cde,
fund_received_cde,
source_fund_received_cde,
distribution_transaction_id,
row_process_dtm,
uuid_gen(
source_delete_ind,
clean_string(replacement_type_cde),
case when source_replacement_type_cde ='   ' then null else btrim(source_replacement_type_cde) end ,
clean_string(exchange_type_cde),
case when source_exchange_type_cde ='   ' then null else btrim(source_exchange_type_cde) end ,
case when replaced_agreement_nr ='               ' then null else btrim(clean_string(replaced_agreement_nr)) end ,
estimated_transfer_amt)::uuid as check_sum,
restricted_row_ind,
logical_delete_ind,
source_system_id,
audit_id,
update_audit_id,
source_delete_ind
from (
select
'Ipa' as agreement_type_cde,
carr_admin_sys_cd as agreement_source_cde,
public.udf_isnum_lpad(hldg_key_pfx, 20, '0', true) as agreement_nr_pfx,
lpad(hldg_key::varchar, 20, '0') as agreement_nr,
public.udf_isnum_lpad(hldg_key_sfx, 20, '0', true) as agreement_nr_sfx,
'Rps' as financial_transaction_source,
'Replacement Transaction' as financial_transaction_type,
case when repl_txn_nr =' ' then null else repl_txn_nr end as replacement_transaction_nr_txt1,
repl_txn_nr as replacement_transaction_nr_txt,
date(trans_dt) as calender_dt,
rplcmt_typ_cd as replacement_type_cde,
src_rplcmt_typ_cd as source_replacement_type_cde,
xch_typ_cd as exchange_type_cde,
src_xch_typ_cd as source_exchange_type_cde,
repl_contr_nr as replaced_agreement_nr,
repl_co_nm as replaced_company_nm,
est_trnf_amt as estimated_transfer_amt,
rate_lock_dt as rt_lock_dt,
rate_lock_ind as rt_lock_cde,
src_rate_lock_ind as source_rt_lock_cde,
fnd_rcvd_ind as fund_received_cde,
src_fnd_rcvd_ind as source_fund_received_cde,
distribution_trans_id as distribution_transaction_id,
current_timestamp(6) as row_process_dtm,
false as restricted_row_ind,
false as logical_delete_ind,
266 as source_system_id,
run_id as audit_id,
updt_run_id as update_audit_id,
case when src_del_ind = 'N' then false
else true end  as source_delete_ind
from prod_stnd_vw_tersun.agmt_repl_vw_aif_rps
where src_sys_id =72
) fact_replacement ;



