CREATE TABLE edw_work.aifrps_dim_agreement (
dim_agreement_natural_key_hash_uuid uuid NOT NULL
,agreement_nr_pfx varchar(50) 
,agreement_nr varchar(150) NOT NULL
,agreement_nr_sfx varchar(50) 
,agreement_source_cde varchar(50) NOT NULL
,agreement_type_cde varchar(50) NOT NULL
,master_contract_group_id varchar(50) 
,sponsor_id varchar(50) 
,plan_id varchar(50) 
,subscriber_id varchar(50) 
,participant_id varchar(50) 
,icu_id varchar(50) 
,master_contract_group_nm_national_desc varchar(500) 
,plan_nm_1_txt varchar(150) 
,plan_nm_2_txt varchar(150) 
,plan_nm_3_txt varchar(150) 
,subscriber_nr int 
,agreement_status_cde varchar(50) 
,agreement_status_reason_cde varchar(50) 
,allow_rollover_ind boolean 
,application_submit_dt date 
,beneficiaries_recorded_ind boolean 
,conversion_expired_ind boolean 
,conversion_eligibility_start_dt date 
,conversion_eligibility_end_dt date 
,default_voluntary_deferral_rt numeric(9,6) 
,enrollment_dt date 
,enrollment_eligibility_dt date 
,enrollment_start_dt date 
,enrollment_end_dt date 
,enrollment_status_cde varchar(50) 
,enrollment_type_cde varchar(50) 
,face_amt numeric(17,4) 
,internal_plan_id varchar(50) 
,issue_dt date 
,participation_dt date 
,solicitation_dt date 
,solicitation_ind boolean 
,taft_hartly_ind boolean 
,electronic_contribution_change_ind boolean 
,pre_tax_auto_increase_contribution_rt numeric(9,6) 
,begin_dt date NOT NULL DEFAULT '0001-01-01'::date
,begin_dtm timestamp(6) NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp
,row_process_dtm timestamp(6) NOT NULL DEFAULT (now())::timestamptz(6)
,audit_id int NOT NULL DEFAULT 0
,logical_delete_ind boolean NOT NULL DEFAULT false
,check_sum uuid NOT NULL
,current_row_ind boolean NOT NULL DEFAULT true
,end_dt date NOT NULL DEFAULT '9999-12-31'::date
,end_dtm timestamp(6) NOT NULL DEFAULT '9999-12-31 23:59:59.999999'::timestamp
,source_system_id varchar(50) NOT NULL
,restricted_row_ind boolean NOT NULL DEFAULT false
,row_sid IDENTITY 
,next_payment_dt date 
,next_payment_amt numeric(17,4) 
,current_principal_amt numeric(17,4) 
,loan_booked_coupon_rt numeric(9,6) 
,loan_booked_amt numeric(17,4) 
,loan_requested_coupon_rt numeric(9,6) 
,loan_requested_amt numeric(17,4) 
,loan_months_to_maturity_val int 
,loan_degree_program_desc varchar(50) 
,decisioning_annual_income_amt numeric(17,4) 
,application_status_dt date 
,loan_report_unique_hash_id varchar(32) 
,eservice_ind boolean 
,agreement_effective_dt date 
,update_audit_id int NOT NULL DEFAULT 0
,terminated_participant_servicing_ind boolean 
,managed_accounts_eligibility_ind boolean 
,managed_accounts_participation_ind boolean 
,managed_accounts_eligibility_start_dtm timestamp(6) 
,split_contract_ind boolean 
,mm_lead_administrator_ind boolean 
,mm_account_manager_nm varchar(100) 
,industry_cde varchar(50) 
,source_agreement_status_cde varchar(50) 
,source_agreement_status_reason_cde varchar(50) 
,source_agreement_status_category_cde varchar(50) 
,agreement_status_dt date 
,dim_product_natural_key_hash_uuid uuid 
,pt1_kind_cde varchar(50) 
,pt2_issue_basis_cde varchar(50) 
,pt3_rate_cde varchar(50) 
,maturity_dt date 
,anniversary_dt date 
,termination_dt date 
,application_received_dt date 
,application_signed_dt date 
,market_category_type_cde varchar(50) 
,source_plan_type_cde varchar(50) 
,source_market_category_type_cde varchar(50) 
,tax_qualified_cde varchar(50) 
,source_tax_qualified_cde varchar(50) 
,replacement_type_cde varchar(50) 
,source_replacement_type_cde varchar(50) 
,restriction_cde varchar(50) 
,source_restriction_cde varchar(50) 
,restriction_category_cde varchar(50) 
,source_restriction_category_cde varchar(50) 
,company_cde varchar(50) 
,source_company_cde varchar(50) 
,frozen_cde varchar(50) 
,source_frozen_cde varchar(50) 
,home_office_amount_suspend_cde varchar(50) 
,source_home_office_amount_suspend_cde varchar(50) 
,lost_insured_ind boolean 
,source_lost_insured_ind varchar(50) 
,title_message_txt varchar(50) 
,offer_acceptance_cde varchar(50) 
,source_offer_acceptance_cde varchar(50) 
,variable_product_cde varchar(50) 
,contract_jurisdiction_state_cde varchar(50) 
,tax_account_nr varchar(50) 
,readability_cde varchar(50) 
,source_readability_cde varchar(50) 
,vantage_restriction_cde varchar(50) 
,suspend_cde varchar(50) 
,source_suspend_cde varchar(50) 
,source_product_short_nm varchar(50) 
,source_product_long_nm varchar(100) 
,special_handling_cde varchar(50) 
,source_special_handling_cde varchar(50) 
,issue_reason_cde varchar(50) 
,source_issue_reason_cde varchar(50) 
,cdsc_period_year_nr int 
,renewal_dt date 
,retire_guard_ind boolean 
,source_admin_error_cde varchar(50) 
,source_pending_activity_cde varchar(50) 
,source_agreement_nr varchar(50) 
,worksite_ind boolean 
,product_group_cde varchar(50) 
,update_state_cde varchar(50) 
,agency_suspend_item_cde varchar(50) 
,distributor_client_account_id varchar(50) 
,resident_state_cde varchar(50) 
,solicitation_state_cde varchar(50) 
,distribution_channel_cde varchar(50) 
,source_distribution_channel_cde varchar(50) 
,product_tier_cde varchar(50) 
,replacement_cde varchar(50) 
,source_replacement_cde varchar(50) 
,special_condition_cde varchar(50) 
,special_condition_reason_cde varchar(50) 
,special_condition_category_cde varchar(50) 
,special_condition_2_cde varchar(50) 
,special_condition_2_reason_cde varchar(50) 
,special_condition_2_category_cde varchar(50) 
,spm_group_billed_suspense_ind boolean 
,spm_individual_billed_suspense_ind boolean 
,spm_group_ar_suspense_ind boolean 
,actively_at_work_ind boolean 
,market_group_cde varchar(50) 
,pt_trans_to_insd_dt date 
,managerial_ind boolean 
,init_pd_to_dt date 
,insured_interested_party_nr_txt varchar(100) 
,issue_state_cde varchar(50) 
,lapse_dt date 
,conversion_status_cde varchar(50) 
,last_anniversary_dt date 
,next_anniversary_dt date 
,insured_issue_age_nr int 
,smoker_cde varchar(50) 
,mec_cde varchar(50) 
,source_mec_cde varchar(50) 
,plan_year_nr int 
,plan_month_nr int 
,agreement_cusip_cde varchar(50) 
,agreement_dividend_option_cde varchar(50) 
,source_agreement_dividend_option_cde varchar(50) 
,apl_cde varchar(50) 
,base_face_rating_nr int 
,base_temporary_premium_amt numeric(17,4) 
,base_temporary_duration_nr int 
,base_permanent_premium_amt numeric(17,4) 
,base_face_amt numeric(17,4) 
,activity_pending_cde varchar(50) 
,activity_pending_desc varchar(200) 
,source_activity_pending_desc varchar(200) 
,apd_ind boolean 
,source_apd_ind varchar(50) 
,apm_nr_txt varchar(25) 
,source_apm_nr_txt varchar(50) 
,source_apl_cde varchar(50) 
,conversion_ind boolean 
,source_conversion_ind varchar(50) 
,converted_policy_type_cde varchar(50) 
,source_converted_policy_type_cde varchar(50) 
,converted_policy_nr_txt varchar(50) 
,activity_cde varchar(50) 
,delivery_data_cde varchar(50) 
,source_delivery_data_cde varchar(50) 
,benefit_amt numeric(17,4) 
,death_benefit_option_cde varchar(50) 
,death_benefit_option_interest_rt numeric(9,6) 
,death_benefit_option_interest_rt_quality_cde varchar(50) 
,exchange_provision_cde varchar(50) 
,source_exchange_provision_cde varchar(50) 
,free_look_expiry_dt date 
,insurance_annuity_cde varchar(50) 
,source_insurance_annuity_cde varchar(50) 
,lump_sum_benefit_amt numeric(17,4) 
,mec_effective_dt date 
,mec_status_cde varchar(50) 
,source_mec_status_cde varchar(50) 
,non_forfeiture_option_cde varchar(50) 
,admspec_cde varchar(50) 
,source_admspec_cde varchar(50) 
,purpose_of_insurance_category_cde varchar(50) 
,purpose_of_insurance_cde varchar(50) 
,pend_settle_cde varchar(50) 
,reinsured_cde varchar(50) 
,source_reinsured_cde varchar(50) 
,temporary_term_pre_effective_dt date 
,temporary_term_status_cde varchar(50) 
,yearly_term_purchase_cde varchar(50) 
,policy_lapse_dt date 
,dbo_short_nm varchar(25) 
,mec_effective_dt_quality_cde varchar(50) 
,vlr_rc varchar(50) 
,telephone_authorization_cde varchar(50) 
,tax_agg_cde varchar(50) 
,source_tax_agg_cde varchar(50) 
,tax_amt_not_determined_ind char(1) 
,assign_dt date 
,earliest_permitted_annuity_dt date 
,latest_permitted_annuity_dt date 
,source_telephone_authorization_cde varchar(50) 
,withdrawal_option_cde varchar(50) 
,source_withdrawal_option_cde varchar(50) 
,glwb_status_cde varchar(50) 
,source_glwb_status_cde varchar(50) 
,glwb_status_dt date 
,reinsurance_treaty_nr_txt varchar(100) 
,excess_withdrawal_cde varchar(50) 
,source_excess_withdrawal_cde varchar(50) 
,vi_rider_ind boolean 
,portability_ind boolean 
,agreement_second_dividend_option_cde varchar(50) 
,source_agreement_second_dividend_option_cde varchar(50) 
,agreement_dividend_option_desc varchar(100) 
,agreement_second_dividend_option_desc varchar(100) 
,source_delete_ind boolean NOT NULL DEFAULT false
,source_product_type_cde varchar(50) 
,living_benefit_notice_cde varchar(50) 
,source_living_benefit_notice_cde varchar(50) 
,living_benefit_lock_in_cde varchar(50) 
,source_living_benefit_lock_in_cde varchar(50) 
,living_benefit_lock_in_dt date 
,persistency_credit_cde varchar(50) 
,source_persistency_credit_cde varchar(50) 
,persistency_credit_start_dt date 
,death_benefit_option_change_age_nr int 
,admin_status_category_desc varchar(200) 
);