SELECT ALL_TABLES.TRANS_DT FROM
(
    SELECT DISTINCT TRANS_DT FROM PROD_STND_VW_TERSUN.AGMT_BILL_VW_AIF_RPS WHERE SRC_SYS_ID = 72
    UNION
    SELECT DISTINCT TRANS_DT FROM PROD_STND_VW_TERSUN.AGMT_BILL_DTL_VW_AIF_RPS WHERE SRC_SYS_ID = 72
) ALL_TABLES WHERE ALL_TABLES.TRANS_DT >
    (SELECT  NVL(MAX(BEGIN_DT),'2000-12-01 00:00:00') FROM EDW_TDSUNSET.fact_agreement_detail_initial_aifrps--EDW_TDSUNSET.fact_agreement_detail
    WHERE SOURCE_SYSTEM_ID=266)
ORDER BY ALL_TABLES.TRANS_DT;