--THIS HAS BEEN RENAMED SINCE MPR DUE TO AGMT_BEN_DATA_VW AND AGMT_DIVIDEND_DATA_VW
--ARE SHARED BY DIM_AGREEMENT AND FACT_AGREEMENT

TRUNCATE TABLE EDW_STAGING.AIFRPS_AGMT_BILL_VW_AIFRPS_SNAPSHOT;

TRUNCATE TABLE EDW_STAGING.AIFRPS_AGMT_BILL_DTL_VW_AIFRPS_SNAPSHOT;
