--de-duplicating the data agmt_bill_dtl
--truncate the temp tables
truncate table edw_staging.agmt_bill_dtl_vw_tmp1;

truncate table edw_staging.agmt_bill_dtl_vw_tmp2;

-- creating temp tables for agmt_bill_dtl

insert into edw_staging.agmt_bill_dtl_vw_tmp1
( select
agmt_bill_dtl.AGMT_ID int,
agmt_bill_dtl.AGMT_BILL_DTL_FR_DT ,
agmt_bill_dtl.AGMT_BILL_DTL_TO_DT ,
agmt_bill_dtl.PD_TO_DT ,
agmt_bill_dtl.PD_TO_DT_TXT ,
agmt_bill_dtl.LST_ADJ_DT ,
agmt_bill_dtl.LST_COLL_DT ,
agmt_bill_dtl.LST_PREM_PD_DT ,
agmt_bill_dtl.LST_TRANS_DT ,
agmt_bill_dtl.PREM_ACCUM_AMT_QLTY_CD ,
agmt_bill_dtl.PREM_ACCUM_AMT,
agmt_bill_dtl.CURR_IND ,
agmt_bill_dtl.SRC_DEL_IND,
agmt_bill_dtl.SRC_SYS_ID ,
agmt_bill_dtl.RUN_ID ,
agmt_bill_dtl.UPDT_RUN_ID ,
agmt_bill_dtl.TRANS_DT ,
agmt_bill_dtl.HLDG_KEY_PFX ,
agmt_bill_dtl.HLDG_KEY ,
agmt_bill_dtl.HLDG_KEY_SFX ,
agmt_bill_dtl.CARR_ADMIN_SYS_CD ,
agmt_bill_dtl.AGMT_DATA_FR_DT ,
agmt_bill_dtl.LST_DPST_DT ,
agmt_bill_dtl.LST_DPST_AMT ,
agmt_bill_dtl.LST_DPST_AMT_QLTY_CD ,
agmt_bill_dtl.ADMIN_CHRG_AMT ,
agmt_bill_dtl.MINUS_1_TAX_RT ,
agmt_bill_dtl.BILL_TO_DT ,
agmt_bill_dtl.APM_NXT_BILL_DT ,
agmt_bill_dtl.LST_PREM_PD_AMT   
from
prod_stnd_vw_tersun.agmt_bill_dtl_vw_aif_rps agmt_bill_dtl
join

	(
		select agmt_id, run_id, trans_dt, count(*)
		from prod_stnd_vw_tersun.agmt_bill_dtl_vw_aif_rps
		where src_sys_id = 72
		group by agmt_id, run_id, trans_dt
		having count(*)>1
	)dup

on 	agmt_bill_dtl.agmt_id=dup.agmt_id
and agmt_bill_dtl.run_id=dup.run_id
and agmt_bill_dtl.trans_dt=dup.trans_dt
and agmt_bill_dtl.TRANS_DT =:TRANS_DT 
and src_sys_id = 72
);--2017-10-24 00:00:00


insert into edw_staging.agmt_bill_dtl_vw_tmp2
(
select 
agmt_bill_dtl.AGMT_ID,
agmt_bill_dtl.AGMT_BILL_DTL_FR_DT ,
agmt_bill_dtl.AGMT_BILL_DTL_TO_DT ,
agmt_bill_dtl.PD_TO_DT ,
agmt_bill_dtl.PD_TO_DT_TXT ,
agmt_bill_dtl.LST_ADJ_DT ,
agmt_bill_dtl.LST_COLL_DT ,
agmt_bill_dtl.LST_PREM_PD_DT ,
agmt_bill_dtl.LST_TRANS_DT ,
agmt_bill_dtl.PREM_ACCUM_AMT_QLTY_CD ,
agmt_bill_dtl.PREM_ACCUM_AMT,
agmt_bill_dtl.CURR_IND ,
agmt_bill_dtl.SRC_DEL_IND,
agmt_bill_dtl.SRC_SYS_ID ,
agmt_bill_dtl.RUN_ID ,
agmt_bill_dtl.UPDT_RUN_ID ,
agmt_bill_dtl.TRANS_DT ,
agmt_bill_dtl.HLDG_KEY_PFX ,
agmt_bill_dtl.HLDG_KEY ,
agmt_bill_dtl.HLDG_KEY_SFX ,
agmt_bill_dtl.CARR_ADMIN_SYS_CD ,
agmt_bill_dtl.AGMT_DATA_FR_DT ,
agmt_bill_dtl.LST_DPST_DT ,
agmt_bill_dtl.LST_DPST_AMT ,
agmt_bill_dtl.LST_DPST_AMT_QLTY_CD ,
agmt_bill_dtl.ADMIN_CHRG_AMT ,
agmt_bill_dtl.MINUS_1_TAX_RT ,
agmt_bill_dtl.BILL_TO_DT ,
agmt_bill_dtl.APM_NXT_BILL_DT ,
agmt_bill_dtl.LST_PREM_PD_AMT   from
prod_stnd_vw_tersun.agmt_bill_dtl_vw_aif_rps agmt_bill_dtl
left join

	(
		select agmt_id, run_id, trans_dt, count(*)
		from prod_stnd_vw_tersun.agmt_bill_dtl_vw_aif_rps
		where src_sys_id = 72
		group by agmt_id, run_id, trans_dt
		having count(*)>1
	)dup

on 	agmt_bill_dtl.agmt_id=dup.agmt_id
and agmt_bill_dtl.run_id=dup.run_id
and agmt_bill_dtl.trans_dt=dup.trans_dt
--and agmt_bill_dtl.run_id = :RUN_ID 
--and src_sys_id = 72
where dup.agmt_id is null
and agmt_bill_dtl.trans_dt = :TRANS_DT 
and src_sys_id = 72
);


------------------------------------------------------------------------------------



--snapshot for agmt_bill_dtl

-- delete the changed record in snapshot, make sure snapshot is all new
delete from edw_staging.aifrps_agmt_bill_dtl_vw_aifrps_snapshot--EDW_STAGING.AIFRPS_AGMT_BILL_VW_AIFRPS_SNAPSHOT
where agmt_id in 
(select agmt_id from prod_stnd_vw_tersun.agmt_bill_dtl_vw_aif_rps where trans_dt = :TRANS_DT and src_sys_id = 72);

-- set all current_batch to false
update edw_staging.aifrps_agmt_bill_dtl_vw_aifrps_snapshot
set current_batch = false
where current_batch = true;

-- insert into new data's

insert into edw_staging.aifrps_agmt_bill_dtl_vw_aifrps_snapshot
(AGMT_ID ,
AGMT_BILL_DTL_FR_DT ,
AGMT_BILL_DTL_TO_DT ,
PD_TO_DT ,
PD_TO_DT_TXT ,
LST_ADJ_DT ,
LST_COLL_DT ,
LST_PREM_PD_DT ,
LST_TRANS_DT ,
PREM_ACCUM_AMT_QLTY_CD ,
PREM_ACCUM_AMT,
CURR_IND ,
SRC_DEL_IND,
SRC_SYS_ID ,
RUN_ID ,
UPDT_RUN_ID ,
TRANS_DT ,
HLDG_KEY_PFX ,
HLDG_KEY ,
HLDG_KEY_SFX ,
CARR_ADMIN_SYS_CD ,
AGMT_DATA_FR_DT ,
LST_DPST_DT ,
LST_DPST_AMT ,
LST_DPST_AMT_QLTY_CD ,
ADMIN_CHRG_AMT ,
MINUS_1_TAX_RT ,
BILL_TO_DT ,
APM_NXT_BILL_DT ,
LST_PREM_PD_AMT,
current_batch
)
(
select
AGMT_ID ,
AGMT_BILL_DTL_FR_DT ,
AGMT_BILL_DTL_TO_DT ,
PD_TO_DT ,
PD_TO_DT_TXT ,
LST_ADJ_DT ,
LST_COLL_DT ,
LST_PREM_PD_DT ,
LST_TRANS_DT ,
PREM_ACCUM_AMT_QLTY_CD ,
PREM_ACCUM_AMT,
CURR_IND ,
SRC_DEL_IND,
SRC_SYS_ID ,
RUN_ID ,
UPDT_RUN_ID ,
TRANS_DT ,
HLDG_KEY_PFX ,
HLDG_KEY ,
HLDG_KEY_SFX ,
CARR_ADMIN_SYS_CD ,
AGMT_DATA_FR_DT ,
LST_DPST_DT ,
LST_DPST_AMT ,
LST_DPST_AMT_QLTY_CD ,
ADMIN_CHRG_AMT ,
MINUS_1_TAX_RT ,
BILL_TO_DT ,
APM_NXT_BILL_DT ,
LST_PREM_PD_AMT,
true

from
(
select t1.*, row_number() over (partition by t1.agmt_id, t1.run_id, t1.trans_dt order by t1.agmt_bill_dtl_to_dt desc) as rec_num
from
edw_staging.agmt_bill_dtl_vw_tmp1 t1
)calc
where rec_num=1
);

insert into edw_staging.aifrps_agmt_bill_dtl_vw_aifrps_snapshot
(AGMT_ID ,
AGMT_BILL_DTL_FR_DT ,
AGMT_BILL_DTL_TO_DT ,
PD_TO_DT ,
PD_TO_DT_TXT ,
LST_ADJ_DT ,
LST_COLL_DT ,
LST_PREM_PD_DT ,
LST_TRANS_DT ,
PREM_ACCUM_AMT_QLTY_CD ,
PREM_ACCUM_AMT,
CURR_IND ,
SRC_DEL_IND,
SRC_SYS_ID ,
RUN_ID ,
UPDT_RUN_ID ,
TRANS_DT ,
HLDG_KEY_PFX ,
HLDG_KEY ,
HLDG_KEY_SFX ,
CARR_ADMIN_SYS_CD ,
AGMT_DATA_FR_DT ,
LST_DPST_DT ,
LST_DPST_AMT ,
LST_DPST_AMT_QLTY_CD ,
ADMIN_CHRG_AMT ,
MINUS_1_TAX_RT ,
BILL_TO_DT ,
APM_NXT_BILL_DT ,
LST_PREM_PD_AMT,
current_batch
)
(
select
AGMT_ID,
AGMT_BILL_DTL_FR_DT ,
AGMT_BILL_DTL_TO_DT ,
PD_TO_DT ,
PD_TO_DT_TXT ,
LST_ADJ_DT ,
LST_COLL_DT ,
LST_PREM_PD_DT ,
LST_TRANS_DT ,
PREM_ACCUM_AMT_QLTY_CD ,
PREM_ACCUM_AMT,
CURR_IND ,
SRC_DEL_IND,
SRC_SYS_ID ,
RUN_ID ,
UPDT_RUN_ID ,
TRANS_DT ,
HLDG_KEY_PFX ,
HLDG_KEY ,
HLDG_KEY_SFX ,
CARR_ADMIN_SYS_CD ,
AGMT_DATA_FR_DT ,
LST_DPST_DT ,
LST_DPST_AMT ,
LST_DPST_AMT_QLTY_CD ,
ADMIN_CHRG_AMT ,
MINUS_1_TAX_RT ,
BILL_TO_DT ,
APM_NXT_BILL_DT ,
LST_PREM_PD_AMT,
true
from
edw_staging.agmt_bill_dtl_vw_tmp2
);
--de-duplicating the data agmt_bill_dtl
-------------------------------------------------------------------------------------------------------------------------------------------------
--de-duplicating the data 

--truncate the temp tables



truncate table edw_staging.agmt_bill_vw_tmp1;

truncate table edw_staging.agmt_bill_vw_tmp2;


-- creating temp tables for agmt_bill

insert into edw_staging.agmt_bill_vw_tmp1
( select
agmt_bill.AGMT_ID ,
agmt_bill.AGMT_DATA_FR_DT ,
agmt_bill.AGMT_BILL_FR_DT ,
agmt_bill.AGMT_BILL_TO_DT ,
agmt_bill.HLDG_KEY_PFX ,
agmt_bill.HLDG_KEY ,
agmt_bill.HLDG_KEY_SFX ,
agmt_bill.CARR_ADMIN_SYS_CD ,
agmt_bill.BILL_MODE_CD ,
agmt_bill.EBILL_PREF_IND ,
agmt_bill.NO_BILL_RSN_CD ,
agmt_bill.BILL_FREQ_WD ,
agmt_bill.PREM_TAX_STATE_CD ,
agmt_bill.RTN_CHK_CD ,
agmt_bill.SDO_MPO_APO_CD ,
agmt_bill.PD_IN_ADV_YR_CNT ,
agmt_bill.SDO_PYMT_TYP_CD ,
agmt_bill.FEE_IND ,
agmt_bill.FRST_YR_IND ,
agmt_bill.IPO_IND ,
agmt_bill.LTC_ACTY_IND ,
agmt_bill.LTC_PREM_ADJ_IND ,
agmt_bill.LATE_PYMT_OFFER_END_DT ,
agmt_bill.VANISH_PREM_EFF_DT ,
agmt_bill.ALIR_BILL_PREM_AMT ,
agmt_bill.ALIR_BILL_PREM_QLTY_CD ,
agmt_bill.AL_SUP_TRMN_AMT ,
agmt_bill.MPO_APO_NET_PYMT_DUE_AMT ,
agmt_bill.MPO_APO_NET_PYMT_QLTY_CD ,
agmt_bill.MPO_APO_PD_AMT ,
agmt_bill.APO_CR_AMT ,
agmt_bill.ANNL_PREM_AMT ,
agmt_bill.ANNL_PREM_AMT_QLTY_CD ,
agmt_bill.BASE_RDR_MTHLY_PREM_AMT ,
agmt_bill.BASE_RDR_MTHLY_PREM_QLTY_CD ,
agmt_bill.BASE_RDR_ANNL_PREM_AMT ,
agmt_bill.BILL_PREM_AMT ,
agmt_bill.BILL_PREM_QLTY_CD ,
agmt_bill.CLI_PREM_BILL_IND ,
agmt_bill.COST_DUE_AMT ,
agmt_bill.COST_BASIS_AMT ,
agmt_bill.COST_BASIS_QLTY_CD ,
agmt_bill.CURR_PREM_CR_BASE_AMT ,
agmt_bill.CURR_YR_PYMNT_AMT ,
agmt_bill.CURR_PREM_CRDT_LTC_AMT ,
agmt_bill.CURR_PREM_CRDT_LTC_QLTY_CD ,
agmt_bill.NXT_YR_PREM_CRDT_LTC_AMT ,
agmt_bill.NXT_YR_PREM_CRDT_LTC_QLTY_CD ,
agmt_bill.EWL_DFCT_PREM_PAYUP_AMT ,
agmt_bill.EWL_DFCT_PD_TO_YR_MTH ,
agmt_bill.FRAC_PREM_CR_BASE_AMT ,
agmt_bill.FRAC_PREM_CR_LTC_AMT ,
agmt_bill.FRAC_PREM_CR_LTC_QLTY_CD ,
agmt_bill.GRS_ANNL_PREM_AMT ,
agmt_bill.GRS_ANNL_PREM_QLTY_CD ,
agmt_bill.GRS_PREM_FPDUP_ADDNS_AMT ,
agmt_bill.LTCIR_RTRN_PREM_AMT ,
agmt_bill.LTCIR_RTRN_PREM_QLTY_CD ,
agmt_bill.LTCIR_RDUC_ADDNS_AMT ,
agmt_bill.LTCIR_RDUC_ADDNS_QLTY_CD ,
agmt_bill.LTC_EXTD_BEN_POOL_AMT ,
agmt_bill.LTC_EXTD_BEN_POOL_QLTY_CD ,
agmt_bill.MAX_ANNL_PYMT_YR ,
agmt_bill.NB_PREM_PD_AMT ,
agmt_bill.NXT_YR_PREM_CR_BASE_AMT ,
agmt_bill.TGT_PREM_AMT ,
agmt_bill.TGT_PREM_QLTY_CD ,
agmt_bill.TOT_MTHLY_PREM_AMT ,
agmt_bill.TOT_MTHLY_PREM_QLTY_CD ,
agmt_bill.UNERND_PAST_DUE_PREM_AMT ,
agmt_bill.UNERND_PAST_DUE_PREM_QLTY_CD ,
agmt_bill.VANISH_BILL_AMT ,
agmt_bill.CURR_IND ,
agmt_bill.SRC_DEL_IND ,
agmt_bill.SRC_SYS_ID ,
agmt_bill.RUN_ID ,
agmt_bill.UPDT_RUN_ID ,
agmt_bill.TRANS_DT ,
agmt_bill.MPO_APO_PD_AMT_QLTY_CD ,
agmt_bill.APO_CR_AMT_QLTY_CD ,
agmt_bill.BASE_RDR_ANNL_PREM_QLTY_CD ,
agmt_bill.CURR_PREM_CR_BASE_QLTY_CD ,
agmt_bill.FRAC_PREM_CR_BASE_QLTY_CD ,
agmt_bill.GRS_PREM_FPDUP_ADDNS_QLTY_CD ,
agmt_bill.NXT_YR_PREM_CR_BASE_QLTY_CD ,
agmt_bill.LISR_DISAB_COST ,
agmt_bill.PYMNT_DRFT_DY_CD ,
agmt_bill.YTD_PREM_AMT ,
agmt_bill.INV_ACCT_NO ,
agmt_bill.GRP_ACCT_TYP ,
agmt_bill.GRP_ACCT_NBR ,
agmt_bill.LST_BILL_MTHD ,
agmt_bill.PAC_ACCT_ID ,
agmt_bill.PAC_ACCT_TYP ,
agmt_bill.BANK_NM ,
agmt_bill.BILL_ARGMT_IDENT ,
agmt_bill.BILL_MTHD_TYP_CD ,
agmt_bill.CNSLDT_BILL_TYP_CD ,
agmt_bill.ANNUALIZED_PREM_AMT ,
agmt_bill.ALIR_BILL_AMT ,
agmt_bill.ALIR_BILL_AMT_QLTY_CD ,
agmt_bill.BANK_ID ,
agmt_bill.PERM_FLAT_XTR_PREM_AMT ,
agmt_bill.TEMP_FLAT_XTR_PREM_AMT ,
agmt_bill.PERM_FLAT_XTR_COST_AMT ,
agmt_bill.TEMP_FLAT_XTR_COST_AMT ,
agmt_bill.TOT_ANNL_PREM_AMT ,
agmt_bill.TOT_ANNL_PREM_AMT_QLTY_CD ,
agmt_bill.SRC_BILL_MODE_CD ,
agmt_bill.INIT_PREM_AMT ,
agmt_bill.PYTD_PREM_AMT ,
agmt_bill.PREM_REFUND_AMT ,
agmt_bill.PREM_REFUND_QLTY_CD ,
agmt_bill.PRO_RATA_REFUND_AMT ,
agmt_bill.PRO_RATA_REFUND_QLTY_CD ,
agmt_bill.ADV_PREM_REFUND_AMT ,
agmt_bill.ADV_PREM_REFUND_QLTY_CD 
from
prod_stnd_vw_tersun.agmt_bill_vw_aif_rps agmt_bill
join

	(
		select agmt_id, run_id, trans_dt, count(*)
		from prod_stnd_vw_tersun.agmt_bill_vw_aif_rps
		where src_sys_id = 72
		group by agmt_id, run_id, trans_dt
		having count(*)>1
	)dup

on 	agmt_bill.agmt_id=dup.agmt_id
and agmt_bill.run_id=dup.run_id
and agmt_bill.trans_dt=dup.trans_dt
and agmt_bill.TRANS_DT =:TRANS_DT 
and src_sys_id = 72
);--2017-10-24 00:00:00


insert into edw_staging.agmt_bill_vw_tmp2
(
select agmt_bill.AGMT_ID ,
agmt_bill.AGMT_DATA_FR_DT ,
agmt_bill.AGMT_BILL_FR_DT ,
agmt_bill.AGMT_BILL_TO_DT ,
agmt_bill.HLDG_KEY_PFX ,
agmt_bill.HLDG_KEY ,
agmt_bill.HLDG_KEY_SFX ,
agmt_bill.CARR_ADMIN_SYS_CD ,
agmt_bill.BILL_MODE_CD ,
agmt_bill.EBILL_PREF_IND ,
agmt_bill.NO_BILL_RSN_CD ,
agmt_bill.BILL_FREQ_WD ,
agmt_bill.PREM_TAX_STATE_CD ,
agmt_bill.RTN_CHK_CD ,
agmt_bill.SDO_MPO_APO_CD ,
agmt_bill.PD_IN_ADV_YR_CNT ,
agmt_bill.SDO_PYMT_TYP_CD ,
agmt_bill.FEE_IND ,
agmt_bill.FRST_YR_IND ,
agmt_bill.IPO_IND ,
agmt_bill.LTC_ACTY_IND ,
agmt_bill.LTC_PREM_ADJ_IND ,
agmt_bill.LATE_PYMT_OFFER_END_DT ,
agmt_bill.VANISH_PREM_EFF_DT ,
agmt_bill.ALIR_BILL_PREM_AMT ,
agmt_bill.ALIR_BILL_PREM_QLTY_CD ,
agmt_bill.AL_SUP_TRMN_AMT ,
agmt_bill.MPO_APO_NET_PYMT_DUE_AMT ,
agmt_bill.MPO_APO_NET_PYMT_QLTY_CD ,
agmt_bill.MPO_APO_PD_AMT ,
agmt_bill.APO_CR_AMT ,
agmt_bill.ANNL_PREM_AMT ,
agmt_bill.ANNL_PREM_AMT_QLTY_CD ,
agmt_bill.BASE_RDR_MTHLY_PREM_AMT ,
agmt_bill.BASE_RDR_MTHLY_PREM_QLTY_CD ,
agmt_bill.BASE_RDR_ANNL_PREM_AMT ,
agmt_bill.BILL_PREM_AMT ,
agmt_bill.BILL_PREM_QLTY_CD ,
agmt_bill.CLI_PREM_BILL_IND ,
agmt_bill.COST_DUE_AMT ,
agmt_bill.COST_BASIS_AMT ,
agmt_bill.COST_BASIS_QLTY_CD ,
agmt_bill.CURR_PREM_CR_BASE_AMT ,
agmt_bill.CURR_YR_PYMNT_AMT ,
agmt_bill.CURR_PREM_CRDT_LTC_AMT ,
agmt_bill.CURR_PREM_CRDT_LTC_QLTY_CD ,
agmt_bill.NXT_YR_PREM_CRDT_LTC_AMT ,
agmt_bill.NXT_YR_PREM_CRDT_LTC_QLTY_CD ,
agmt_bill.EWL_DFCT_PREM_PAYUP_AMT ,
agmt_bill.EWL_DFCT_PD_TO_YR_MTH ,
agmt_bill.FRAC_PREM_CR_BASE_AMT ,
agmt_bill.FRAC_PREM_CR_LTC_AMT ,
agmt_bill.FRAC_PREM_CR_LTC_QLTY_CD ,
agmt_bill.GRS_ANNL_PREM_AMT ,
agmt_bill.GRS_ANNL_PREM_QLTY_CD ,
agmt_bill.GRS_PREM_FPDUP_ADDNS_AMT ,
agmt_bill.LTCIR_RTRN_PREM_AMT ,
agmt_bill.LTCIR_RTRN_PREM_QLTY_CD ,
agmt_bill.LTCIR_RDUC_ADDNS_AMT ,
agmt_bill.LTCIR_RDUC_ADDNS_QLTY_CD ,
agmt_bill.LTC_EXTD_BEN_POOL_AMT ,
agmt_bill.LTC_EXTD_BEN_POOL_QLTY_CD ,
agmt_bill.MAX_ANNL_PYMT_YR ,
agmt_bill.NB_PREM_PD_AMT ,
agmt_bill.NXT_YR_PREM_CR_BASE_AMT ,
agmt_bill.TGT_PREM_AMT ,
agmt_bill.TGT_PREM_QLTY_CD ,
agmt_bill.TOT_MTHLY_PREM_AMT ,
agmt_bill.TOT_MTHLY_PREM_QLTY_CD ,
agmt_bill.UNERND_PAST_DUE_PREM_AMT ,
agmt_bill.UNERND_PAST_DUE_PREM_QLTY_CD ,
agmt_bill.VANISH_BILL_AMT ,
agmt_bill.CURR_IND ,
agmt_bill.SRC_DEL_IND ,
agmt_bill.SRC_SYS_ID ,
agmt_bill.RUN_ID ,
agmt_bill.UPDT_RUN_ID ,
agmt_bill.TRANS_DT ,
agmt_bill.MPO_APO_PD_AMT_QLTY_CD ,
agmt_bill.APO_CR_AMT_QLTY_CD ,
agmt_bill.BASE_RDR_ANNL_PREM_QLTY_CD ,
agmt_bill.CURR_PREM_CR_BASE_QLTY_CD ,
agmt_bill.FRAC_PREM_CR_BASE_QLTY_CD ,
agmt_bill.GRS_PREM_FPDUP_ADDNS_QLTY_CD ,
agmt_bill.NXT_YR_PREM_CR_BASE_QLTY_CD ,
agmt_bill.LISR_DISAB_COST ,
agmt_bill.PYMNT_DRFT_DY_CD ,
agmt_bill.YTD_PREM_AMT ,
agmt_bill.INV_ACCT_NO ,
agmt_bill.GRP_ACCT_TYP ,
agmt_bill.GRP_ACCT_NBR ,
agmt_bill.LST_BILL_MTHD ,
agmt_bill.PAC_ACCT_ID ,
agmt_bill.PAC_ACCT_TYP ,
agmt_bill.BANK_NM ,
agmt_bill.BILL_ARGMT_IDENT ,
agmt_bill.BILL_MTHD_TYP_CD ,
agmt_bill.CNSLDT_BILL_TYP_CD ,
agmt_bill.ANNUALIZED_PREM_AMT ,
agmt_bill.ALIR_BILL_AMT ,
agmt_bill.ALIR_BILL_AMT_QLTY_CD ,
agmt_bill.BANK_ID ,
agmt_bill.PERM_FLAT_XTR_PREM_AMT ,
agmt_bill.TEMP_FLAT_XTR_PREM_AMT ,
agmt_bill.PERM_FLAT_XTR_COST_AMT ,
agmt_bill.TEMP_FLAT_XTR_COST_AMT ,
agmt_bill.TOT_ANNL_PREM_AMT ,
agmt_bill.TOT_ANNL_PREM_AMT_QLTY_CD ,
agmt_bill.SRC_BILL_MODE_CD ,
agmt_bill.INIT_PREM_AMT ,
agmt_bill.PYTD_PREM_AMT ,
agmt_bill.PREM_REFUND_AMT ,
agmt_bill.PREM_REFUND_QLTY_CD ,
agmt_bill.PRO_RATA_REFUND_AMT ,
agmt_bill.PRO_RATA_REFUND_QLTY_CD ,
agmt_bill.ADV_PREM_REFUND_AMT ,
agmt_bill.ADV_PREM_REFUND_QLTY_CD from
prod_stnd_vw_tersun.agmt_bill_vw_aif_rps agmt_bill
left join

	(
		select agmt_id, run_id, trans_dt, count(*)
		from prod_stnd_vw_tersun.agmt_bill_vw_aif_rps
		where src_sys_id = 72
		group by agmt_id, run_id, trans_dt
		having count(*)>1
	)dup

on 	agmt_bill.agmt_id=dup.agmt_id
and agmt_bill.run_id=dup.run_id
and agmt_bill.trans_dt=dup.trans_dt
--and agmt_bill.run_id = :RUN_ID 
--and src_sys_id = 72
where dup.agmt_id is null
and agmt_bill.trans_dt = :TRANS_DT 
and src_sys_id = 72
);


------------------------------------------------------------------------------------



--snapshot for agmt_bill

-- delete the changed record in snapshot, make sure snapshot is all new
delete from edw_staging.aifrps_agmt_bill_vw_aifrps_snapshot--EDW_STAGING.AIFRPS_AGMT_BILL_VW_AIFRPS_SNAPSHOT
where agmt_id in 
(select agmt_id from prod_stnd_vw_tersun.agmt_bill_vw_aif_rps where trans_dt = :TRANS_DT and src_sys_id = 72);

-- set all current_batch to false
update edw_staging.aifrps_agmt_bill_vw_aifrps_snapshot
set current_batch = false
where current_batch = true;

-- insert into new data's

insert into edw_staging.aifrps_agmt_bill_vw_aifrps_snapshot
(AGMT_ID ,
AGMT_DATA_FR_DT ,
AGMT_BILL_FR_DT ,
AGMT_BILL_TO_DT ,
HLDG_KEY_PFX ,
HLDG_KEY ,
HLDG_KEY_SFX ,
CARR_ADMIN_SYS_CD ,
BILL_MODE_CD ,
EBILL_PREF_IND ,
NO_BILL_RSN_CD ,
BILL_FREQ_WD ,
PREM_TAX_STATE_CD ,
RTN_CHK_CD ,
SDO_MPO_APO_CD ,
PD_IN_ADV_YR_CNT ,
SDO_PYMT_TYP_CD ,
FEE_IND ,
FRST_YR_IND ,
IPO_IND ,
LTC_ACTY_IND ,
LTC_PREM_ADJ_IND ,
LATE_PYMT_OFFER_END_DT ,
VANISH_PREM_EFF_DT ,
ALIR_BILL_PREM_AMT ,
ALIR_BILL_PREM_QLTY_CD ,
AL_SUP_TRMN_AMT ,
MPO_APO_NET_PYMT_DUE_AMT ,
MPO_APO_NET_PYMT_QLTY_CD ,
MPO_APO_PD_AMT ,
APO_CR_AMT ,
ANNL_PREM_AMT ,
ANNL_PREM_AMT_QLTY_CD ,
BASE_RDR_MTHLY_PREM_AMT ,
BASE_RDR_MTHLY_PREM_QLTY_CD ,
BASE_RDR_ANNL_PREM_AMT ,
BILL_PREM_AMT ,
BILL_PREM_QLTY_CD ,
CLI_PREM_BILL_IND ,
COST_DUE_AMT ,
COST_BASIS_AMT ,
COST_BASIS_QLTY_CD ,
CURR_PREM_CR_BASE_AMT ,
CURR_YR_PYMNT_AMT ,
CURR_PREM_CRDT_LTC_AMT ,
CURR_PREM_CRDT_LTC_QLTY_CD ,
NXT_YR_PREM_CRDT_LTC_AMT ,
NXT_YR_PREM_CRDT_LTC_QLTY_CD ,
EWL_DFCT_PREM_PAYUP_AMT ,
EWL_DFCT_PD_TO_YR_MTH ,
FRAC_PREM_CR_BASE_AMT ,
FRAC_PREM_CR_LTC_AMT ,
FRAC_PREM_CR_LTC_QLTY_CD ,
GRS_ANNL_PREM_AMT ,
GRS_ANNL_PREM_QLTY_CD ,
GRS_PREM_FPDUP_ADDNS_AMT ,
LTCIR_RTRN_PREM_AMT ,
LTCIR_RTRN_PREM_QLTY_CD ,
LTCIR_RDUC_ADDNS_AMT ,
LTCIR_RDUC_ADDNS_QLTY_CD ,
LTC_EXTD_BEN_POOL_AMT ,
LTC_EXTD_BEN_POOL_QLTY_CD ,
MAX_ANNL_PYMT_YR ,
NB_PREM_PD_AMT ,
NXT_YR_PREM_CR_BASE_AMT ,
TGT_PREM_AMT ,
TGT_PREM_QLTY_CD ,
TOT_MTHLY_PREM_AMT ,
TOT_MTHLY_PREM_QLTY_CD ,
UNERND_PAST_DUE_PREM_AMT ,
UNERND_PAST_DUE_PREM_QLTY_CD ,
VANISH_BILL_AMT ,
CURR_IND ,
SRC_DEL_IND ,
SRC_SYS_ID ,
RUN_ID ,
UPDT_RUN_ID ,
TRANS_DT ,
MPO_APO_PD_AMT_QLTY_CD ,
APO_CR_AMT_QLTY_CD ,
BASE_RDR_ANNL_PREM_QLTY_CD ,
CURR_PREM_CR_BASE_QLTY_CD ,
FRAC_PREM_CR_BASE_QLTY_CD ,
GRS_PREM_FPDUP_ADDNS_QLTY_CD ,
NXT_YR_PREM_CR_BASE_QLTY_CD ,
LISR_DISAB_COST ,
PYMNT_DRFT_DY_CD ,
YTD_PREM_AMT ,
INV_ACCT_NO ,
GRP_ACCT_TYP ,
GRP_ACCT_NBR ,
LST_BILL_MTHD ,
PAC_ACCT_ID ,
PAC_ACCT_TYP ,
BANK_NM ,
BILL_ARGMT_IDENT ,
BILL_MTHD_TYP_CD ,
CNSLDT_BILL_TYP_CD ,
ANNUALIZED_PREM_AMT ,
ALIR_BILL_AMT ,
ALIR_BILL_AMT_QLTY_CD ,
BANK_ID ,
PERM_FLAT_XTR_PREM_AMT ,
TEMP_FLAT_XTR_PREM_AMT ,
PERM_FLAT_XTR_COST_AMT ,
TEMP_FLAT_XTR_COST_AMT ,
TOT_ANNL_PREM_AMT ,
TOT_ANNL_PREM_AMT_QLTY_CD ,
SRC_BILL_MODE_CD ,
INIT_PREM_AMT ,
PYTD_PREM_AMT ,
PREM_REFUND_AMT ,
PREM_REFUND_QLTY_CD ,
PRO_RATA_REFUND_AMT ,
PRO_RATA_REFUND_QLTY_CD ,
ADV_PREM_REFUND_AMT ,
ADV_PREM_REFUND_QLTY_CD,
current_batch
)
(
select
AGMT_ID ,
AGMT_DATA_FR_DT ,
AGMT_BILL_FR_DT ,
AGMT_BILL_TO_DT ,
HLDG_KEY_PFX ,
HLDG_KEY ,
HLDG_KEY_SFX ,
CARR_ADMIN_SYS_CD ,
BILL_MODE_CD ,
EBILL_PREF_IND ,
NO_BILL_RSN_CD ,
BILL_FREQ_WD ,
PREM_TAX_STATE_CD ,
RTN_CHK_CD ,
SDO_MPO_APO_CD ,
PD_IN_ADV_YR_CNT ,
SDO_PYMT_TYP_CD ,
FEE_IND ,
FRST_YR_IND ,
IPO_IND ,
LTC_ACTY_IND ,
LTC_PREM_ADJ_IND ,
LATE_PYMT_OFFER_END_DT ,
VANISH_PREM_EFF_DT ,
ALIR_BILL_PREM_AMT ,
ALIR_BILL_PREM_QLTY_CD ,
AL_SUP_TRMN_AMT ,
MPO_APO_NET_PYMT_DUE_AMT ,
MPO_APO_NET_PYMT_QLTY_CD ,
MPO_APO_PD_AMT ,
APO_CR_AMT ,
ANNL_PREM_AMT ,
ANNL_PREM_AMT_QLTY_CD ,
BASE_RDR_MTHLY_PREM_AMT ,
BASE_RDR_MTHLY_PREM_QLTY_CD ,
BASE_RDR_ANNL_PREM_AMT ,
BILL_PREM_AMT ,
BILL_PREM_QLTY_CD ,
CLI_PREM_BILL_IND ,
COST_DUE_AMT ,
COST_BASIS_AMT ,
COST_BASIS_QLTY_CD ,
CURR_PREM_CR_BASE_AMT ,
CURR_YR_PYMNT_AMT ,
CURR_PREM_CRDT_LTC_AMT ,
CURR_PREM_CRDT_LTC_QLTY_CD ,
NXT_YR_PREM_CRDT_LTC_AMT ,
NXT_YR_PREM_CRDT_LTC_QLTY_CD ,
EWL_DFCT_PREM_PAYUP_AMT ,
EWL_DFCT_PD_TO_YR_MTH ,
FRAC_PREM_CR_BASE_AMT ,
FRAC_PREM_CR_LTC_AMT ,
FRAC_PREM_CR_LTC_QLTY_CD ,
GRS_ANNL_PREM_AMT ,
GRS_ANNL_PREM_QLTY_CD ,
GRS_PREM_FPDUP_ADDNS_AMT ,
LTCIR_RTRN_PREM_AMT ,
LTCIR_RTRN_PREM_QLTY_CD ,
LTCIR_RDUC_ADDNS_AMT ,
LTCIR_RDUC_ADDNS_QLTY_CD ,
LTC_EXTD_BEN_POOL_AMT ,
LTC_EXTD_BEN_POOL_QLTY_CD ,
MAX_ANNL_PYMT_YR ,
NB_PREM_PD_AMT ,
NXT_YR_PREM_CR_BASE_AMT ,
TGT_PREM_AMT ,
TGT_PREM_QLTY_CD ,
TOT_MTHLY_PREM_AMT ,
TOT_MTHLY_PREM_QLTY_CD ,
UNERND_PAST_DUE_PREM_AMT ,
UNERND_PAST_DUE_PREM_QLTY_CD ,
VANISH_BILL_AMT ,
CURR_IND ,
SRC_DEL_IND ,
SRC_SYS_ID ,
RUN_ID ,
UPDT_RUN_ID ,
TRANS_DT ,
MPO_APO_PD_AMT_QLTY_CD ,
APO_CR_AMT_QLTY_CD ,
BASE_RDR_ANNL_PREM_QLTY_CD ,
CURR_PREM_CR_BASE_QLTY_CD ,
FRAC_PREM_CR_BASE_QLTY_CD ,
GRS_PREM_FPDUP_ADDNS_QLTY_CD ,
NXT_YR_PREM_CR_BASE_QLTY_CD ,
LISR_DISAB_COST ,
PYMNT_DRFT_DY_CD ,
YTD_PREM_AMT ,
INV_ACCT_NO ,
GRP_ACCT_TYP ,
GRP_ACCT_NBR ,
LST_BILL_MTHD ,
PAC_ACCT_ID ,
PAC_ACCT_TYP ,
BANK_NM ,
BILL_ARGMT_IDENT ,
BILL_MTHD_TYP_CD ,
CNSLDT_BILL_TYP_CD ,
ANNUALIZED_PREM_AMT ,
ALIR_BILL_AMT ,
ALIR_BILL_AMT_QLTY_CD ,
BANK_ID ,
PERM_FLAT_XTR_PREM_AMT ,
TEMP_FLAT_XTR_PREM_AMT ,
PERM_FLAT_XTR_COST_AMT ,
TEMP_FLAT_XTR_COST_AMT ,
TOT_ANNL_PREM_AMT ,
TOT_ANNL_PREM_AMT_QLTY_CD ,
SRC_BILL_MODE_CD ,
INIT_PREM_AMT ,
PYTD_PREM_AMT ,
PREM_REFUND_AMT ,
PREM_REFUND_QLTY_CD ,
PRO_RATA_REFUND_AMT ,
PRO_RATA_REFUND_QLTY_CD ,
ADV_PREM_REFUND_AMT ,
ADV_PREM_REFUND_QLTY_CD,
true

from
(
select t1.*, row_number() over (partition by t1.agmt_id, t1.run_id, t1.trans_dt order by t1.agmt_bill_to_dt desc) as rec_num
from
edw_staging.agmt_bill_vw_tmp1 t1
)calc
where rec_num=1
);

insert into edw_staging.aifrps_agmt_bill_vw_aifrps_snapshot
(AGMT_ID ,
AGMT_DATA_FR_DT ,
AGMT_BILL_FR_DT ,
AGMT_BILL_TO_DT ,
HLDG_KEY_PFX ,
HLDG_KEY ,
HLDG_KEY_SFX ,
CARR_ADMIN_SYS_CD ,
BILL_MODE_CD ,
EBILL_PREF_IND ,
NO_BILL_RSN_CD ,
BILL_FREQ_WD ,
PREM_TAX_STATE_CD ,
RTN_CHK_CD ,
SDO_MPO_APO_CD ,
PD_IN_ADV_YR_CNT ,
SDO_PYMT_TYP_CD ,
FEE_IND ,
FRST_YR_IND ,
IPO_IND ,
LTC_ACTY_IND ,
LTC_PREM_ADJ_IND ,
LATE_PYMT_OFFER_END_DT ,
VANISH_PREM_EFF_DT ,
ALIR_BILL_PREM_AMT ,
ALIR_BILL_PREM_QLTY_CD ,
AL_SUP_TRMN_AMT ,
MPO_APO_NET_PYMT_DUE_AMT ,
MPO_APO_NET_PYMT_QLTY_CD ,
MPO_APO_PD_AMT ,
APO_CR_AMT ,
ANNL_PREM_AMT ,
ANNL_PREM_AMT_QLTY_CD ,
BASE_RDR_MTHLY_PREM_AMT ,
BASE_RDR_MTHLY_PREM_QLTY_CD ,
BASE_RDR_ANNL_PREM_AMT ,
BILL_PREM_AMT ,
BILL_PREM_QLTY_CD ,
CLI_PREM_BILL_IND ,
COST_DUE_AMT ,
COST_BASIS_AMT ,
COST_BASIS_QLTY_CD ,
CURR_PREM_CR_BASE_AMT ,
CURR_YR_PYMNT_AMT ,
CURR_PREM_CRDT_LTC_AMT ,
CURR_PREM_CRDT_LTC_QLTY_CD ,
NXT_YR_PREM_CRDT_LTC_AMT ,
NXT_YR_PREM_CRDT_LTC_QLTY_CD ,
EWL_DFCT_PREM_PAYUP_AMT ,
EWL_DFCT_PD_TO_YR_MTH ,
FRAC_PREM_CR_BASE_AMT ,
FRAC_PREM_CR_LTC_AMT ,
FRAC_PREM_CR_LTC_QLTY_CD ,
GRS_ANNL_PREM_AMT ,
GRS_ANNL_PREM_QLTY_CD ,
GRS_PREM_FPDUP_ADDNS_AMT ,
LTCIR_RTRN_PREM_AMT ,
LTCIR_RTRN_PREM_QLTY_CD ,
LTCIR_RDUC_ADDNS_AMT ,
LTCIR_RDUC_ADDNS_QLTY_CD ,
LTC_EXTD_BEN_POOL_AMT ,
LTC_EXTD_BEN_POOL_QLTY_CD ,
MAX_ANNL_PYMT_YR ,
NB_PREM_PD_AMT ,
NXT_YR_PREM_CR_BASE_AMT ,
TGT_PREM_AMT ,
TGT_PREM_QLTY_CD ,
TOT_MTHLY_PREM_AMT ,
TOT_MTHLY_PREM_QLTY_CD ,
UNERND_PAST_DUE_PREM_AMT ,
UNERND_PAST_DUE_PREM_QLTY_CD ,
VANISH_BILL_AMT ,
CURR_IND ,
SRC_DEL_IND ,
SRC_SYS_ID ,
RUN_ID ,
UPDT_RUN_ID ,
TRANS_DT ,
MPO_APO_PD_AMT_QLTY_CD ,
APO_CR_AMT_QLTY_CD ,
BASE_RDR_ANNL_PREM_QLTY_CD ,
CURR_PREM_CR_BASE_QLTY_CD ,
FRAC_PREM_CR_BASE_QLTY_CD ,
GRS_PREM_FPDUP_ADDNS_QLTY_CD ,
NXT_YR_PREM_CR_BASE_QLTY_CD ,
LISR_DISAB_COST ,
PYMNT_DRFT_DY_CD ,
YTD_PREM_AMT ,
INV_ACCT_NO ,
GRP_ACCT_TYP ,
GRP_ACCT_NBR ,
LST_BILL_MTHD ,
PAC_ACCT_ID ,
PAC_ACCT_TYP ,
BANK_NM ,
BILL_ARGMT_IDENT ,
BILL_MTHD_TYP_CD ,
CNSLDT_BILL_TYP_CD ,
ANNUALIZED_PREM_AMT ,
ALIR_BILL_AMT ,
ALIR_BILL_AMT_QLTY_CD ,
BANK_ID ,
PERM_FLAT_XTR_PREM_AMT ,
TEMP_FLAT_XTR_PREM_AMT ,
PERM_FLAT_XTR_COST_AMT ,
TEMP_FLAT_XTR_COST_AMT ,
TOT_ANNL_PREM_AMT ,
TOT_ANNL_PREM_AMT_QLTY_CD ,
SRC_BILL_MODE_CD ,
INIT_PREM_AMT ,
PYTD_PREM_AMT ,
PREM_REFUND_AMT ,
PREM_REFUND_QLTY_CD ,
PRO_RATA_REFUND_AMT ,
PRO_RATA_REFUND_QLTY_CD ,
ADV_PREM_REFUND_AMT ,
ADV_PREM_REFUND_QLTY_CD,
current_batch
)
(
select
AGMT_ID ,
AGMT_DATA_FR_DT ,
AGMT_BILL_FR_DT ,
AGMT_BILL_TO_DT ,
HLDG_KEY_PFX ,
HLDG_KEY ,
HLDG_KEY_SFX ,
CARR_ADMIN_SYS_CD ,
BILL_MODE_CD ,
EBILL_PREF_IND ,
NO_BILL_RSN_CD ,
BILL_FREQ_WD ,
PREM_TAX_STATE_CD ,
RTN_CHK_CD ,
SDO_MPO_APO_CD ,
PD_IN_ADV_YR_CNT ,
SDO_PYMT_TYP_CD ,
FEE_IND ,
FRST_YR_IND ,
IPO_IND ,
LTC_ACTY_IND ,
LTC_PREM_ADJ_IND ,
LATE_PYMT_OFFER_END_DT ,
VANISH_PREM_EFF_DT ,
ALIR_BILL_PREM_AMT ,
ALIR_BILL_PREM_QLTY_CD ,
AL_SUP_TRMN_AMT ,
MPO_APO_NET_PYMT_DUE_AMT ,
MPO_APO_NET_PYMT_QLTY_CD ,
MPO_APO_PD_AMT ,
APO_CR_AMT ,
ANNL_PREM_AMT ,
ANNL_PREM_AMT_QLTY_CD ,
BASE_RDR_MTHLY_PREM_AMT ,
BASE_RDR_MTHLY_PREM_QLTY_CD ,
BASE_RDR_ANNL_PREM_AMT ,
BILL_PREM_AMT ,
BILL_PREM_QLTY_CD ,
CLI_PREM_BILL_IND ,
COST_DUE_AMT ,
COST_BASIS_AMT ,
COST_BASIS_QLTY_CD ,
CURR_PREM_CR_BASE_AMT ,
CURR_YR_PYMNT_AMT ,
CURR_PREM_CRDT_LTC_AMT ,
CURR_PREM_CRDT_LTC_QLTY_CD ,
NXT_YR_PREM_CRDT_LTC_AMT ,
NXT_YR_PREM_CRDT_LTC_QLTY_CD ,
EWL_DFCT_PREM_PAYUP_AMT ,
EWL_DFCT_PD_TO_YR_MTH ,
FRAC_PREM_CR_BASE_AMT ,
FRAC_PREM_CR_LTC_AMT ,
FRAC_PREM_CR_LTC_QLTY_CD ,
GRS_ANNL_PREM_AMT ,
GRS_ANNL_PREM_QLTY_CD ,
GRS_PREM_FPDUP_ADDNS_AMT ,
LTCIR_RTRN_PREM_AMT ,
LTCIR_RTRN_PREM_QLTY_CD ,
LTCIR_RDUC_ADDNS_AMT ,
LTCIR_RDUC_ADDNS_QLTY_CD ,
LTC_EXTD_BEN_POOL_AMT ,
LTC_EXTD_BEN_POOL_QLTY_CD ,
MAX_ANNL_PYMT_YR ,
NB_PREM_PD_AMT ,
NXT_YR_PREM_CR_BASE_AMT ,
TGT_PREM_AMT ,
TGT_PREM_QLTY_CD ,
TOT_MTHLY_PREM_AMT ,
TOT_MTHLY_PREM_QLTY_CD ,
UNERND_PAST_DUE_PREM_AMT ,
UNERND_PAST_DUE_PREM_QLTY_CD ,
VANISH_BILL_AMT ,
CURR_IND ,
SRC_DEL_IND ,
SRC_SYS_ID ,
RUN_ID ,
UPDT_RUN_ID ,
TRANS_DT ,
MPO_APO_PD_AMT_QLTY_CD ,
APO_CR_AMT_QLTY_CD ,
BASE_RDR_ANNL_PREM_QLTY_CD ,
CURR_PREM_CR_BASE_QLTY_CD ,
FRAC_PREM_CR_BASE_QLTY_CD ,
GRS_PREM_FPDUP_ADDNS_QLTY_CD ,
NXT_YR_PREM_CR_BASE_QLTY_CD ,
LISR_DISAB_COST ,
PYMNT_DRFT_DY_CD ,
YTD_PREM_AMT ,
INV_ACCT_NO ,
GRP_ACCT_TYP ,
GRP_ACCT_NBR ,
LST_BILL_MTHD ,
PAC_ACCT_ID ,
PAC_ACCT_TYP ,
BANK_NM ,
BILL_ARGMT_IDENT ,
BILL_MTHD_TYP_CD ,
CNSLDT_BILL_TYP_CD ,
ANNUALIZED_PREM_AMT ,
ALIR_BILL_AMT ,
ALIR_BILL_AMT_QLTY_CD ,
BANK_ID ,
PERM_FLAT_XTR_PREM_AMT ,
TEMP_FLAT_XTR_PREM_AMT ,
PERM_FLAT_XTR_COST_AMT ,
TEMP_FLAT_XTR_COST_AMT ,
TOT_ANNL_PREM_AMT ,
TOT_ANNL_PREM_AMT_QLTY_CD ,
SRC_BILL_MODE_CD ,
INIT_PREM_AMT ,
PYTD_PREM_AMT ,
PREM_REFUND_AMT ,
PREM_REFUND_QLTY_CD ,
PRO_RATA_REFUND_AMT ,
PRO_RATA_REFUND_QLTY_CD ,
ADV_PREM_REFUND_AMT ,
ADV_PREM_REFUND_QLTY_CD,
true
from
edw_staging.agmt_bill_vw_tmp2
);