--from aifrps, fact records will be based on dim_agreement_natural_key_hash and trans_dt.
--check-sum is not part of the comparison anymore
--clean up pre-work table and work table
delete from edw_staging.aifrps_fact_agreement_detail_initial_load_pre_work;
delete from edw_work.aifrps_fact_agreement_detail_initial_load;

--step 1, populate all records into pre-work table
insert into edw_staging.aifrps_fact_agreement_detail_initial_load_pre_work
    (
    fact_agreement_detail_natural_key_hash_uuid,
    dim_agreement_natural_key_hash_uuid,
    pay7_period_premium_amt,
    pay7_period_premium_end_dt,
    pay7_period_premium_end_dt_quality_cde,
    pay7_period_premium_quality_cde,
    pay7_period_premium_start_dt,
    pay7_period_premium_start_dt_quality_cde,
    tcc_amt,
    total_monthly_benefit_amt,
    ultimate_face_amt,
    grace_period_payment_amt,
    grace_period_payment_quality_cde,
    policy_unit_face_amt,
    policy_income_amt,
    agreement_dividend_year_nr,
    current_dividend_amt,
    accumulated_dividend_amt,
    accumulated_dividend_quality_cde,
    rp_current_dividend_month_txt,
    rp_current_dividend_year_txt,
    rp_current_dividend_amt,
    rp_dividend_amt,
    rp_dividend_amt_quality_cde,
    ri_dividend_amt_quality_cde,
    ri_dividend_amt,
    applied_dividend_amt,
    applied_dividend_quality_cde,
    base_dividend_amt,
    base_dividend_quality_cde,
    previous_year_dividend_amt,
    previous_year_dividend_quality_cde,
    dividend_accumulated_available_amt,
    dividend_accumulated_available_quality_cde,
    dividend_available_amt,
    dividend_available_quality_cde,
    last_dividend_credit_amt,
    last_dividend_credit_quality_cde,
    ltcir_dividend_benefit_pool_amt,
    ltcir_dividend_benefit_pool_quality_cde,
    interest_on_dividend_accumulated_to_dt_amt,
    interest_on_dividend_accumulated_to_dt_quality_cde,
    settlement_dividend_amt,
    settlement_dividend_quality_cde,
    dividend_accumulated_tax_amt,
    dividend_accumulated_tax_quality_cde,
    dividend_mo_da,

    bill_mode_cde,
    ebill_preference_cde,
    no_bill_reason_cde,
    bill_frequency_txt,
    premium_tax_state_cde,
    returned_check_cde,
    sdo_mpo_apo_cde,
    paid_in_advance_year_cnt,
    sdo_payment_type_cde,
    policy_fee_ind,
    first_year_ind,
    ipo_ind,
    ltc_activity_cde,
    ltc_premium_adjustment_ind,
    late_payment_offer_end_dt,
    vanishing_premium_effective_dt,
    alir_bill_premium_amt,
    alir_bill_premium_quality_cde,
    al_sup_termination_amt,
    mpo_apo_net_payment_due_amt,
    mpo_apo_net_payment_quality_cde,
    mpo_apo_paid_amt,
    apo_credit_amt,
    annual_premium_amt,
    annual_premium_quality_cde,
    base_rider_monthly_premium_amt,
    base_rider_monthly_premium_quality_cde,
    base_rider_annual_premium_amt,
    bill_premium_amt,
    bill_premium_quality_cde,
    cli_premium_bill_cde,
    cost_due_amt,
    cost_basis_amt,
    cost_basis_quality_cde,
    current_premium_credit_base_amt,
    current_year_payment_amt,
    current_premium_credit_ltc_amt,
    current_premium_credit_ltc_quality_cde,
    next_year_premium_credit_ltc_amt,
    next_year_premium_credit_ltc_quality_cde,
    ewl_deficit_premium_payup_amt,
    ewl_deficit_paid_to_year_month_txt,
    fraction_premium_credit_base_amt,
    fraction_premium_credit_ltc_amt,
    fraction_premium_credit_ltc_quality_cde,
    gross_annual_premium_amt,
    gross_annual_premium_quality_cde,
    gross_premium_fpdup_addns_amt,
    ltcir_return_premium_amt,
    ltcir_return_premium_quality_cde,
    ltcir_reduced_addns_amt,
    ltcir_reduced_addns_quality_cde,
    ltc_extended_benefit_pool_amt,
    ltc_extended_benefit_pool_quality_cde,
    max_annual_payment_year_nr,
    new_business_premium_paid_amt,
    next_year_premium_credit_base_amt,
    target_premium_amt,
    target_premium_quality_cde,
    total_monthly_premium_amt,
    total_monthly_premium_quality_cde,
    unearned_past_due_premium_amt,
    unearned_past_due_premium_quality_cde,
    vanish_bill_amt,

    mpo_apo_paid_amt_quality_cde,
    apo_credit_amt_quality_cde,
    base_rider_annual_premium_quality_cde,
    current_premium_credit_base_quality_cde,
    fraction_premium_credit_base_quality_cde,
    gross_premium_fpdup_addns_quality_cde,
    next_year_premium_credit_base_quality_cde,
    lisr_disability_cost_amt,
    payment_draft_dy_cde,
    ytd_premium_amt,
    invoice_account_id_txt,
    group_account_type_cde,
    group_account_nr_txt,
    last_bill_method_cde,
    pac_account_id_txt,
    pac_account_type_cde,
    bank_nm,
    billing_arrangement_id_txt,
    bill_method_type_cde,
    consolidated_bill_type_cde,
    annualized_premium_amt,
    alir_bill_amt,
    alir_bill_amt_quality_cde,
    bank_id,
    permenant_flat_extra_premium_amt,
    temperory_flat_extra_premium_amt,
    permenant_flat_extra_cost_amt,
    temperory_flat_extra_cost_amt,
    total_annual_premium_amt,
    total_annual_premium_quality_cde,
    source_bill_mode_cde,
    initial_premium_amt,
    pytd_premium_amt,
    premium_refund_amt,
    premium_refund_quality_cde,
    pro_rata_refund_amt,
    pro_rata_refund_quality_cde,
    advance_premium_refund_amt,
    advance_premium_refund_quality_cde,

    paid_to_dt,
    paid_to_dt_txt,
    last_premium_adjustment_dt,
    last_premium_collection_dt,
    last_premium_paid_dt,
    last_transaction_dt,
    premium_accumulated_amt_quality_cde,
    premium_accumulated_amt,
    source_delete_ind,

    last_deposit_dt,
    last_deposit_amt,
    last_deposit_amt_quality_cde,
    administration_charge_amt,
    minus_1_tax_rt,
    bill_to_dt,
    apm_next_bill_dt,
    last_premium_paid_amt,
    check_sum,
    source_system_id,
    audit_id,
    update_audit_id,
    begin_dt,
    begin_dtm,
    transaction_dt,
    transaction_dtm
    )
select
    uuid_gen(
        agreement_source_cde,
        'Ipa',
        agreement_nr_pfx,
        agreement_nr,
        agreement_nr_sfx,
        begin_dt
    )::uuid as fact_agreement_detail_natural_key_hash_uuid,
    uuid_gen(
        agreement_source_cde,
        'Ipa',
        agreement_nr_pfx,
        agreement_nr,
        agreement_nr_sfx
    )::uuid as dim_agreement_natural_key_hash_uuid,
    pay7_period_premium_amt,
    pay7_period_premium_end_dt,
    pay7_period_premium_end_dt_quality_cde,
    pay7_period_premium_quality_cde,
    pay7_period_premium_start_dt,
    pay7_period_premium_start_dt_quality_cde,
    tcc_amt,
    total_monthly_benefit_amt,
    ultimate_face_amt,
    grace_period_payment_amt,
    grace_period_payment_quality_cde,
    policy_unit_face_amt,
    policy_income_amt,
    agreement_dividend_year_nr,
    current_dividend_amt,
    accumulated_dividend_amt,
    accumulated_dividend_quality_cde,
    rp_current_dividend_month_txt,
    rp_current_dividend_year_txt,
    rp_current_dividend_amt,
    rp_dividend_amt,
    rp_dividend_amt_quality_cde,
    ri_dividend_amt_quality_cde,
    ri_dividend_amt,
    applied_dividend_amt,
    applied_dividend_quality_cde,
    base_dividend_amt,
    base_dividend_quality_cde,
    previous_year_dividend_amt,
    previous_year_dividend_quality_cde,
    dividend_accumulated_available_amt,
    dividend_accumulated_available_quality_cde,
    dividend_available_amt,
    dividend_available_quality_cde,
    last_dividend_credit_amt,
    last_dividend_credit_quality_cde,
    ltcir_dividend_benefit_pool_amt,
    ltcir_dividend_benefit_pool_quality_cde,
    interest_on_dividend_accumulated_to_dt_amt,
    interest_on_dividend_accumulated_to_dt_quality_cde,
    settlement_dividend_amt,
    settlement_dividend_quality_cde,
    dividend_accumulated_tax_amt,
    dividend_accumulated_tax_quality_cde,
    dividend_mo_da,

    bill_mode_cde,
    ebill_preference_cde,
    no_bill_reason_cde,
    bill_frequency_txt,
    premium_tax_state_cde,
    returned_check_cde,
    sdo_mpo_apo_cde,
    paid_in_advance_year_cnt,
    sdo_payment_type_cde,
    policy_fee_ind,
    first_year_ind,
    ipo_ind,
    ltc_activity_cde,
    ltc_premium_adjustment_ind,
    late_payment_offer_end_dt,
    vanishing_premium_effective_dt,
    alir_bill_premium_amt,
    alir_bill_premium_quality_cde,
    al_sup_termination_amt,
    mpo_apo_net_payment_due_amt,
    mpo_apo_net_payment_quality_cde,
    mpo_apo_paid_amt,
    apo_credit_amt,
    annual_premium_amt,
    annual_premium_quality_cde,
    base_rider_monthly_premium_amt,
    base_rider_monthly_premium_quality_cde,
    base_rider_annual_premium_amt,
    bill_premium_amt,
    bill_premium_quality_cde,
    cli_premium_bill_cde,
    cost_due_amt,
    cost_basis_amt,
    cost_basis_quality_cde,
    current_premium_credit_base_amt,
    current_year_payment_amt,
    current_premium_credit_ltc_amt,
    current_premium_credit_ltc_quality_cde,
    next_year_premium_credit_ltc_amt,
    next_year_premium_credit_ltc_quality_cde,
    ewl_deficit_premium_payup_amt,
    ewl_deficit_paid_to_year_month_txt,
    fraction_premium_credit_base_amt,
    fraction_premium_credit_ltc_amt,
    fraction_premium_credit_ltc_quality_cde,
    gross_annual_premium_amt,
    gross_annual_premium_quality_cde,
    gross_premium_fpdup_addns_amt,
    ltcir_return_premium_amt,
    ltcir_return_premium_quality_cde,
    ltcir_reduced_addns_amt,
    ltcir_reduced_addns_quality_cde,
    ltc_extended_benefit_pool_amt,
    ltc_extended_benefit_pool_quality_cde,
    max_annual_payment_year_nr,
    new_business_premium_paid_amt,
    next_year_premium_credit_base_amt,
    target_premium_amt,
    target_premium_quality_cde,
    total_monthly_premium_amt,
    total_monthly_premium_quality_cde,
    unearned_past_due_premium_amt,
    unearned_past_due_premium_quality_cde,
    vanish_bill_amt,

    mpo_apo_paid_amt_quality_cde,
    apo_credit_amt_quality_cde,
    base_rider_annual_premium_quality_cde,
    current_premium_credit_base_quality_cde,
    fraction_premium_credit_base_quality_cde,
    gross_premium_fpdup_addns_quality_cde,
    next_year_premium_credit_base_quality_cde,
    lisr_disability_cost_amt,
    payment_draft_dy_cde,
    ytd_premium_amt,
    invoice_account_id_txt,
    group_account_type_cde,
    group_account_nr_txt,
    last_bill_method_cde,
    pac_account_id_txt,
    pac_account_type_cde,
    bank_nm,
    billing_arrangement_id_txt,
    bill_method_type_cde,
    consolidated_bill_type_cde,
    annualized_premium_amt,
    alir_bill_amt,
    alir_bill_amt_quality_cde,
    bank_id,
    permenant_flat_extra_premium_amt,
    temperory_flat_extra_premium_amt,
    permenant_flat_extra_cost_amt,
    temperory_flat_extra_cost_amt,
    total_annual_premium_amt,
    total_annual_premium_quality_cde,
    source_bill_mode_cde,
    initial_premium_amt,
    pytd_premium_amt,
    premium_refund_amt,
    premium_refund_quality_cde,
    pro_rata_refund_amt,
    pro_rata_refund_quality_cde,
    advance_premium_refund_amt,
    advance_premium_refund_quality_cde,

    paid_to_dt,
    paid_to_dt_txt,
    last_premium_adjustment_dt,
    last_premium_collection_dt,
    last_premium_paid_dt,
    last_transaction_dt,
    premium_accumulated_amt_quality_cde,
    premium_accumulated_amt,
    source_delete_ind,

    last_deposit_dt,
    last_deposit_amt,
    last_deposit_amt_quality_cde,
    administration_charge_amt,
    minus_1_tax_rt,
    bill_to_dt,
    apm_next_bill_dt,
    last_premium_paid_amt,
    
  /* 2020-11-17: Modifying the check_sum logic to use only the key attribute. As this is fact table so check_sum is 
  not used for change detection (SCD 2).  To avoid performace issue while loading the History data making this
  logic change. 
  */
    uuid_gen(
		agreement_source_cde,
        'Ipa',
        agreement_nr_pfx,
        agreement_nr,
        agreement_nr_sfx,
        begin_dt

        )::uuid as check_sum,


    266 as source_system_id,
    audit_id,
    update_audit_id,
    begin_dt,
    begin_dt::timestamp(6) as begin_dtm,
    begin_dt as transaction_dt,
    begin_dt::timestamp(6) as transaction_dtm
from (

select
    clean_string(agreement_sdt.trnslt_fld_val) as agreement_source_cde,
    udf_isnum_lpad(agmt_bill.hldg_key_pfx, 20, '0', true) as agreement_nr_pfx,
    lpad(agmt_bill.hldg_key::varchar, 20, '0') as agreement_nr,
    udf_isnum_lpad(agmt_bill.hldg_key_sfx, 20, '0', true) as agreement_nr_sfx,

    NULL  	as pay7_period_premium_amt,
    NULL 	as pay7_period_premium_end_dt,
    NULL	as pay7_period_premium_end_dt_quality_cde,
    NULL	as pay7_period_premium_quality_cde,
    NULL	as pay7_period_premium_start_dt,
    NULL	as pay7_period_premium_start_dt_quality_cde,
    NULL	as tcc_amt,
    NULL	as total_monthly_benefit_amt,
    NULL	as ultimate_face_amt,
    NULL	as grace_period_payment_amt,
    NULL 	as grace_period_payment_quality_cde,
    NULL	as policy_unit_face_amt,
    NULL	as policy_income_amt,
    NULL	as agreement_dividend_year_nr, --maybe
    NULL	as current_dividend_amt,
    NULL	as accumulated_dividend_amt,
    NULL	as accumulated_dividend_quality_cde,
    NULL	as rp_current_dividend_month_txt,
    NULL	as rp_current_dividend_year_txt,
    NULL	as rp_current_dividend_amt,
    NULL	as rp_dividend_amt,
    NULL	as rp_dividend_amt_quality_cde,
    NULL	as ri_dividend_amt_quality_cde,
    NULL	as ri_dividend_amt,
    NULL	as applied_dividend_amt,
    NULL	as applied_dividend_quality_cde,
    NULL	as base_dividend_amt,
    NULL	as base_dividend_quality_cde,
    NULL	as previous_year_dividend_amt,
    NULL	as previous_year_dividend_quality_cde,
    NULL	as dividend_accumulated_available_amt,
    NULL	as dividend_accumulated_available_quality_cde,
    NULL	as dividend_available_amt,
    NULL	as dividend_available_quality_cde,
    NULL	as last_dividend_credit_amt,
    NULL	as last_dividend_credit_quality_cde,
    NULL	as ltcir_dividend_benefit_pool_amt,
    NULL	as ltcir_dividend_benefit_pool_quality_cde,
    NULL	as interest_on_dividend_accumulated_to_dt_amt,
    NULL	as interest_on_dividend_accumulated_to_dt_quality_cde,
    NULL	as settlement_dividend_amt,
    NULL	as settlement_dividend_quality_cde,
    NULL	as dividend_accumulated_tax_amt,
    NULL	as dividend_accumulated_tax_quality_cde,
    NULL	as dividend_mo_da,
	agmt_bill.bill_mode_cd as bill_mode_cde,
    agmt_bill.ebill_pref_ind as ebill_preference_cde,
    agmt_bill.no_bill_rsn_cd as no_bill_reason_cde,
    agmt_bill.bill_freq_wd as bill_frequency_txt,
    agmt_bill.prem_tax_state_cd as premium_tax_state_cde,
    agmt_bill.rtn_chk_cd as returned_check_cde,
    agmt_bill.sdo_mpo_apo_cd as sdo_mpo_apo_cde,
    agmt_bill.pd_in_adv_yr_cnt as paid_in_advance_year_cnt,
    agmt_bill.sdo_pymt_typ_cd as sdo_payment_type_cde,
    case when agmt_bill.fee_ind = '' then null else agmt_bill.fee_ind::boolean end as policy_fee_ind,
    case when agmt_bill.frst_yr_ind = '' then null else agmt_bill.frst_yr_ind::boolean end as first_year_ind,
    case when agmt_bill.ipo_ind = '' then null else agmt_bill.ipo_ind::boolean end as ipo_ind,
    agmt_bill.ltc_acty_ind as ltc_activity_cde,
    case when agmt_bill.ltc_prem_adj_ind = '' then null else agmt_bill.ltc_prem_adj_ind::boolean end as ltc_premium_adjustment_ind,
    agmt_bill.late_pymt_offer_end_dt as late_payment_offer_end_dt,
    agmt_bill.vanish_prem_eff_dt as vanishing_premium_effective_dt,
    agmt_bill.alir_bill_prem_amt as alir_bill_premium_amt,
    agmt_bill.alir_bill_prem_qlty_cd as alir_bill_premium_quality_cde,
    agmt_bill.al_sup_trmn_amt as al_sup_termination_amt,
    agmt_bill.mpo_apo_net_pymt_due_amt as mpo_apo_net_payment_due_amt,
    agmt_bill.mpo_apo_net_pymt_qlty_cd as mpo_apo_net_payment_quality_cde,
    agmt_bill.mpo_apo_pd_amt as mpo_apo_paid_amt,
    agmt_bill.apo_cr_amt as apo_credit_amt,
    agmt_bill.annl_prem_amt as annual_premium_amt,
    agmt_bill.annl_prem_amt_qlty_cd as annual_premium_quality_cde,
    agmt_bill.base_rdr_mthly_prem_amt as base_rider_monthly_premium_amt,
    agmt_bill.base_rdr_mthly_prem_qlty_cd as base_rider_monthly_premium_quality_cde,
    agmt_bill.base_rdr_annl_prem_amt as base_rider_annual_premium_amt,
    agmt_bill.bill_prem_amt as bill_premium_amt,
    agmt_bill.bill_prem_qlty_cd as bill_premium_quality_cde,
    agmt_bill.cli_prem_bill_ind as cli_premium_bill_cde,
    agmt_bill.cost_due_amt as cost_due_amt,
    agmt_bill.cost_basis_amt as cost_basis_amt,
    agmt_bill.cost_basis_qlty_cd as cost_basis_quality_cde,
    agmt_bill.curr_prem_cr_base_amt as current_premium_credit_base_amt,
    agmt_bill.curr_yr_pymnt_amt as current_year_payment_amt,
    agmt_bill.curr_prem_crdt_ltc_amt as current_premium_credit_ltc_amt,
    agmt_bill.curr_prem_crdt_ltc_qlty_cd as current_premium_credit_ltc_quality_cde,
    agmt_bill.nxt_yr_prem_crdt_ltc_amt as next_year_premium_credit_ltc_amt,
    agmt_bill.nxt_yr_prem_crdt_ltc_qlty_cd as next_year_premium_credit_ltc_quality_cde,
    agmt_bill.ewl_dfct_prem_payup_amt as ewl_deficit_premium_payup_amt,
    agmt_bill.ewl_dfct_pd_to_yr_mth as ewl_deficit_paid_to_year_month_txt,
    agmt_bill.frac_prem_cr_base_amt as fraction_premium_credit_base_amt,
    agmt_bill.frac_prem_cr_ltc_amt as fraction_premium_credit_ltc_amt,
    agmt_bill.frac_prem_cr_ltc_qlty_cd as fraction_premium_credit_ltc_quality_cde,
    agmt_bill.grs_annl_prem_amt as gross_annual_premium_amt,
    agmt_bill.grs_annl_prem_qlty_cd as gross_annual_premium_quality_cde,
    agmt_bill.grs_prem_fpdup_addns_amt as gross_premium_fpdup_addns_amt,
    agmt_bill.ltcir_rtrn_prem_amt as ltcir_return_premium_amt,
    agmt_bill.ltcir_rtrn_prem_qlty_cd as ltcir_return_premium_quality_cde,
    agmt_bill.ltcir_rduc_addns_amt as ltcir_reduced_addns_amt,
    agmt_bill.ltcir_rduc_addns_qlty_cd as ltcir_reduced_addns_quality_cde,
    agmt_bill.ltc_extd_ben_pool_amt as ltc_extended_benefit_pool_amt,
    agmt_bill.ltc_extd_ben_pool_qlty_cd as ltc_extended_benefit_pool_quality_cde,
    agmt_bill.max_annl_pymt_yr::varchar as max_annual_payment_year_nr,
    agmt_bill.nb_prem_pd_amt as new_business_premium_paid_amt,
    agmt_bill.nxt_yr_prem_cr_base_amt as next_year_premium_credit_base_amt,
    agmt_bill.tgt_prem_amt as target_premium_amt,
    agmt_bill.tgt_prem_qlty_cd as target_premium_quality_cde,
    agmt_bill.tot_mthly_prem_amt as total_monthly_premium_amt,
    agmt_bill.tot_mthly_prem_qlty_cd as total_monthly_premium_quality_cde,
    agmt_bill.unernd_past_due_prem_amt as unearned_past_due_premium_amt,
    agmt_bill.unernd_past_due_prem_qlty_cd as unearned_past_due_premium_quality_cde,
    agmt_bill.vanish_bill_amt as vanish_bill_amt,
	agmt_bill.mpo_apo_pd_amt_qlty_cd as mpo_apo_paid_amt_quality_cde,
    agmt_bill.apo_cr_amt_qlty_cd as apo_credit_amt_quality_cde,
    agmt_bill.base_rdr_annl_prem_qlty_cd as base_rider_annual_premium_quality_cde,
    agmt_bill.curr_prem_cr_base_qlty_cd as current_premium_credit_base_quality_cde,
    agmt_bill.frac_prem_cr_base_qlty_cd as fraction_premium_credit_base_quality_cde,
    agmt_bill.grs_prem_fpdup_addns_qlty_cd as gross_premium_fpdup_addns_quality_cde,
    agmt_bill.nxt_yr_prem_cr_base_qlty_cd as next_year_premium_credit_base_quality_cde,
    agmt_bill.lisr_disab_cost as lisr_disability_cost_amt,
    agmt_bill.pymnt_drft_dy_cd as payment_draft_dy_cde,
    agmt_bill.ytd_prem_amt as ytd_premium_amt,
    agmt_bill.inv_acct_no as invoice_account_id_txt,
    agmt_bill.grp_acct_typ as group_account_type_cde,
    agmt_bill.grp_acct_nbr as group_account_nr_txt,
    agmt_bill.lst_bill_mthd as last_bill_method_cde,
    agmt_bill.pac_acct_id as pac_account_id_txt,
    agmt_bill.pac_acct_typ as pac_account_type_cde,
    agmt_bill.bank_nm as bank_nm,
    agmt_bill.bill_argmt_ident as billing_arrangement_id_txt,
    agmt_bill.bill_mthd_typ_cd as bill_method_type_cde,
    agmt_bill.cnsldt_bill_typ_cd as consolidated_bill_type_cde,
    agmt_bill.annualized_prem_amt as annualized_premium_amt,
    agmt_bill.alir_bill_amt as alir_bill_amt,
    agmt_bill.alir_bill_amt_qlty_cd as alir_bill_amt_quality_cde,
    agmt_bill.bank_id as bank_id,
    agmt_bill.perm_flat_xtr_prem_amt as permenant_flat_extra_premium_amt,
    agmt_bill.temp_flat_xtr_prem_amt as temperory_flat_extra_premium_amt,
    agmt_bill.perm_flat_xtr_cost_amt as permenant_flat_extra_cost_amt,
    agmt_bill.temp_flat_xtr_cost_amt as temperory_flat_extra_cost_amt,
    agmt_bill.tot_annl_prem_amt as total_annual_premium_amt,
    agmt_bill.tot_annl_prem_amt_qlty_cd as total_annual_premium_quality_cde,
    agmt_bill.src_bill_mode_cd as source_bill_mode_cde,
    agmt_bill.init_prem_amt as initial_premium_amt,
    agmt_bill.pytd_prem_amt as pytd_premium_amt,
    agmt_bill.prem_refund_amt as premium_refund_amt,
    agmt_bill.prem_refund_qlty_cd as premium_refund_quality_cde,
    agmt_bill.pro_rata_refund_amt as pro_rata_refund_amt,
    agmt_bill.pro_rata_refund_qlty_cd as pro_rata_refund_quality_cde,
    agmt_bill.adv_prem_refund_amt as advance_premium_refund_amt,
    agmt_bill.adv_prem_refund_qlty_cd as advance_premium_refund_quality_cde,

    agmt_bill_dtl.pd_to_dt as paid_to_dt,
    agmt_bill_dtl.pd_to_dt_txt as paid_to_dt_txt,
    agmt_bill_dtl.lst_adj_dt as last_premium_adjustment_dt,
    agmt_bill_dtl.lst_coll_dt as last_premium_collection_dt,
    agmt_bill_dtl.lst_prem_pd_dt as last_premium_paid_dt,
    agmt_bill_dtl.lst_trans_dt as last_transaction_dt,
    agmt_bill_dtl.prem_accum_amt_qlty_cd as premium_accumulated_amt_quality_cde,
    agmt_bill_dtl.prem_accum_amt as premium_accumulated_amt,
	case
                    when agmt_bill.current_batch = true and upper(agmt_bill.src_del_ind) = 'Y'
                        then true
                    when agmt_bill_dtl.current_batch = true and upper(agmt_bill_dtl.src_del_ind) = 'Y'
                        then true
                    else false
                    end                                                                                          as source_delete_ind,
    --agmt_bill_dtl.src_del_ind::boolean as source_delete_ind,
    agmt_bill_dtl.lst_dpst_dt as last_deposit_dt,
    agmt_bill_dtl.lst_dpst_amt as last_deposit_amt,
    agmt_bill_dtl.lst_dpst_amt_qlty_cd as last_deposit_amt_quality_cde,
    agmt_bill_dtl.admin_chrg_amt as administration_charge_amt,
    agmt_bill_dtl.minus_1_tax_rt as minus_1_tax_rt,
    agmt_bill_dtl.bill_to_dt as bill_to_dt,
    agmt_bill_dtl.apm_nxt_bill_dt as apm_next_bill_dt,
    agmt_bill_dtl.lst_prem_pd_amt as last_premium_paid_amt,
    case when agmt_bill.current_batch = TRUE then agmt_bill.run_id
         when agmt_bill_dtl.current_batch = true then agmt_bill_dtl.run_id
        end as audit_id,
    case when agmt_bill.current_batch = TRUE then agmt_bill.run_id
        when agmt_bill_dtl.current_batch = true then agmt_bill_dtl.run_id
        end as update_audit_id,
--    agmt_bill.run_id as ,audit_id
--    agmt_bill.run_id as update_audit_id,
    :TRANS_DT::date as begin_dt -- this need to in upper-case to get the parameter value

from edw_staging.aifrps_agmt_bill_vw_aifrps_snapshot agmt_bill
left join edw_staging.aifrps_agmt_bill_dtl_vw_aifrps_snapshot agmt_bill_dtl
on agmt_bill.agmt_id = agmt_bill_dtl.agmt_id

left join ( select distinct trnslt_fld_val,src_cde,src_fld_nm,trnslt_fld_nm,src_fld_val from edw_ref.src_data_trnslt
    where upper(src_cde)='PARTY'
    and upper(src_fld_nm)='ADMN_SYS_CDE'
    and upper(trnslt_fld_nm) = 'ADMIN OR SOURCE SYSTEM CODE') agreement_sdt
    on upper(agreement_sdt.src_fld_val) = upper(trim(coalesce(agmt_bill.carr_admin_sys_cd, '')))

where agmt_bill.current_batch = true
or agmt_bill_dtl.current_batch = true) src;



-- Step 2 insert brand new records which don't exist in target based on
-- combination of dim-natural-key
insert into edw_work.aifrps_fact_agreement_detail_initial_load
    (
    fact_agreement_detail_natural_key_hash_uuid,
    dim_agreement_natural_key_hash_uuid,
    pay7_period_premium_amt,
    pay7_period_premium_end_dt,
    pay7_period_premium_end_dt_quality_cde,
    pay7_period_premium_quality_cde,
    pay7_period_premium_start_dt,
    pay7_period_premium_start_dt_quality_cde,
    tcc_amt,
    total_monthly_benefit_amt,
    ultimate_face_amt,
    grace_period_payment_amt,
    grace_period_payment_quality_cde,
    policy_unit_face_amt,
    policy_income_amt,
    agreement_dividend_year_nr,
    current_dividend_amt,
    accumulated_dividend_amt,
    accumulated_dividend_quality_cde,
    rp_current_dividend_month_txt,
    rp_current_dividend_year_txt,
    rp_current_dividend_amt,
    rp_dividend_amt,
    rp_dividend_amt_quality_cde,
    ri_dividend_amt_quality_cde,
    ri_dividend_amt,
    applied_dividend_amt,
    applied_dividend_quality_cde,
    base_dividend_amt,
    base_dividend_quality_cde,
    previous_year_dividend_amt,
    previous_year_dividend_quality_cde,
    dividend_accumulated_available_amt,
    dividend_accumulated_available_quality_cde,
    dividend_available_amt,
    dividend_available_quality_cde,
    last_dividend_credit_amt,
    last_dividend_credit_quality_cde,
    ltcir_dividend_benefit_pool_amt,
    ltcir_dividend_benefit_pool_quality_cde,
    interest_on_dividend_accumulated_to_dt_amt,
    interest_on_dividend_accumulated_to_dt_quality_cde,
    settlement_dividend_amt,
    settlement_dividend_quality_cde,
    dividend_accumulated_tax_amt,
    dividend_accumulated_tax_quality_cde,
    dividend_mo_da,
    bill_mode_cde,
    ebill_preference_cde,
    no_bill_reason_cde,
    bill_frequency_txt,
    premium_tax_state_cde,
    returned_check_cde,
    sdo_mpo_apo_cde,
    paid_in_advance_year_cnt,
    sdo_payment_type_cde,
    policy_fee_ind,
    first_year_ind,
    ipo_ind,
    ltc_activity_cde,
    ltc_premium_adjustment_ind,
    late_payment_offer_end_dt,
    vanishing_premium_effective_dt,
    alir_bill_premium_amt,
    alir_bill_premium_quality_cde,
    al_sup_termination_amt,
    mpo_apo_net_payment_due_amt,
    mpo_apo_net_payment_quality_cde,
    mpo_apo_paid_amt,
    apo_credit_amt,
    annual_premium_amt,
    annual_premium_quality_cde,
    base_rider_monthly_premium_amt,
    base_rider_monthly_premium_quality_cde,
    base_rider_annual_premium_amt,
    bill_premium_amt,
    bill_premium_quality_cde,
    cli_premium_bill_cde,
    cost_due_amt,
    cost_basis_amt,
    cost_basis_quality_cde,
    current_premium_credit_base_amt,
    current_year_payment_amt,
    current_premium_credit_ltc_amt,
    current_premium_credit_ltc_quality_cde,
    next_year_premium_credit_ltc_amt,
    next_year_premium_credit_ltc_quality_cde,
    ewl_deficit_premium_payup_amt,
    ewl_deficit_paid_to_year_month_txt,
    fraction_premium_credit_base_amt,
    fraction_premium_credit_ltc_amt,
    fraction_premium_credit_ltc_quality_cde,
    gross_annual_premium_amt,
    gross_annual_premium_quality_cde,
    gross_premium_fpdup_addns_amt,
    ltcir_return_premium_amt,
    ltcir_return_premium_quality_cde,
    ltcir_reduced_addns_amt,
    ltcir_reduced_addns_quality_cde,
    ltc_extended_benefit_pool_amt,
    ltc_extended_benefit_pool_quality_cde,
    max_annual_payment_year_nr,
    new_business_premium_paid_amt,
    next_year_premium_credit_base_amt,
    target_premium_amt,
    target_premium_quality_cde,
    total_monthly_premium_amt,
    total_monthly_premium_quality_cde,
    unearned_past_due_premium_amt,
    unearned_past_due_premium_quality_cde,
    vanish_bill_amt,

    mpo_apo_paid_amt_quality_cde,
    apo_credit_amt_quality_cde,
    base_rider_annual_premium_quality_cde,
    current_premium_credit_base_quality_cde,
    fraction_premium_credit_base_quality_cde,
    gross_premium_fpdup_addns_quality_cde,
    next_year_premium_credit_base_quality_cde,
    lisr_disability_cost_amt,
    payment_draft_dy_cde,
    ytd_premium_amt,
    invoice_account_id_txt,
    group_account_type_cde,
    group_account_nr_txt,
    last_bill_method_cde,
    pac_account_id_txt,
    pac_account_type_cde,
    bank_nm,
    billing_arrangement_id_txt,
    bill_method_type_cde,
    consolidated_bill_type_cde,
    annualized_premium_amt,
    alir_bill_amt,
    alir_bill_amt_quality_cde,
    bank_id,
    permenant_flat_extra_premium_amt,
    temperory_flat_extra_premium_amt,
    permenant_flat_extra_cost_amt,
    temperory_flat_extra_cost_amt,
    total_annual_premium_amt,
    total_annual_premium_quality_cde,
    source_bill_mode_cde,
    initial_premium_amt,
    pytd_premium_amt,
    premium_refund_amt,
    premium_refund_quality_cde,
    pro_rata_refund_amt,
    pro_rata_refund_quality_cde,
    advance_premium_refund_amt,
    advance_premium_refund_quality_cde,

    paid_to_dt,
    paid_to_dt_txt,
    last_premium_adjustment_dt,
    last_premium_collection_dt,
    last_premium_paid_dt,
    last_transaction_dt,
    premium_accumulated_amt_quality_cde,
    premium_accumulated_amt,
    source_delete_ind,

    last_deposit_dt,
    last_deposit_amt,
    last_deposit_amt_quality_cde,
    administration_charge_amt,
    minus_1_tax_rt,
    bill_to_dt,
    apm_next_bill_dt,
    last_premium_paid_amt,
    begin_dt,
    begin_dtm,
    row_process_dtm,
    audit_id,
    update_audit_id,
    logical_delete_ind,
    check_sum,
    current_row_ind,
    end_dt,
    end_dtm,
    source_system_id,
    restricted_row_ind,
    transaction_dt,
    transaction_dtm
    )
    
select
    src.fact_agreement_detail_natural_key_hash_uuid,
    src.dim_agreement_natural_key_hash_uuid,
    src.pay7_period_premium_amt,
    src.pay7_period_premium_end_dt,
    src.pay7_period_premium_end_dt_quality_cde,
    src.pay7_period_premium_quality_cde,
    src.pay7_period_premium_start_dt,
    src.pay7_period_premium_start_dt_quality_cde,
    src.tcc_amt,
    src.total_monthly_benefit_amt,
    src.ultimate_face_amt,
    src.grace_period_payment_amt,
    src.grace_period_payment_quality_cde,
    src.policy_unit_face_amt,
    src.policy_income_amt,
    src.agreement_dividend_year_nr,
    src.current_dividend_amt,
    src.accumulated_dividend_amt,
    src.accumulated_dividend_quality_cde,
    src.rp_current_dividend_month_txt,
    src.rp_current_dividend_year_txt,
    src.rp_current_dividend_amt,
    src.rp_dividend_amt,
    src.rp_dividend_amt_quality_cde,
    src.ri_dividend_amt_quality_cde,
    src.ri_dividend_amt,
    src.applied_dividend_amt,
    src.applied_dividend_quality_cde,
    src.base_dividend_amt,
    src.base_dividend_quality_cde,
    src.previous_year_dividend_amt,
    src.previous_year_dividend_quality_cde,
    src.dividend_accumulated_available_amt,
    src.dividend_accumulated_available_quality_cde,
    src.dividend_available_amt,
    src.dividend_available_quality_cde,
    src.last_dividend_credit_amt,
    src.last_dividend_credit_quality_cde,
    src.ltcir_dividend_benefit_pool_amt,
    src.ltcir_dividend_benefit_pool_quality_cde,
    src.interest_on_dividend_accumulated_to_dt_amt,
    src.interest_on_dividend_accumulated_to_dt_quality_cde,
    src.settlement_dividend_amt,
    src.settlement_dividend_quality_cde,
    src.dividend_accumulated_tax_amt,
    src.dividend_accumulated_tax_quality_cde,
    src.dividend_mo_da,
    src.bill_mode_cde,
    src.ebill_preference_cde,
    src.no_bill_reason_cde,
    src.bill_frequency_txt,
    src.premium_tax_state_cde,
    src.returned_check_cde,
    src.sdo_mpo_apo_cde,
    src.paid_in_advance_year_cnt,
    src.sdo_payment_type_cde,
    src.policy_fee_ind,
    src.first_year_ind,
    src.ipo_ind,
    src.ltc_activity_cde,
    src.ltc_premium_adjustment_ind,
    src.late_payment_offer_end_dt,
    src.vanishing_premium_effective_dt,
    src.alir_bill_premium_amt,
    src.alir_bill_premium_quality_cde,
    src.al_sup_termination_amt,
    src.mpo_apo_net_payment_due_amt,
    src.mpo_apo_net_payment_quality_cde,
    src.mpo_apo_paid_amt,
    src.apo_credit_amt,
    src.annual_premium_amt,
    src.annual_premium_quality_cde,
    src.base_rider_monthly_premium_amt,
    src.base_rider_monthly_premium_quality_cde,
    src.base_rider_annual_premium_amt,
    src.bill_premium_amt,
    src.bill_premium_quality_cde,
    src.cli_premium_bill_cde,
    src.cost_due_amt,
    src.cost_basis_amt,
    src.cost_basis_quality_cde,
    src.current_premium_credit_base_amt,
    src.current_year_payment_amt,
    src.current_premium_credit_ltc_amt,
    src.current_premium_credit_ltc_quality_cde,
    src.next_year_premium_credit_ltc_amt,
    src.next_year_premium_credit_ltc_quality_cde,
    src.ewl_deficit_premium_payup_amt,
    src.ewl_deficit_paid_to_year_month_txt,
    src.fraction_premium_credit_base_amt,
    src.fraction_premium_credit_ltc_amt,
    src.fraction_premium_credit_ltc_quality_cde,
    src.gross_annual_premium_amt,
    src.gross_annual_premium_quality_cde,
    src.gross_premium_fpdup_addns_amt,
    src.ltcir_return_premium_amt,
    src.ltcir_return_premium_quality_cde,
    src.ltcir_reduced_addns_amt,
    src.ltcir_reduced_addns_quality_cde,
    src.ltc_extended_benefit_pool_amt,
    src.ltc_extended_benefit_pool_quality_cde,
    src.max_annual_payment_year_nr,
    src.new_business_premium_paid_amt,
    src.next_year_premium_credit_base_amt,
    src.target_premium_amt,
    src.target_premium_quality_cde,
    src.total_monthly_premium_amt,
    src.total_monthly_premium_quality_cde,
    src.unearned_past_due_premium_amt,
    src.unearned_past_due_premium_quality_cde,
    src.vanish_bill_amt,

    src.mpo_apo_paid_amt_quality_cde,
    src.apo_credit_amt_quality_cde,
    src.base_rider_annual_premium_quality_cde,
    src.current_premium_credit_base_quality_cde,
    src.fraction_premium_credit_base_quality_cde,
    src.gross_premium_fpdup_addns_quality_cde,
    src.next_year_premium_credit_base_quality_cde,
    src.lisr_disability_cost_amt,
    src.payment_draft_dy_cde,
    src.ytd_premium_amt,
    src.invoice_account_id_txt,
    src.group_account_type_cde,
    src.group_account_nr_txt,
    src.last_bill_method_cde,
    src.pac_account_id_txt,
    src.pac_account_type_cde,
    src.bank_nm,
    src.billing_arrangement_id_txt,
    src.bill_method_type_cde,
    src.consolidated_bill_type_cde,
    src.annualized_premium_amt,
    src.alir_bill_amt,
    src.alir_bill_amt_quality_cde,
    src.bank_id,
    src.permenant_flat_extra_premium_amt,
    src.temperory_flat_extra_premium_amt,
    src.permenant_flat_extra_cost_amt,
    src.temperory_flat_extra_cost_amt,
    src.total_annual_premium_amt,
    src.total_annual_premium_quality_cde,
    src.source_bill_mode_cde,
    src.initial_premium_amt,
    src.pytd_premium_amt,
    src.premium_refund_amt,
    src.premium_refund_quality_cde,
    src.pro_rata_refund_amt,
    src.pro_rata_refund_quality_cde,
    src.advance_premium_refund_amt,
    src.advance_premium_refund_quality_cde,

    src.paid_to_dt,
    src.paid_to_dt_txt,
    src.last_premium_adjustment_dt,
    src.last_premium_collection_dt,
    src.last_premium_paid_dt,
    src.last_transaction_dt,
    src.premium_accumulated_amt_quality_cde,
    src.premium_accumulated_amt,
    src.source_delete_ind,

    src.last_deposit_dt,
    src.last_deposit_amt,
    src.last_deposit_amt_quality_cde,
    src.administration_charge_amt,
    src.minus_1_tax_rt,
    src.bill_to_dt,
    src.apm_next_bill_dt,
    src.last_premium_paid_amt,
    src.begin_dt,
    src.begin_dtm,
    current_timestamp(6) as row_process_dtm,
    src.audit_id,
    src.update_audit_id,
    src.logical_delete_ind,
    src.check_sum,
    src.current_row_ind,
    src.end_dt,
    src.end_dtm,
    src.source_system_id,
    src.restricted_row_ind,
    src.transaction_dt,
    src.transaction_dtm
 
 from 
 edw_staging.aifrps_fact_agreement_detail_initial_load_pre_work src
 left join --edw_tdsunset.fact_agreement_detail tgt
 edw_tdsunset.fact_agreement_detail_initial_aifrps tgt
 on src.dim_agreement_natural_key_hash_uuid=tgt.dim_agreement_natural_key_hash_uuid
 and src.transaction_dt=tgt.transaction_dt
 and src.source_system_id=tgt.source_system_id
 where tgt.dim_agreement_natural_key_hash_uuid is null
;
 
