-- Insert the Historical TD data into Vertica_Staging Table:
INSERT INTO EDW_STAGING.AIFRPS_DIM_AGMT_SPCL_PRGM_VW
SELECT
                    agmt_id,
                    spcl_pgm_typ,
                    spcl_pgm_cntr,
                    agmt_spcl_pgm_fr_dt,
                    agmt_spcl_pgm_to_dt,
                    hldg_key_pfx,
                    hldg_key,
                    hldg_key_sfx,
                    carr_admin_sys_cd,
                    pgm_buss_strt_dt,
                    pgm_buss_end_dt,
                    src_spcl_pgm_typ,
                    pgm_mode_cd,
                    src_pgm_mode_cd,
                    pgm_mode_nr,
                    pgm_dur,
                    pgm_amt,
                    pgm_calc_typ,
                    src_pgm_calc_typ,
                    pgm_amt_typ_cd,
                    src_pgm_amt_typ_cd,
                    detail_amt,
                    detail_pct,
                    pgm_int_rt,
                    next_run_dt,
                    fnd_id,
                    admin_fnd_nr,
                    prod_tier_cd,
                    agmt_data_fr_dt,
                    src_del_ind,
                    curr_ind,
                    src_sys_id,
                    run_id,
                    updt_run_id,
                    trans_dt,
                    first_pymt_dt,
                    first_pymt_yr,
                    src_prior_mrd_amt_typ_cd,
                    prior_mrd_amt_typ_cd,
                    prior_mrd_amt,
                    exclusion_amt
FROM PROD_STND_VW_TERSUN.AGMT_SPCL_PGM_VW_AIFRPS
WHERE SRC_SYS_ID = 72;
