/* back-up*/
CREATE table PROD_STND_VW_TERSUN.AGMT_FND_ALLOC_VW_RPS_AIF-->back-up
as select * from PROD_STND_VW_TERSUN.AGMT_FND_ALLOC_VW_AIF_RPS;

/*validation*/
SELECT AGMT_ID,FND_ID,MAX(TRANS_DT)
FROM PROD_STND_VW_TERSUN.AGMT_FND_ALLOC_VW_AIF_RPS
WHERE SRC_SYS_ID=72
GROUP BY 1,2 ;--414

/*update all the records to N*/

UPDATE PROD_STND_VW_TERSUN.AGMT_FND_ALLOC_VW_AIF_RPS
SET CURR_IND='N'
WHERE SRC_SYS_ID=72;

/* Update the latest trans_dt record curr_ind to 'Y' based on AGMT_ID, FUND_ID and MAX(TRANS_DT)*/

UPDATE PROD_STND_VW_TERSUN.AGMT_FND_ALLOC_VW_AIF_RPS TGT
SET CURR_IND='Y'
FROM 
(
SELECT AGMT_ID,FND_ID,MAX(TRANS_DT) AS MAX_TRANS_DT
FROM PROD_STND_VW_TERSUN.AGMT_FND_ALLOC_VW_AIF_RPS
WHERE SRC_SYS_ID=72
GROUP BY 1,2
)SRC
WHERE 
SRC.AGMT_ID=TGT.AGMT_ID
AND SRC.FND_ID=TGT.FND_ID
AND SRC.MAX_TRANS_DT=TGT.TRANS_DT
AND TGT.SRC_SYS_ID=72; --414

/*validation */

select count(curr_ind)
FROM PROD_STND_VW_TERSUN.AGMT_FND_ALLOC_VW_AIF_RPS TGT
join (
SELECT AGMT_ID,FND_ID,MAX(TRANS_DT) AS MAX_TRANS_DT
FROM PROD_STND_VW_TERSUN.AGMT_FND_ALLOC_VW_AIF_RPS
WHERE SRC_SYS_ID=72
GROUP BY 1,2
)SRC
on 
SRC.AGMT_ID=TGT.AGMT_ID
AND SRC.FND_ID=TGT.FND_ID
AND SRC.MAX_TRANS_DT=TGT.TRANS_DT
AND TGT.SRC_SYS_ID=72
AND TGT.CURR_IND='Y';--414


commit;