
-- insert into new data's
INSERT INTO EDW_STAGING.AIFRPS_AGMT_UNDW_VW_SNAPSHOT
SELECT 
AGMT_ID, AGMT_UNDW_ID, AGMT_DATA_FR_DT, AGMT_UNDW_FR_DT, AGMT_UNDW_TO_DT, HLDG_KEY_PFX, HLDG_KEY, HLDG_KEY_SFX, CARR_ADMIN_SYS_CD, 
PTCP_RLE_CD, SRC_PTCP_RLE_CD, UNDW_SEQ_NBR, SRC_PTCP_RLE_STYP_CD, ISS_AGE, EXCL_RDR_IND, SRC_EXCL_RDR_IND, EXCL_RDR_FRM_NBR, EXCL_CD, 
SRC_EXCL_CD, TBAC_CLS_CD, SRC_TBAC_CLS_CD, RISK_CLS_CD, SRC_RISK_CLS_CD, RISK_CLS_PCT, CURR_IND, SRC_DEL_IND, SRC_SYS_ID, RUN_ID, 
UPDT_RUN_ID, TRANS_DT, UNISEX_IND, EXCL_RDR_2_FRM_NBR, TRUE 
FROM PROD_STND_VW_TERSUN.AGMT_UNDW_VW_AIF_RPS WHERE SRC_SYS_ID = 72;--WHERE RUN_ID = :RUN_ID AND SRC_SYS_ID = 72;
