/*
         FILENAME: aifrps_edw_fact_agreement_detail
         AUTHOR: SYED THOUHEER HUSSAIN
         SUBJECT AREA : AIFRPS
         SOURCE: TERADATA
         TERADATA SOURCE CODE:   72
         DESCRIPTION:  This is to populate fact_agreement_detail incremental load
         Fact table are insert records only.
         Process_ind = 'D' will be handled at dim_agreement table
         Note: All grey out fields are set to NULL, included in check-sum, which is different from OPM
         JIRA:
         CREATE DATE:06/15/2021
         ---------------------------------------------------------------------------------------------------------------
 */


--clean up the pre-work and work table before loading
truncate table edw_staging.aifrps_fact_agreement_detail_pre_work;
truncate table edw_work.aifrps_fact_agreement_detail;

--load data into pre-work table.
--Step 1 for dividend-related fields, only populate these fields when contract.ctrt_curr_div_opt is valid
--some dividend fields are grey-out
insert into edw_staging.aifrps_fact_agreement_detail_pre_work
(fact_agreement_detail_natural_key_hash_uuid,
 dim_agreement_natural_key_hash_uuid,
 pay7_period_premium_amt,
 pay7_period_premium_quality_cde,
 pay7_period_premium_end_dt,
 pay7_period_premium_end_dt_quality_cde,
 pay7_period_premium_start_dt,
 pay7_period_premium_start_dt_quality_cde,
 tcc_amt,
 total_monthly_benefit_amt,
 ultimate_face_amt,
 grace_period_payment_amt,
 grace_period_payment_quality_cde,
 policy_unit_face_amt,
 policy_income_amt,
 current_dividend_amt,
 accumulated_dividend_amt,
 accumulated_dividend_quality_cde,
 rp_current_dividend_month_txt,
 rp_current_dividend_year_txt,
 rp_current_dividend_amt,
 rp_dividend_amt,
 rp_dividend_amt_quality_cde,
 ri_dividend_amt,
 ri_dividend_amt_quality_cde,
 agreement_dividend_year_nr,
 applied_dividend_amt,
 applied_dividend_quality_cde,
 base_dividend_amt,
 base_dividend_quality_cde,
 previous_year_dividend_amt,
 previous_year_dividend_quality_cde,
 dividend_accumulated_available_amt,
 dividend_accumulated_available_quality_cde,
 dividend_available_amt,
 dividend_available_quality_cde,
 last_dividend_credit_amt,
 last_dividend_credit_quality_cde,
 ltcir_dividend_benefit_pool_amt,
 ltcir_dividend_benefit_pool_quality_cde,
 interest_on_dividend_accumulated_to_dt_amt,
 interest_on_dividend_accumulated_to_dt_quality_cde,
 settlement_dividend_amt,
 settlement_dividend_quality_cde,
 dividend_accumulated_tax_amt,
 dividend_accumulated_tax_quality_cde,
 dividend_mo_da,
 bill_mode_cde,
 source_bill_mode_cde,
 ebill_preference_cde,
 no_bill_reason_cde,
 bill_frequency_txt,
 premium_tax_state_cde,
 returned_check_cde,
 sdo_mpo_apo_cde,
 paid_in_advance_year_cnt,
 sdo_payment_type_cde,
 policy_fee_ind,
 first_year_ind,
 ipo_ind,
 ltc_activity_cde,
 ltc_premium_adjustment_ind,
 late_payment_offer_end_dt,
 vanishing_premium_effective_dt,
 alir_bill_premium_amt,
 alir_bill_premium_quality_cde,
 al_sup_termination_amt,
 mpo_apo_net_payment_due_amt,
 mpo_apo_net_payment_quality_cde,
 mpo_apo_paid_amt,
 mpo_apo_paid_amt_quality_cde,
 apo_credit_amt,
 apo_credit_amt_quality_cde,
 annual_premium_amt,
 annual_premium_quality_cde,
 annualized_premium_amt,
 annualized_premium_quality_cde,
 gross_annual_premium_amt,
 gross_annual_premium_quality_cde,
 total_annual_premium_amt,
 total_annual_premium_quality_cde,
 max_annual_payment_year_nr,
 base_rider_monthly_premium_amt,
 base_rider_monthly_premium_quality_cde,
 base_rider_annual_premium_amt,
 base_rider_annual_premium_quality_cde,
 bill_premium_amt,
 bill_premium_quality_cde,
 cli_premium_bill_cde,
 cost_due_amt,
 cost_basis_amt,
 cost_basis_quality_cde,
 current_premium_credit_base_amt,
 current_premium_credit_base_quality_cde,
 current_year_payment_amt,
 next_year_premium_credit_base_amt,
 next_year_premium_credit_base_quality_cde,
 current_premium_credit_ltc_amt,
 current_premium_credit_ltc_quality_cde,
 next_year_premium_credit_ltc_amt,
 next_year_premium_credit_ltc_quality_cde,
 ewl_deficit_premium_payup_amt,
 ewl_deficit_paid_to_year_month_txt,
 fraction_premium_credit_base_amt,
 fraction_premium_credit_base_quality_cde,
 fraction_premium_credit_ltc_amt,
 fraction_premium_credit_ltc_quality_cde,
 gross_premium_fpdup_addns_amt,
 gross_premium_fpdup_addns_quality_cde,
 ltcir_return_premium_amt,
 ltcir_return_premium_quality_cde,
 ltcir_reduced_addns_amt,
 ltcir_reduced_addns_quality_cde,
 ltc_extended_benefit_pool_amt,
 ltc_extended_benefit_pool_quality_cde,
 new_business_premium_paid_amt,
 target_premium_amt,
 target_premium_quality_cde,
 total_monthly_premium_amt,
 total_monthly_premium_quality_cde,
 unearned_past_due_premium_amt,
 unearned_past_due_premium_quality_cde,
 ytd_premium_amt,
 initial_premium_amt,
 pytd_premium_amt,
 last_bill_method_cde,
 premium_refund_amt,
 premium_refund_quality_cde,
 pro_rata_refund_amt,
 pro_rata_refund_quality_cde,
 advance_premium_refund_amt,
 advance_premium_refund_quality_cde,
 vanish_bill_amt,
 lisr_disability_cost_amt,
 payment_draft_dy_cde,
 invoice_account_id_txt,
 group_account_type_cde,
 group_account_nr_txt,
 pac_account_id_txt,
 pac_account_type_cde,
 bank_nm,
 billing_arrangement_id_txt,
 bill_method_type_cde,
 consolidated_bill_type_cde,
 alir_bill_amt,
 alir_bill_amt_quality_cde,
 bank_id,
 permenant_flat_extra_premium_amt,
 temperory_flat_extra_premium_amt,
 permenant_flat_extra_cost_amt,
 temperory_flat_extra_cost_amt,
 paid_to_dt,
 paid_to_dt_txt,
 last_premium_adjustment_dt,
 last_premium_collection_dt,
 last_premium_paid_dt,
 last_transaction_dt,
 premium_accumulated_amt,
 premium_accumulated_amt_quality_cde,
 last_deposit_dt,
 last_deposit_amt,
 last_deposit_amt_quality_cde,
 administration_charge_amt,
 minus_1_tax_rt,
 bill_to_dt,
 apm_next_bill_dt,
 last_premium_paid_amt,
 begin_dt,
 begin_dtm,
 row_process_dtm,
 check_sum,
 end_dt,
 end_dtm,
 restricted_row_ind,
 current_row_ind,
 logical_delete_ind,
 source_system_id,
 audit_id,
 update_audit_id,
 source_delete_ind,
 process_ind,
 transaction_dt,
 transaction_dtm,
 net_cash_val_amt,
 net_cash_val_as_of_dt,
 death_benefit_amt,
 death_benefit_as_of_dt,
 wp_premium_amt,
 wp_premium_issue_age_nr,
 wp_premium_issue_dt,
 wp_premium_duration_nr,
 payout_amt,
 premium_tax_dt,
 bill_day_nr)
select stg.fact_agreement_detail_natural_key_hash_uuid,
       stg.dim_agreement_natural_key_hash_uuid,
       stg.pay7_period_premium_amt,
       stg.pay7_period_premium_quality_cde,
       stg.pay7_period_premium_end_dt,
       stg.pay7_period_premium_end_dt_quality_cde,
       stg.pay7_period_premium_start_dt,
       stg.pay7_period_premium_start_dt_quality_cde,
       stg.tcc_amt,
       stg.total_monthly_benefit_amt,
       stg.ultimate_face_amt,
       stg.grace_period_payment_amt,
       stg.grace_period_payment_quality_cde,
       stg.policy_unit_face_amt,
       stg.policy_income_amt,
       stg.current_dividend_amt,
       stg.accumulated_dividend_amt,
       stg.accumulated_dividend_quality_cde,
       stg.rp_current_dividend_month_txt,
       stg.rp_current_dividend_year_txt,
       stg.rp_current_dividend_amt,
       stg.rp_dividend_amt,
       stg.rp_dividend_amt_quality_cde,
       stg.ri_dividend_amt,
       stg.ri_dividend_amt_quality_cde,
       stg.agreement_dividend_year_nr,
       stg.applied_dividend_amt,
       stg.applied_dividend_quality_cde,
       stg.base_dividend_amt,
       stg.base_dividend_quality_cde,
       stg.previous_year_dividend_amt,
       stg.previous_year_dividend_quality_cde,
       stg.dividend_accumulated_available_amt,
       stg.dividend_accumulated_available_quality_cde,
       stg.dividend_available_amt,
       stg.dividend_available_quality_cde,
       stg.last_dividend_credit_amt,
       stg.last_dividend_credit_quality_cde,
       stg.ltcir_dividend_benefit_pool_amt,
       stg.ltcir_dividend_benefit_pool_quality_cde,
       stg.interest_on_dividend_accumulated_to_dt_amt,
       stg.interest_on_dividend_accumulated_to_dt_quality_cde,
       stg.settlement_dividend_amt,
       stg.settlement_dividend_quality_cde,
       stg.dividend_accumulated_tax_amt,
       stg.dividend_accumulated_tax_quality_cde,
       stg.dividend_mo_da,
       stg.bill_mode_cde,
       stg.source_bill_mode_cde,
       stg.ebill_preference_cde,
       stg.no_bill_reason_cde,
       stg.bill_frequency_txt,
       stg.premium_tax_state_cde,
       stg.returned_check_cde,
       stg.sdo_mpo_apo_cde,
       stg.paid_in_advance_year_cnt,
       stg.sdo_payment_type_cde,
       stg.policy_fee_ind,
       stg.first_year_ind,
       stg.ipo_ind,
       stg.ltc_activity_cde,
       stg.ltc_premium_adjustment_ind,
       stg.late_payment_offer_end_dt,
       stg.vanishing_premium_effective_dt,
       stg.alir_bill_premium_amt,
       stg.alir_bill_premium_quality_cde,
       stg.al_sup_termination_amt,
       stg.mpo_apo_net_payment_due_amt,
       stg.mpo_apo_net_payment_quality_cde,
       stg.mpo_apo_paid_amt,
       stg.mpo_apo_paid_amt_quality_cde,
       stg.apo_credit_amt,
       stg.apo_credit_amt_quality_cde,
       stg.annual_premium_amt,
       stg.annual_premium_quality_cde,
       stg.annualized_premium_amt,
       stg.annualized_premium_quality_cde,
       stg.gross_annual_premium_amt,
       stg.gross_annual_premium_quality_cde,
       stg.total_annual_premium_amt,
       stg.total_annual_premium_quality_cde,
       stg.max_annual_payment_year_nr,
       stg.base_rider_monthly_premium_amt,
       stg.base_rider_monthly_premium_quality_cde,
       stg.base_rider_annual_premium_amt,
       stg.base_rider_annual_premium_quality_cde,
       stg.bill_premium_amt,
       stg.bill_premium_quality_cde,
       stg.cli_premium_bill_cde,
       stg.cost_due_amt,
       stg.cost_basis_amt,
       stg.cost_basis_quality_cde,
       stg.current_premium_credit_base_amt,
       stg.current_premium_credit_base_quality_cde,
       stg.current_year_payment_amt,
       stg.next_year_premium_credit_base_amt,
       stg.next_year_premium_credit_base_quality_cde,
       stg.current_premium_credit_ltc_amt,
       stg.current_premium_credit_ltc_quality_cde,
       stg.next_year_premium_credit_ltc_amt,
       stg.next_year_premium_credit_ltc_quality_cde,
       stg.ewl_deficit_premium_payup_amt,
       stg.ewl_deficit_paid_to_year_month_txt,
       stg.fraction_premium_credit_base_amt,
       stg.fraction_premium_credit_base_quality_cde,
       stg.fraction_premium_credit_ltc_amt,
       stg.fraction_premium_credit_ltc_quality_cde,
       stg.gross_premium_fpdup_addns_amt,
       stg.gross_premium_fpdup_addns_quality_cde,
       stg.ltcir_return_premium_amt,
       stg.ltcir_return_premium_quality_cde,
       stg.ltcir_reduced_addns_amt,
       stg.ltcir_reduced_addns_quality_cde,
       stg.ltc_extended_benefit_pool_amt,
       stg.ltc_extended_benefit_pool_quality_cde,
       stg.new_business_premium_paid_amt,
       stg.target_premium_amt,
       stg.target_premium_quality_cde,
       stg.total_monthly_premium_amt,
       stg.total_monthly_premium_quality_cde,
       stg.unearned_past_due_premium_amt,
       stg.unearned_past_due_premium_quality_cde,
       stg.ytd_premium_amt,
       stg.initial_premium_amt,
       stg.pytd_premium_amt,
       stg.last_bill_method_cde,
       stg.premium_refund_amt,
       stg.premium_refund_quality_cde,
       stg.pro_rata_refund_amt,
       stg.pro_rata_refund_quality_cde,
       stg.advance_premium_refund_amt,
       stg.advance_premium_refund_quality_cde,
       stg.vanish_bill_amt,
       stg.lisr_disability_cost_amt,
       stg.payment_draft_dy_cde,
       stg.invoice_account_id_txt,
       stg.group_account_type_cde,
       stg.group_account_nr_txt,
       stg.pac_account_id_txt,
       stg.pac_account_type_cde,
       stg.bank_nm,
       stg.billing_arrangement_id_txt,
       stg.bill_method_type_cde,
       stg.consolidated_bill_type_cde,
       stg.alir_bill_amt,
       stg.alir_bill_amt_quality_cde,
       stg.bank_id,
       stg.permenant_flat_extra_premium_amt,
       stg.temperory_flat_extra_premium_amt,
       stg.permenant_flat_extra_cost_amt,
       stg.temperory_flat_extra_cost_amt,
       stg.paid_to_dt,
       stg.paid_to_dt_txt,
       stg.last_premium_adjustment_dt,
       stg.last_premium_collection_dt,
       stg.last_premium_paid_dt,
       stg.last_transaction_dt,
       stg.premium_accumulated_amt,
       stg.premium_accumulated_amt_quality_cde,
       stg.last_deposit_dt,
       stg.last_deposit_amt,
       stg.last_deposit_amt_quality_cde,
       stg.administration_charge_amt,
       stg.minus_1_tax_rt,
       stg.bill_to_dt,
       stg.apm_next_bill_dt,
       stg.last_premium_paid_amt,
       stg.begin_dt,
       stg.begin_dtm,
       stg.row_process_dtm,

       UUID_GEN(
               stg.source_delete_ind,
               clean_string(stg.bill_mode_cde),
               stg.source_bill_mode_cde,
               stg.bill_frequency_txt,
               clean_string(stg.premium_tax_state_cde),
               stg.total_annual_premium_amt,
               stg.bill_premium_amt,
               stg.initial_premium_amt,
               stg.invoice_account_id_txt,
               clean_string(stg.bill_method_type_cde),
               stg.premium_accumulated_amt,
               stg.apm_next_bill_dt)::UUID as check_sum,
       stg.end_dt,
       stg.end_dtm,
       stg.restricted_row_ind,
       stg.current_row_ind,
       stg.logical_delete_ind,
       stg.source_system_id,
       stg.audit_id,
       stg.update_audit_id,
       stg.source_delete_ind,
       stg.process_ind,
       stg.transaction_dt,
       stg.transaction_dtm,
       stg.net_cash_val_amt,
       stg.net_cash_val_as_of_dt,
       stg.death_benefit_amt,
       stg.death_benefit_as_of_dt,
       stg.wp_premium_amt,
       stg.wp_premium_issue_age_nr,
       stg.wp_premium_issue_dt,
       stg.wp_premium_duration_nr,
       stg.payout_amt,
       stg.premium_tax_dt,
       stg.bill_day_nr
from( 
select 
uuid_gen(
                        clean_string(agreement_sdt.trnslt_fld_val),
                        'Ipa',
                        clean_string(PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'PFX')),
                        clean_string(PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'KEY')),
                        clean_string(PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'SFX')),
                        contract.begin_dt
                    )::uuid                                                             as fact_agreement_detail_natural_key_hash_uuid,
                uuid_gen(
                        clean_string(agreement_sdt.trnslt_fld_val),
                        'Ipa',
                        clean_string(PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'PFX')),
                        clean_string(PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'KEY')),
                        clean_string(PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'SFX'))
                    )::uuid                                                             as dim_agreement_natural_key_hash_uuid,
                NULL                                                                    as pay7_period_premium_amt,
                NULL                                                                    as pay7_period_premium_quality_cde,
                NULL                                                          			as pay7_period_premium_end_dt,
                NULL                                                                    as pay7_period_premium_end_dt_quality_cde,
                NULL                                                                    as pay7_period_premium_start_dt,
                NULL                                                                    as pay7_period_premium_start_dt_quality_cde,
                NULL                                                                    as tcc_amt,
                NULL                                                                    as total_monthly_benefit_amt,
                NULL                                                                    as ultimate_face_amt,
                NULL                                                                    as grace_period_payment_amt,
                NULL                                                                    as grace_period_payment_quality_cde,
                NULL                                                                    as policy_unit_face_amt,
                NULL                                                                    as policy_income_amt,
                NULL                                                                    as current_dividend_amt,
                NULL                                                                    as accumulated_dividend_amt,
                NULL                                                                    as accumulated_dividend_quality_cde,
                NULL                                                                    as rp_current_dividend_month_txt,
                NULL                                                                    as rp_current_dividend_year_txt,
                NULL                                                                    as rp_current_dividend_amt,
                NULL                                                                    as rp_dividend_amt,
                NULL                                                                    as rp_dividend_amt_quality_cde,
                NULL                                                                    as ri_dividend_amt,
                NULL                                                                    as ri_dividend_amt_quality_cde,
                NULL                                                                    as agreement_dividend_year_nr,
                NULL                                                                    as applied_dividend_amt,
                NULL                                                                    as applied_dividend_quality_cde,
                NULL                                                                    as base_dividend_amt,
                NULL                                                                    as base_dividend_quality_cde,
                NULL                                                                    as previous_year_dividend_amt,
                NULL                                                                    as previous_year_dividend_quality_cde,
                NULL                                                                    as dividend_accumulated_available_amt,
                NULL                                                                    as dividend_accumulated_available_quality_cde,
                NULL                                                                    as dividend_available_amt,
                NULL                                                                    as dividend_available_quality_cde,
                NULL                                                                    as last_dividend_credit_amt,
                NULL                                                                    as last_dividend_credit_quality_cde,
                NULL                                                                    as ltcir_dividend_benefit_pool_amt,
                NULL                                                                    as ltcir_dividend_benefit_pool_quality_cde,
                NULL                                                                    as interest_on_dividend_accumulated_to_dt_amt,
                NULL                                                                    as interest_on_dividend_accumulated_to_dt_quality_cde,
                NULL                                                                    as settlement_dividend_amt,
                NULL                                                                    as settlement_dividend_quality_cde,
                NULL                                                                    as dividend_accumulated_tax_amt,
                NULL                                                                    as dividend_accumulated_tax_quality_cde,
                NULL                                                                    as dividend_mo_da,
                case
                when clean_string(bill_mode_cde_sdt.trnslt_fld_val) is null
                then 'Unk'
                else clean_string(bill_mode_cde_sdt.trnslt_fld_val)
                end 																	as bill_mode_cde,
                contract.aifcow_bill_frequency                                          as source_bill_mode_cde,
                NULL                                                                    as ebill_preference_cde,
                NULL                                                                    as no_bill_reason_cde,
                case
				when clean_string(bill_frequency_txt_sdt.trnslt_fld_val) is null
				then 'Unk'
				else clean_string(bill_frequency_txt_sdt.trnslt_fld_val)
				end 																	as bill_frequency_txt,
                clean_string(contract.premium_tax_state_lifecomm)                       as premium_tax_state_cde,
                NULL                                                                    as returned_check_cde,
                NULL                                                                    as sdo_mpo_apo_cde,
                NULL                                                                    as paid_in_advance_year_cnt,
                NULL                                                                    as sdo_payment_type_cde,
                NULL                                                                    as policy_fee_ind,
                NULL                                                                    as first_year_ind,
                NULL                                                                    as ipo_ind,
                NULL                                                                    as ltc_activity_cde,
                NULL                                                                    as ltc_premium_adjustment_ind,
                NULL                                                                    as late_payment_offer_end_dt,
                NULL                                                                    as vanishing_premium_effective_dt,
                NULL                                                                    as alir_bill_premium_amt,
                NULL                                                                    as alir_bill_premium_quality_cde,
                null                                                                    as al_sup_termination_amt,
                NULL                                                                    as mpo_apo_net_payment_due_amt,
                NULL                                                                    as mpo_apo_net_payment_quality_cde,
                NULL                                                                    as mpo_apo_paid_amt,
                NULL                                                                    as mpo_apo_paid_amt_quality_cde,
                NULL                                                                    as apo_credit_amt,
                NULL                                                                    as apo_credit_amt_quality_cde,
                NULL                                                                    as annual_premium_amt,
                NULL                                                                    as annual_premium_quality_cde,
                NULL                                                                    as annualized_premium_amt,
                NULL                                                                    as annualized_premium_quality_cde,
                NULL                                                                    as gross_annual_premium_amt,
                NULL                                                                    as gross_annual_premium_quality_cde,
                contract.aifcow_total_regular_premium                                   as total_annual_premium_amt,
                NULL                                                                    as total_annual_premium_quality_cde,
                null                                                                    as max_annual_payment_year_nr,
                NULL                                                                    as base_rider_monthly_premium_amt,
                NULL                                                                    as base_rider_monthly_premium_quality_cde,
                NULL                                                                    as base_rider_annual_premium_amt,
                NULL                                                                    as base_rider_annual_premium_quality_cde,
                contract.aifcow_modal_premium                                           as bill_premium_amt,
                NULL                                                                    as bill_premium_quality_cde,
                null                                                                    as cli_premium_bill_cde,
                NULL                                                                    as cost_due_amt,
                null                                                                    as cost_basis_amt,
                null                                                                    as cost_basis_quality_cde,
                null                                                                    as current_premium_credit_base_amt,
                null                                                                    as current_premium_credit_base_quality_cde,
                null                                                                    as current_year_payment_amt,
                null                                                                    as next_year_premium_credit_base_amt,
                null                                                                    as next_year_premium_credit_base_quality_cde,
                null                                                                    as current_premium_credit_ltc_amt,
                null                                                                    as current_premium_credit_ltc_quality_cde,
                null                                                                    as next_year_premium_credit_ltc_amt,
                null                                                                    as next_year_premium_credit_ltc_quality_cde,
                null                                                                    as ewl_deficit_premium_payup_amt,
                null                                                                    as ewl_deficit_paid_to_year_month_txt,
                null                                                                    as fraction_premium_credit_base_amt,
                null                                                                    as fraction_premium_credit_base_quality_cde,
                null                                                                    as fraction_premium_credit_ltc_amt,
                null                                                                    as fraction_premium_credit_ltc_quality_cde,
                null                                                                    as gross_premium_fpdup_addns_amt,
                null                                                                    as gross_premium_fpdup_addns_quality_cde,
                null                                                                    as ltcir_return_premium_amt,
                null                                                                    as ltcir_return_premium_quality_cde,
                null                                                                    as ltcir_reduced_addns_amt,
                null                                                                    as ltcir_reduced_addns_quality_cde,
                null                                                                    as ltc_extended_benefit_pool_amt,
                null                                                                    as ltc_extended_benefit_pool_quality_cde,
                null                                                                    as new_business_premium_paid_amt,
                NULL                                                                    as target_premium_amt,
                null                                                                    as target_premium_quality_cde,
                NULL                                                                    as total_monthly_premium_amt, --new
                NULL                                                                    as total_monthly_premium_quality_cde, --new
                null                                                                    as unearned_past_due_premium_amt,
                NULL                                                                    as unearned_past_due_premium_quality_cde,
                NULL                                                                    as ytd_premium_amt,
                contract.aifcow_first_payment_amt                                       as initial_premium_amt,
                NULL                                                                    as pytd_premium_amt,
                NULL                                                                    as last_bill_method_cde,
                NULL                                                                    as premium_refund_amt,
                NULL                                                                    as premium_refund_quality_cde,
                NULL                                                                    as pro_rata_refund_amt,
                NULL                                                                    as pro_rata_refund_quality_cde,
                null                                                                    as advance_premium_refund_amt,
                null                                                                    as advance_premium_refund_quality_cde,

                null                                                                    as vanish_bill_amt,
                null                                                                    as lisr_disability_cost_amt,
                null                                                                    as payment_draft_dy_cde,
                contract.aifcow_group_number                                            as invoice_account_id_txt,--ok
                null                                                                    as group_account_type_cde,--need discuss for lvrgvl as it is
                null                                                                    as group_account_nr_txt,
                null                                                                    as pac_account_id_txt,
                null                                                                    as pac_account_type_cde,
                null                                                                    as bank_nm,
                null                                                                    as billing_arrangement_id_txt,
                case
				when clean_string(bill_method_type_cde_sdt.trnslt_fld_val) is null
				then 'Unk'
				else clean_string(bill_method_type_cde_sdt.trnslt_fld_val)
				end 																    as bill_method_type_cde,
                null                                                                    as consolidated_bill_type_cde,
                null                                                                    as alir_bill_amt,
                null                                                                    as alir_bill_amt_quality_cde,
            
                NULL                                                                    as bank_id,
             
                NULL                                                                    as permenant_flat_extra_premium_amt,
             
                NULL                                                                    as temperory_flat_extra_premium_amt,
             
                NULL                                                                    as permenant_flat_extra_cost_amt,
             
                NULL                                                                    as temperory_flat_extra_cost_amt,
                null                                                                    as paid_to_dt,
                null                                                                    as paid_to_dt_txt,
                null                                                                    as last_premium_adjustment_dt,
                null                                                                    as last_premium_collection_dt,
                null                                                                    as last_premium_paid_dt,
                null                                                                    as last_transaction_dt,
                /*case
                    when value.valu_prem_accum_sig = '7' and value.valu_prem_accum > 0 then value.valu_prem_accum * (-1)
                    else value.valu_prem_accum
                    end*/
                          contract.aifcow_total_premium_value                           as premium_accumulated_amt,
                null                                                                    as premium_accumulated_amt_quality_cde,

             
                NULL                                                                    as last_deposit_dt,
                NULL                                                                    as last_deposit_amt,
             
                NULL                                                                    as last_deposit_amt_quality_cde,
             
                NULL                                                                    as administration_charge_amt,
             
                NULL                                                                    as minus_1_tax_rt,
                null                                                                    as bill_to_dt,
                CASE WHEN 
TO_CHAR(CONTRACT.aifcow_next_pmt_due_yyyy)||LPAD(TO_CHAR(CONTRACT.aifcow_next_pmt_due_mm),2,'0')||LPAD(TO_CHAR(CONTRACT.aifcow_next_pmt_due_dd),2,'0')=99999999
OR TO_CHAR(CONTRACT.aifcow_next_pmt_due_yyyy)||LPAD(TO_CHAR(CONTRACT.aifcow_next_pmt_due_mm),2,'0')||LPAD(TO_CHAR(CONTRACT.aifcow_next_pmt_due_dd),2,'0')>52000000
THEN TO_DATE('9999-12-31','YYYY-MM-DD')
ELSE
public.isdate((TO_CHAR(CONTRACT.aifcow_next_pmt_due_yyyy))||LPAD(TO_CHAR(CONTRACT.aifcow_next_pmt_due_mm),2,'0')||LPAD(TO_CHAR(CONTRACT.aifcow_next_pmt_due_dd),2,'0'))
END 																					as apm_next_bill_dt,
                NULL                                                                    as last_premium_paid_amt,
                contract.begin_dt,
                contract.begin_dt                                                       as begin_dtm,
                current_timestamp(6)                                                    as row_process_dtm,
                '9999-12-31'::date                                                      as end_dt,
                '9999-12-31'::timestamp                                                 as end_dtm,
                false                                                                   as restricted_row_ind,
                true                                                                    as current_row_ind,
                false                                                                   as logical_delete_ind,
                72                                                                      as source_system_id,
                :audit_id                                                               as audit_id,
                :audit_id                                                               as update_audit_id,
                false                                                                   as source_delete_ind,
                contract.processed_ind                                                  as process_ind,
                contract.begin_dt                                                       as transaction_dt,
                contract.begin_dt                                                       as transaction_dtm,
                NULL                                                                    as net_cash_val_amt,
                NULL                                                                    as net_cash_val_as_of_dt,
                NULL                                                                    as death_benefit_amt,
                NULL                                                                    as death_benefit_as_of_dt,
                NULL                                                                    as wp_premium_amt,
                NULL                                                                    as wp_premium_issue_age_nr,
                NULL                                                                    as wp_premium_issue_dt,
                NULL                                                                    as wp_premium_duration_nr,
                NULL                                                                    as payout_amt,
                NULL                                                                    as premium_tax_dt,
                NULL                                                                    as bill_day_nr,
                    PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'PFX')     as AGREEMENT_NR_PFX,
                    PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'KEY')     as AGREEMENT_NR,
                    PUBLIC.UDF_AIF_HLDG_KEY_FORMAT(contract.aifcow_policy_id,'SFX')     as AGREEMENT_NR_SFX
from (select delta.*,
                      coalesce(to_date(cnt.cycle_date::varchar, 'yyyymmdd'), current_date) as begin_dt

               from edw_staging.aif_rps_edw_ctrt_full_dedup delta,--aif_rps_edw_ctrt_delta

                    edw_staging.aif_rps_edw_ctrt_delta_count cnt
              ) contract

                  left join (select distinct trnslt_fld_val, src_cde, src_fld_nm, trnslt_fld_nm, src_fld_val
                             from edw_ref.src_data_trnslt
                             where upper(src_cde) = 'ANN'
                               and upper(src_fld_nm) = 'ADMN_SYS_CDE'
                               and upper(trnslt_fld_nm) = 'ADMIN OR SOURCE SYSTEM CODE'
         ) agreement_sdt
                            on upper(agreement_sdt.src_fld_val) =
                               upper(udf_replaceemptystr(contract.aifcow_source_system_id, 'SPACE'))
                                                       
--bill_mode_cde

                  left join (select distinct trnslt_fld_val, src_cde, src_fld_nm, trnslt_fld_nm, src_fld_val
                             from edw_ref.src_data_trnslt
                             where
                              upper(src_fld_nm) = 'BILL_FREQ'
                               and upper(trnslt_fld_nm) = 'BILLING FREQUENCY'
         ) bill_mode_cde_sdt
                            on upper(bill_mode_cde_sdt.src_fld_val) =
                               upper(udf_replaceemptystr(to_char(contract.aifcow_bill_frequency), 'SPACE'))
                             and upper(trim(bill_mode_cde_sdt.src_cde)) =upper(trim(agreement_sdt.trnslt_fld_val))
                                                  
--bill_frequency_txt

                  left join (select distinct trnslt_fld_val, src_cde, src_fld_nm, trnslt_fld_nm, src_fld_val
                             from edw_ref.src_data_trnslt
                             where 
                                upper(src_fld_nm) = 'BILL_FREQ'
                               and upper(trnslt_fld_nm) = 'BILLING FREQUENCY'
         ) bill_frequency_txt_sdt
                            on upper(bill_frequency_txt_sdt.src_fld_val) =
                               upper(udf_replaceemptystr(to_char(contract.aifcow_bill_frequency), 'SPACE'))                                            
                              and upper(trim(bill_frequency_txt_sdt.src_cde)) =upper(trim(agreement_sdt.trnslt_fld_val) )                 

--bill_method_type_cde

                  left join (select distinct trnslt_fld_val, src_cde, src_fld_nm, trnslt_fld_nm, src_fld_val
                             from edw_ref.src_data_trnslt
                             where 
                                upper(src_fld_nm) = 'BILL_OPT'
                               and upper(trnslt_fld_nm) = 'BILLING METHOD') bill_method_type_cde_sdt
                            on upper(bill_method_type_cde_sdt.src_fld_val) =
                               upper(udf_replaceemptystr(contract.aifcow_bill_option, 'SPACE'))
                             and upper(trim(bill_method_type_cde_sdt.src_cde)) =upper(trim(agreement_sdt.trnslt_fld_val))                
                               
                              
                  ) stg;



-- Step 2 insert brand new records to target
--use dim_agreement_natural_key_hash_uuid as key in join condition
insert into edw_work.aifrps_fact_agreement_detail
(fact_agreement_detail_natural_key_hash_uuid,
 dim_agreement_natural_key_hash_uuid,
 pay7_period_premium_amt,
 pay7_period_premium_quality_cde,
 pay7_period_premium_end_dt,
 pay7_period_premium_end_dt_quality_cde,
 pay7_period_premium_start_dt,
 pay7_period_premium_start_dt_quality_cde,
 tcc_amt,
 total_monthly_benefit_amt,
 ultimate_face_amt,
 grace_period_payment_amt,
 grace_period_payment_quality_cde,
 policy_unit_face_amt,
 policy_income_amt,
 current_dividend_amt,
 accumulated_dividend_amt,
 accumulated_dividend_quality_cde,
 rp_current_dividend_month_txt,
 rp_current_dividend_year_txt,
 rp_current_dividend_amt,
 rp_dividend_amt,
 rp_dividend_amt_quality_cde,
 ri_dividend_amt,
 ri_dividend_amt_quality_cde,
 agreement_dividend_year_nr,
 applied_dividend_amt,
 applied_dividend_quality_cde,
 base_dividend_amt,
 base_dividend_quality_cde,
 previous_year_dividend_amt,
 previous_year_dividend_quality_cde,
 dividend_accumulated_available_amt,
 dividend_accumulated_available_quality_cde,
 dividend_available_amt,
 dividend_available_quality_cde,
 last_dividend_credit_amt,
 last_dividend_credit_quality_cde,
 ltcir_dividend_benefit_pool_amt,
 ltcir_dividend_benefit_pool_quality_cde,
 interest_on_dividend_accumulated_to_dt_amt,
 interest_on_dividend_accumulated_to_dt_quality_cde,
 settlement_dividend_amt,
 settlement_dividend_quality_cde,
 dividend_accumulated_tax_amt,
 dividend_accumulated_tax_quality_cde,
 dividend_mo_da,
 bill_mode_cde,
 source_bill_mode_cde,
 ebill_preference_cde,
 no_bill_reason_cde,
 bill_frequency_txt,
 premium_tax_state_cde,
 returned_check_cde,
 sdo_mpo_apo_cde,
 paid_in_advance_year_cnt,
 sdo_payment_type_cde,
 policy_fee_ind,
 first_year_ind,
 ipo_ind,
 ltc_activity_cde,
 ltc_premium_adjustment_ind,
 late_payment_offer_end_dt,
 vanishing_premium_effective_dt,
 alir_bill_premium_amt,
 alir_bill_premium_quality_cde,
 al_sup_termination_amt,
 mpo_apo_net_payment_due_amt,
 mpo_apo_net_payment_quality_cde,
 mpo_apo_paid_amt,
 mpo_apo_paid_amt_quality_cde,
 apo_credit_amt,
 apo_credit_amt_quality_cde,
 annual_premium_amt,
 annual_premium_quality_cde,
 annualized_premium_amt,
 annualized_premium_quality_cde,
 gross_annual_premium_amt,
 gross_annual_premium_quality_cde,
 total_annual_premium_amt,
 total_annual_premium_quality_cde,
 max_annual_payment_year_nr,
 base_rider_monthly_premium_amt,
 base_rider_monthly_premium_quality_cde,
 base_rider_annual_premium_amt,
 base_rider_annual_premium_quality_cde,
 bill_premium_amt,
 bill_premium_quality_cde,
 cli_premium_bill_cde,
 cost_due_amt,
 cost_basis_amt,
 cost_basis_quality_cde,
 current_premium_credit_base_amt,
 current_premium_credit_base_quality_cde,
 current_year_payment_amt,
 next_year_premium_credit_base_amt,
 next_year_premium_credit_base_quality_cde,
 current_premium_credit_ltc_amt,
 current_premium_credit_ltc_quality_cde,
 next_year_premium_credit_ltc_amt,
 next_year_premium_credit_ltc_quality_cde,
 ewl_deficit_premium_payup_amt,
 ewl_deficit_paid_to_year_month_txt,
 fraction_premium_credit_base_amt,
 fraction_premium_credit_base_quality_cde,
 fraction_premium_credit_ltc_amt,
 fraction_premium_credit_ltc_quality_cde,
 gross_premium_fpdup_addns_amt,
 gross_premium_fpdup_addns_quality_cde,
 ltcir_return_premium_amt,
 ltcir_return_premium_quality_cde,
 ltcir_reduced_addns_amt,
 ltcir_reduced_addns_quality_cde,
 ltc_extended_benefit_pool_amt,
 ltc_extended_benefit_pool_quality_cde,
 new_business_premium_paid_amt,
 target_premium_amt,
 target_premium_quality_cde,
 total_monthly_premium_amt, --new
 total_monthly_premium_quality_cde, --new
 unearned_past_due_premium_amt,
 unearned_past_due_premium_quality_cde,
 ytd_premium_amt,
 initial_premium_amt,
 pytd_premium_amt,
 last_bill_method_cde,
 premium_refund_amt,
 premium_refund_quality_cde,
 pro_rata_refund_amt,
 pro_rata_refund_quality_cde,
 advance_premium_refund_amt,
 advance_premium_refund_quality_cde,
 vanish_bill_amt,
 lisr_disability_cost_amt,
 payment_draft_dy_cde,
 invoice_account_id_txt,
 group_account_type_cde,
 group_account_nr_txt,
 pac_account_id_txt,
 pac_account_type_cde,
 bank_nm,
 billing_arrangement_id_txt,
 bill_method_type_cde,
 consolidated_bill_type_cde,
 alir_bill_amt,
 alir_bill_amt_quality_cde,
 bank_id,
 permenant_flat_extra_premium_amt,
 temperory_flat_extra_premium_amt,
 permenant_flat_extra_cost_amt,
 temperory_flat_extra_cost_amt,
 paid_to_dt,
 paid_to_dt_txt,
 last_premium_adjustment_dt,
 last_premium_collection_dt,
 last_premium_paid_dt,
 last_transaction_dt,
 premium_accumulated_amt,
 premium_accumulated_amt_quality_cde,
 last_deposit_dt,
 last_deposit_amt,
 last_deposit_amt_quality_cde,
 administration_charge_amt,
 minus_1_tax_rt,
 bill_to_dt,
 apm_next_bill_dt,
 last_premium_paid_amt,
 begin_dt,
 begin_dtm,
 row_process_dtm,
 check_sum,
 end_dt,
 end_dtm,
 restricted_row_ind,
 current_row_ind,
 logical_delete_ind,
 source_system_id,
 audit_id,
 update_audit_id,
 source_delete_ind,
 transaction_dt,
 transaction_dtm,
 net_cash_val_amt,
 net_cash_val_as_of_dt,
 death_benefit_amt,
 death_benefit_as_of_dt,
 wp_premium_amt,
 wp_premium_issue_age_nr,
 wp_premium_issue_dt,
 wp_premium_duration_nr,
 payout_amt,
 premium_tax_dt,
 bill_day_nr)
select fact_agreement_detail_natural_key_hash_uuid,
       dim_agreement_natural_key_hash_uuid,
       pay7_period_premium_amt,
       pay7_period_premium_quality_cde,
       pay7_period_premium_end_dt,
       pay7_period_premium_end_dt_quality_cde,
       pay7_period_premium_start_dt,
       pay7_period_premium_start_dt_quality_cde,
       tcc_amt,
       total_monthly_benefit_amt,
       ultimate_face_amt,
       grace_period_payment_amt,
       grace_period_payment_quality_cde,
       policy_unit_face_amt,
       policy_income_amt,
       current_dividend_amt,
       accumulated_dividend_amt,
       accumulated_dividend_quality_cde,
       rp_current_dividend_month_txt,
       rp_current_dividend_year_txt,
       rp_current_dividend_amt,
       rp_dividend_amt,
       rp_dividend_amt_quality_cde,
       ri_dividend_amt,
       ri_dividend_amt_quality_cde,
       agreement_dividend_year_nr,
       applied_dividend_amt,
       applied_dividend_quality_cde,
       base_dividend_amt,
       base_dividend_quality_cde,
       previous_year_dividend_amt,
       previous_year_dividend_quality_cde,
       dividend_accumulated_available_amt,
       dividend_accumulated_available_quality_cde,
       dividend_available_amt,
       dividend_available_quality_cde,
       last_dividend_credit_amt,
       last_dividend_credit_quality_cde,
       ltcir_dividend_benefit_pool_amt,
       ltcir_dividend_benefit_pool_quality_cde,
       interest_on_dividend_accumulated_to_dt_amt,
       interest_on_dividend_accumulated_to_dt_quality_cde,
       settlement_dividend_amt,
       settlement_dividend_quality_cde,
       dividend_accumulated_tax_amt,
       dividend_accumulated_tax_quality_cde,
       dividend_mo_da,
       bill_mode_cde,
       source_bill_mode_cde,
       ebill_preference_cde,
       no_bill_reason_cde,
       bill_frequency_txt,
       premium_tax_state_cde,
       returned_check_cde,
       sdo_mpo_apo_cde,
       paid_in_advance_year_cnt,
       sdo_payment_type_cde,
       policy_fee_ind,
       first_year_ind,
       ipo_ind,
       ltc_activity_cde,
       ltc_premium_adjustment_ind,
       late_payment_offer_end_dt,
       vanishing_premium_effective_dt,
       alir_bill_premium_amt,
       alir_bill_premium_quality_cde,
       al_sup_termination_amt,
       mpo_apo_net_payment_due_amt,
       mpo_apo_net_payment_quality_cde,
       mpo_apo_paid_amt,
       mpo_apo_paid_amt_quality_cde,
       apo_credit_amt,
       apo_credit_amt_quality_cde,
       annual_premium_amt,
       annual_premium_quality_cde,
       annualized_premium_amt,
       annualized_premium_quality_cde,
       gross_annual_premium_amt,
       gross_annual_premium_quality_cde,
       total_annual_premium_amt,
       total_annual_premium_quality_cde,
       max_annual_payment_year_nr,
       base_rider_monthly_premium_amt,
       base_rider_monthly_premium_quality_cde,
       base_rider_annual_premium_amt,
       base_rider_annual_premium_quality_cde,
       bill_premium_amt,
       bill_premium_quality_cde,
       cli_premium_bill_cde,
       cost_due_amt,
       cost_basis_amt,
       cost_basis_quality_cde,
       current_premium_credit_base_amt,
       current_premium_credit_base_quality_cde,
       current_year_payment_amt,
       next_year_premium_credit_base_amt,
       next_year_premium_credit_base_quality_cde,
       current_premium_credit_ltc_amt,
       current_premium_credit_ltc_quality_cde,
       next_year_premium_credit_ltc_amt,
       next_year_premium_credit_ltc_quality_cde,
       ewl_deficit_premium_payup_amt,
       ewl_deficit_paid_to_year_month_txt,
       fraction_premium_credit_base_amt,
       fraction_premium_credit_base_quality_cde,
       fraction_premium_credit_ltc_amt,
       fraction_premium_credit_ltc_quality_cde,
       gross_premium_fpdup_addns_amt,
       gross_premium_fpdup_addns_quality_cde,
       ltcir_return_premium_amt,
       ltcir_return_premium_quality_cde,
       ltcir_reduced_addns_amt,
       ltcir_reduced_addns_quality_cde,
       ltc_extended_benefit_pool_amt,
       ltc_extended_benefit_pool_quality_cde,
       new_business_premium_paid_amt,
       target_premium_amt,
       target_premium_quality_cde,
       total_monthly_premium_amt,         --new
       total_monthly_premium_quality_cde, --new
       unearned_past_due_premium_amt,
       unearned_past_due_premium_quality_cde,
       ytd_premium_amt,
       initial_premium_amt,
       pytd_premium_amt,
       last_bill_method_cde,
       premium_refund_amt,
       premium_refund_quality_cde,
       pro_rata_refund_amt,
       pro_rata_refund_quality_cde,
       advance_premium_refund_amt,
       advance_premium_refund_quality_cde,
       vanish_bill_amt,
       lisr_disability_cost_amt,
       payment_draft_dy_cde,
       invoice_account_id_txt,
       group_account_type_cde,
       group_account_nr_txt,
       pac_account_id_txt,
       pac_account_type_cde,
       bank_nm,
       billing_arrangement_id_txt,
       bill_method_type_cde,
       consolidated_bill_type_cde,
       alir_bill_amt,
       alir_bill_amt_quality_cde,
       bank_id,
       permenant_flat_extra_premium_amt,
       temperory_flat_extra_premium_amt,
       permenant_flat_extra_cost_amt,
       temperory_flat_extra_cost_amt,
       paid_to_dt,
       paid_to_dt_txt,
       last_premium_adjustment_dt,
       last_premium_collection_dt,
       last_premium_paid_dt,
       last_transaction_dt,
       premium_accumulated_amt,
       premium_accumulated_amt_quality_cde,
       last_deposit_dt,
       last_deposit_amt,
       last_deposit_amt_quality_cde,
       administration_charge_amt,
       minus_1_tax_rt,
       bill_to_dt,
       apm_next_bill_dt,
       last_premium_paid_amt,
       begin_dt,
       begin_dtm,
       row_process_dtm,
       check_sum,
       end_dt,
       end_dtm,
       restricted_row_ind,
       current_row_ind,
       logical_delete_ind,
       source_system_id,
       audit_id,
       update_audit_id,
       source_delete_ind,
       transaction_dt,
       transaction_dtm,
       net_cash_val_amt,
       net_cash_val_as_of_dt,
       death_benefit_amt,
       death_benefit_as_of_dt,
       wp_premium_amt,
       wp_premium_issue_age_nr,
       wp_premium_issue_dt,
       wp_premium_duration_nr,
       payout_amt,
       premium_tax_dt,
       bill_day_nr
from edw_staging.aifrps_fact_agreement_detail_pre_work
where dim_agreement_natural_key_hash_uuid not in
      (select distinct dim_agreement_natural_key_hash_uuid
       from {{target_schema}}.fact_agreement_detail )
and upper(process_ind) in ('A','C');



-- Step 4 insert only updated records to target
-- use dim_agreement_natural_key_hash_uuid + begin_dt as key
insert into edw_work.aifrps_fact_agreement_detail
(fact_agreement_detail_natural_key_hash_uuid,
 dim_agreement_natural_key_hash_uuid,
 pay7_period_premium_amt,
 pay7_period_premium_quality_cde,
 pay7_period_premium_end_dt,
 pay7_period_premium_end_dt_quality_cde,
 pay7_period_premium_start_dt,
 pay7_period_premium_start_dt_quality_cde,
 tcc_amt,
 total_monthly_benefit_amt,
 ultimate_face_amt,
 grace_period_payment_amt,
 grace_period_payment_quality_cde,
 policy_unit_face_amt,
 policy_income_amt,
 current_dividend_amt,
 accumulated_dividend_amt,
 accumulated_dividend_quality_cde,
 rp_current_dividend_month_txt,
 rp_current_dividend_year_txt,
 rp_current_dividend_amt,
 rp_dividend_amt,
 rp_dividend_amt_quality_cde,
 ri_dividend_amt,
 ri_dividend_amt_quality_cde,
 agreement_dividend_year_nr,
 applied_dividend_amt,
 applied_dividend_quality_cde,
 base_dividend_amt,
 base_dividend_quality_cde,
 previous_year_dividend_amt,
 previous_year_dividend_quality_cde,
 dividend_accumulated_available_amt,
 dividend_accumulated_available_quality_cde,
 dividend_available_amt,
 dividend_available_quality_cde,
 last_dividend_credit_amt,
 last_dividend_credit_quality_cde,
 ltcir_dividend_benefit_pool_amt,
 ltcir_dividend_benefit_pool_quality_cde,
 interest_on_dividend_accumulated_to_dt_amt,
 interest_on_dividend_accumulated_to_dt_quality_cde,
 settlement_dividend_amt,
 settlement_dividend_quality_cde,
 dividend_accumulated_tax_amt,
 dividend_accumulated_tax_quality_cde,
 dividend_mo_da,
 bill_mode_cde,
 source_bill_mode_cde,
 ebill_preference_cde,
 no_bill_reason_cde,
 bill_frequency_txt,
 premium_tax_state_cde,
 returned_check_cde,
 sdo_mpo_apo_cde,
 paid_in_advance_year_cnt,
 sdo_payment_type_cde,
 policy_fee_ind,
 first_year_ind,
 ipo_ind,
 ltc_activity_cde,
 ltc_premium_adjustment_ind,
 late_payment_offer_end_dt,
 vanishing_premium_effective_dt,
 alir_bill_premium_amt,
 alir_bill_premium_quality_cde,
 al_sup_termination_amt,
 mpo_apo_net_payment_due_amt,
 mpo_apo_net_payment_quality_cde,
 mpo_apo_paid_amt,
 mpo_apo_paid_amt_quality_cde,
 apo_credit_amt,
 apo_credit_amt_quality_cde,
 annual_premium_amt,
 annual_premium_quality_cde,
 annualized_premium_amt,
 annualized_premium_quality_cde,
 gross_annual_premium_amt,
 gross_annual_premium_quality_cde,
 total_annual_premium_amt,
 total_annual_premium_quality_cde,
 max_annual_payment_year_nr,
 base_rider_monthly_premium_amt,
 base_rider_monthly_premium_quality_cde,
 base_rider_annual_premium_amt,
 base_rider_annual_premium_quality_cde,
 bill_premium_amt,
 bill_premium_quality_cde,
 cli_premium_bill_cde,
 cost_due_amt,
 cost_basis_amt,
 cost_basis_quality_cde,
 current_premium_credit_base_amt,
 current_premium_credit_base_quality_cde,
 current_year_payment_amt,
 next_year_premium_credit_base_amt,
 next_year_premium_credit_base_quality_cde,
 current_premium_credit_ltc_amt,
 current_premium_credit_ltc_quality_cde,
 next_year_premium_credit_ltc_amt,
 next_year_premium_credit_ltc_quality_cde,
 ewl_deficit_premium_payup_amt,
 ewl_deficit_paid_to_year_month_txt,
 fraction_premium_credit_base_amt,
 fraction_premium_credit_base_quality_cde,
 fraction_premium_credit_ltc_amt,
 fraction_premium_credit_ltc_quality_cde,
 gross_premium_fpdup_addns_amt,
 gross_premium_fpdup_addns_quality_cde,
 ltcir_return_premium_amt,
 ltcir_return_premium_quality_cde,
 ltcir_reduced_addns_amt,
 ltcir_reduced_addns_quality_cde,
 ltc_extended_benefit_pool_amt,
 ltc_extended_benefit_pool_quality_cde,
 new_business_premium_paid_amt,
 target_premium_amt,
 target_premium_quality_cde,
 total_monthly_premium_amt, --new
 total_monthly_premium_quality_cde, --new
 unearned_past_due_premium_amt,
 unearned_past_due_premium_quality_cde,
 ytd_premium_amt,
 initial_premium_amt,
 pytd_premium_amt,
 last_bill_method_cde,
 premium_refund_amt,
 premium_refund_quality_cde,
 pro_rata_refund_amt,
 pro_rata_refund_quality_cde,
 advance_premium_refund_amt,
 advance_premium_refund_quality_cde,
 vanish_bill_amt,
 lisr_disability_cost_amt,
 payment_draft_dy_cde,
 invoice_account_id_txt,
 group_account_type_cde,
 group_account_nr_txt,
 pac_account_id_txt,
 pac_account_type_cde,
 bank_nm,
 billing_arrangement_id_txt,
 bill_method_type_cde,
 consolidated_bill_type_cde,
 alir_bill_amt,
 alir_bill_amt_quality_cde,
 bank_id,
 permenant_flat_extra_premium_amt,
 temperory_flat_extra_premium_amt,
 permenant_flat_extra_cost_amt,
 temperory_flat_extra_cost_amt,
 paid_to_dt,
 paid_to_dt_txt,
 last_premium_adjustment_dt,
 last_premium_collection_dt,
 last_premium_paid_dt,
 last_transaction_dt,
 premium_accumulated_amt,
 premium_accumulated_amt_quality_cde,
 last_deposit_dt,
 last_deposit_amt,
 last_deposit_amt_quality_cde,
 administration_charge_amt,
 minus_1_tax_rt,
 bill_to_dt,
 apm_next_bill_dt,
 last_premium_paid_amt,
 begin_dt,
 begin_dtm,
 row_process_dtm,
 check_sum,
 end_dt,
 end_dtm,
 restricted_row_ind,
 current_row_ind,
 logical_delete_ind,
 source_system_id,
 audit_id,
 update_audit_id,
 source_delete_ind,
 transaction_dt,
 transaction_dtm,
 net_cash_val_amt,
 net_cash_val_as_of_dt,
 death_benefit_amt,
 death_benefit_as_of_dt,
 wp_premium_amt,
 wp_premium_issue_age_nr,
 wp_premium_issue_dt,
 wp_premium_duration_nr,
 payout_amt,
 premium_tax_dt,
 bill_day_nr)
select prework.fact_agreement_detail_natural_key_hash_uuid,
       prework.dim_agreement_natural_key_hash_uuid,
       prework.pay7_period_premium_amt,
       prework.pay7_period_premium_quality_cde,
       prework.pay7_period_premium_end_dt,
       prework.pay7_period_premium_end_dt_quality_cde,
       prework.pay7_period_premium_start_dt,
       prework.pay7_period_premium_start_dt_quality_cde,
       prework.tcc_amt,
       prework.total_monthly_benefit_amt,
       prework.ultimate_face_amt,
       prework.grace_period_payment_amt,
       prework.grace_period_payment_quality_cde,
       prework.policy_unit_face_amt,
       prework.policy_income_amt,
       prework.current_dividend_amt,
       prework.accumulated_dividend_amt,
       prework.accumulated_dividend_quality_cde,
       prework.rp_current_dividend_month_txt,
       prework.rp_current_dividend_year_txt,
       prework.rp_current_dividend_amt,
       prework.rp_dividend_amt,
       prework.rp_dividend_amt_quality_cde,
       prework.ri_dividend_amt,
       prework.ri_dividend_amt_quality_cde,
       prework.agreement_dividend_year_nr,
       prework.applied_dividend_amt,
       prework.applied_dividend_quality_cde,
       prework.base_dividend_amt,
       prework.base_dividend_quality_cde,
       prework.previous_year_dividend_amt,
       prework.previous_year_dividend_quality_cde,
       prework.dividend_accumulated_available_amt,
       prework.dividend_accumulated_available_quality_cde,
       prework.dividend_available_amt,
       prework.dividend_available_quality_cde,
       prework.last_dividend_credit_amt,
       prework.last_dividend_credit_quality_cde,
       prework.ltcir_dividend_benefit_pool_amt,
       prework.ltcir_dividend_benefit_pool_quality_cde,
       prework.interest_on_dividend_accumulated_to_dt_amt,
       prework.interest_on_dividend_accumulated_to_dt_quality_cde,
       prework.settlement_dividend_amt,
       prework.settlement_dividend_quality_cde,
       prework.dividend_accumulated_tax_amt,
       prework.dividend_accumulated_tax_quality_cde,
       prework.dividend_mo_da,
       prework.bill_mode_cde,
       prework.source_bill_mode_cde,
       prework.ebill_preference_cde,
       prework.no_bill_reason_cde,
       prework.bill_frequency_txt,
       prework.premium_tax_state_cde,
       prework.returned_check_cde,
       prework.sdo_mpo_apo_cde,
       prework.paid_in_advance_year_cnt,
       prework.sdo_payment_type_cde,
       prework.policy_fee_ind,
       prework.first_year_ind,
       prework.ipo_ind,
       prework.ltc_activity_cde,
       prework.ltc_premium_adjustment_ind,
       prework.late_payment_offer_end_dt,
       prework.vanishing_premium_effective_dt,
       prework.alir_bill_premium_amt,
       prework.alir_bill_premium_quality_cde,
       prework.al_sup_termination_amt,
       prework.mpo_apo_net_payment_due_amt,
       prework.mpo_apo_net_payment_quality_cde,
       prework.mpo_apo_paid_amt,
       prework.mpo_apo_paid_amt_quality_cde,
       prework.apo_credit_amt,
       prework.apo_credit_amt_quality_cde,
       prework.annual_premium_amt,
       prework.annual_premium_quality_cde,
       prework.annualized_premium_amt,
       prework.annualized_premium_quality_cde,
       prework.gross_annual_premium_amt,
       prework.gross_annual_premium_quality_cde,
       prework.total_annual_premium_amt,
       prework.total_annual_premium_quality_cde,
       prework.max_annual_payment_year_nr,
       prework.base_rider_monthly_premium_amt,
       prework.base_rider_monthly_premium_quality_cde,
       prework.base_rider_annual_premium_amt,
       prework.base_rider_annual_premium_quality_cde,
       prework.bill_premium_amt,
       prework.bill_premium_quality_cde,
       prework.cli_premium_bill_cde,
       prework.cost_due_amt,
       prework.cost_basis_amt,
       prework.cost_basis_quality_cde,
       prework.current_premium_credit_base_amt,
       prework.current_premium_credit_base_quality_cde,
       prework.current_year_payment_amt,
       prework.next_year_premium_credit_base_amt,
       prework.next_year_premium_credit_base_quality_cde,
       prework.current_premium_credit_ltc_amt,
       prework.current_premium_credit_ltc_quality_cde,
       prework.next_year_premium_credit_ltc_amt,
       prework.next_year_premium_credit_ltc_quality_cde,
       prework.ewl_deficit_premium_payup_amt,
       prework.ewl_deficit_paid_to_year_month_txt,
       prework.fraction_premium_credit_base_amt,
       prework.fraction_premium_credit_base_quality_cde,
       prework.fraction_premium_credit_ltc_amt,
       prework.fraction_premium_credit_ltc_quality_cde,
       prework.gross_premium_fpdup_addns_amt,
       prework.gross_premium_fpdup_addns_quality_cde,
       prework.ltcir_return_premium_amt,
       prework.ltcir_return_premium_quality_cde,
       prework.ltcir_reduced_addns_amt,
       prework.ltcir_reduced_addns_quality_cde,
       prework.ltc_extended_benefit_pool_amt,
       prework.ltc_extended_benefit_pool_quality_cde,
       prework.new_business_premium_paid_amt,
       prework.target_premium_amt,
       prework.target_premium_quality_cde,
       prework.total_monthly_premium_amt,         --new
       prework.total_monthly_premium_quality_cde, --new
       prework.unearned_past_due_premium_amt,
       prework.unearned_past_due_premium_quality_cde,
       prework.ytd_premium_amt,
       prework.initial_premium_amt,
       prework.pytd_premium_amt,
       prework.last_bill_method_cde,
       prework.premium_refund_amt,
       prework.premium_refund_quality_cde,
       prework.pro_rata_refund_amt,
       prework.pro_rata_refund_quality_cde,
       prework.advance_premium_refund_amt,
       prework.advance_premium_refund_quality_cde,
       prework.vanish_bill_amt,
       prework.lisr_disability_cost_amt,
       prework.payment_draft_dy_cde,
       prework.invoice_account_id_txt,
       prework.group_account_type_cde,
       prework.group_account_nr_txt,
       prework.pac_account_id_txt,
       prework.pac_account_type_cde,
       prework.bank_nm,
       prework.billing_arrangement_id_txt,
       prework.bill_method_type_cde,
       prework.consolidated_bill_type_cde,
       prework.alir_bill_amt,
       prework.alir_bill_amt_quality_cde,
       prework.bank_id,
       prework.permenant_flat_extra_premium_amt,
       prework.temperory_flat_extra_premium_amt,
       prework.permenant_flat_extra_cost_amt,
       prework.temperory_flat_extra_cost_amt,
       prework.paid_to_dt,
       prework.paid_to_dt_txt,
       prework.last_premium_adjustment_dt,
       prework.last_premium_collection_dt,
       prework.last_premium_paid_dt,
       prework.last_transaction_dt,
       prework.premium_accumulated_amt,
       prework.premium_accumulated_amt_quality_cde,
       prework.last_deposit_dt,
       prework.last_deposit_amt,
       prework.last_deposit_amt_quality_cde,
       prework.administration_charge_amt,
       prework.minus_1_tax_rt,
       prework.bill_to_dt,
       prework.apm_next_bill_dt,
       prework.last_premium_paid_amt,
       prework.begin_dt,
       prework.begin_dtm,
       prework.row_process_dtm,
       prework.check_sum,
       prework.end_dt,
       prework.end_dtm,
       prework.restricted_row_ind,
       prework.current_row_ind,
       prework.logical_delete_ind,
       prework.source_system_id,
       prework.audit_id,
       prework.update_audit_id,
       prework.source_delete_ind,
       prework.transaction_dt,
       prework.transaction_dtm,
       prework.net_cash_val_amt,
       prework.net_cash_val_as_of_dt,
       prework.death_benefit_amt,
       prework.death_benefit_as_of_dt,
       prework.wp_premium_amt,
       prework.wp_premium_issue_age_nr,
       prework.wp_premium_issue_dt,
       prework.wp_premium_duration_nr,
       prework.payout_amt,
       prework.premium_tax_dt,
       prework.bill_day_nr
from edw_staging.aifrps_fact_agreement_detail_pre_work prework
         join (
    select dim_agreement_natural_key_hash_uuid,
           check_sum,
           row_number() OVER (PARTITION BY dim_agreement_natural_key_hash_uuid ORDER BY begin_dt DESC) AS rownum
    from {{target_schema}}.fact_agreement_detail
) tgt
              on tgt.dim_agreement_natural_key_hash_uuid = prework.dim_agreement_natural_key_hash_uuid
where tgt.rownum = 1
  and upper(prework.process_ind) in ('A', 'C')
  and tgt.check_sum <> prework.check_sum
;

select analyze_statistics('edw_work.aifrps_fact_agreement_detail');