CREATE TABLE edw_work.dim_financial_transaction_aifrps
(
    dim_financial_transaction_natural_key_hash_uuid uuid NOT NULL,
    financial_transaction_unique_id varchar(200) NOT NULL,
    ref_financial_transaction_source_natural_key_hash_uuid uuid NOT NULL,
    ref_financial_transaction_type_natural_key_hash_uuid uuid NOT NULL,
    pay_group_nr_txt varchar(20),
    check_form_id varchar(50),
    transaction_dt timestamp(6),
    check_status_cde varchar(50),
    account_nr_txt varchar(50),
    tax_reporting_cde varchar(50),
    original_check_nr numeric(20,0),
    distribution_cde varchar(50),
    source_payee_unique_id varchar(20),
    clear_dt timestamp(6),
    clear_reference_nr_txt varchar(20),
    reversal_dt date,
    begin_dt date NOT NULL DEFAULT '0001-01-01'::date,
    begin_dtm timestamp(6) NOT NULL,
    row_process_dtm timestamp(6) NOT NULL,
    audit_id int NOT NULL DEFAULT 0,
    logical_delete_ind boolean NOT NULL DEFAULT false,
    check_sum uuid NOT NULL,
    current_row_ind boolean NOT NULL DEFAULT true,
    end_dt date NOT NULL DEFAULT '9999-12-31'::date,
    end_dtm timestamp(6) NOT NULL,
    source_system_id varchar(50) NOT NULL,
    restricted_row_ind boolean NOT NULL DEFAULT false,
    row_sid  IDENTITY ,
    update_audit_id int NOT NULL DEFAULT 0,
    source_delete_ind boolean NOT NULL,
    source_transaction_key_txt varchar(50),
    routing_nr_txt varchar(50),
    payment_method_cde varchar(50),
    previous_source_transaction_key_txt varchar(50),
    effective_dt date,
    system_dt date,
    transaction_cde varchar(50),
    source_transaction_cde varchar(50),
    transaction_reversal_cde varchar(25),
    admin_fund_cde varchar(25),
    product_id varchar(50),
    company_cde varchar(25),
    source_company_cde varchar(50),
    pt1_kind_cde varchar(50),
    product_tier_cde varchar(50),
    fund_type_cde varchar(50),
    source_fund_type_cde varchar(50),
    coverage_type_cde varchar(25),
    coverage_occurance_nr int,
    transaction_source_id varchar(50),
    transaction_memo_cde varchar(50),
    rollover_cde varchar(25),
    source_rollover_cde varchar(50),
    gmib_status_cde varchar(25),
    administration_cde varchar(50),
    source_administration_cde varchar(50),
    disbursement_transaction_nr_txt varchar(50),
    replacement_transaction_nr_txt varchar(50),
    transaction_desc varchar(300),
    source_transaction_desc varchar(300),
    transaction_reporting_desc varchar(300),
    transaction_reporting_detail_desc varchar(300)
);

CREATE TABLE edw_work.rel_financial_transaction_aifrps
(
    dim_financial_transaction_natural_key_hash_uuid uuid NOT NULL,
    dim_party_natural_key_hash_uuid uuid,
    dim_agreement_natural_key_hash_uuid uuid NOT NULL,
    begin_dt date NOT NULL DEFAULT '0001-01-01'::date,
    begin_dtm timestamp(6) NOT NULL,
    row_process_dtm timestamp(6) NOT NULL,
    audit_id int NOT NULL DEFAULT 0,
    logical_delete_ind boolean NOT NULL DEFAULT false,
    check_sum uuid NOT NULL,
    current_row_ind boolean NOT NULL DEFAULT true,
    end_dt date NOT NULL DEFAULT '9999-12-31'::date,
    end_dtm timestamp(6) NOT NULL,
    source_system_id varchar(50) NOT NULL,
    restricted_row_ind boolean NOT NULL DEFAULT false,
    row_sid  IDENTITY ,
    update_audit_id int NOT NULL DEFAULT 0,
    source_delete_ind boolean NOT NULL DEFAULT false,
    dim_fund_natural_key_hash_uuid uuid
);


CREATE TABLE edw_work.fact_financial_detail_aifrps
(
    fact_financial_detail_natural_key_hash_uuid uuid NOT NULL,
    dim_financial_transaction_natural_key_hash_uuid uuid NOT NULL,
    calendar_dt date NOT NULL,
    transaction_detail_type_cde varchar(50) NOT NULL,
    transaction_detail_category_cde varchar(50),
    transaction_detail_method_cde varchar(50),
    source_transaction_detail_category_cde varchar(50),
    source_transaction_detail_method_cde varchar(50),
    source_transaction_detail_type_cde varchar(50),
    transaction_amt numeric(17,4),
    row_process_dtm timestamp(6) NOT NULL,
    audit_id int NOT NULL DEFAULT 0,
    logical_delete_ind boolean NOT NULL DEFAULT false,
    check_sum uuid NOT NULL,
    source_system_id varchar(50) NOT NULL,
    restricted_row_ind boolean NOT NULL DEFAULT false,
    row_sid  IDENTITY ,
    update_audit_id int NOT NULL DEFAULT 0,
    source_delete_ind boolean NOT NULL,
    credit_debit_type_cde varchar(25),
    source_credit_debit_type_cde varchar(25),
    transaction_sequence_nr int,
    waiver_reason_cde varchar(25),
    source_waiver_reason_cde varchar(25),
    money_source_cde varchar(25),
    source_money_source_cde varchar(50),
    bill_mode_cde varchar(25),
    source_bill_mode_cde varchar(50),
    premium_paid_dt date,
    premium_due_dt timestamp,
    transaction_duration_nr varchar(50),
    deposits_tax_year_nr int,
    fund_units_cnt numeric(18,6),
    fund_unit_val_rt numeric(18,6),
    fund_declared_interest_rt numeric(12,9),
    basis_points_val numeric(17,4),
    commission_overdue_pct numeric(19,6),
    bonus_rt numeric(19,6),
    post_tefra_cost_basis_amt numeric(17,4),
    pre_tefra_cost_basis_amt numeric(17,4),
    rollover_amt numeric(17,4),
    new_money_amt numeric(17,4),
    exchange_1035_amt numeric(17,4),
    transfer_amt numeric(17,4),
    premium_due_amt numeric(17,4),
    interest_due_amt numeric(17,4),
    premium_payment_cash_amt numeric(17,4),
    waiver_premium_payment_cash_amt numeric(17,4),
    premium_payment_loan_amt numeric(17,4),
    premium_payment_dividend_amt numeric(17,4),
    premium_payment_abr_dividend_amt numeric(17,4)
);