SELECT ALL_TABLES.RUN_ID FROM
(SELECT DISTINCT RUN_ID FROM PROD_STND_VW_TERSUN.AGMT_CVG_VW_AIF_RPS WHERE SRC_SYS_ID = 72
UNION
SELECT DISTINCT RUN_ID FROM PROD_STND_VW_TERSUN.AGMT_CVG_BEN_VW_AIF_RPS WHERE SRC_SYS_ID = 72
) ALL_TABLES 
WHERE ALL_TABLES.RUN_ID >
(
SELECT NVL(MAX(AUDIT_ID),0) FROM EDW_TDSUNSET.DIM_COVERAGE WHERE SOURCE_SYSTEM_ID = 266
)
ORDER BY ALL_TABLES.RUN_ID ASC
;