
insert into edw_financial_transactions.dim_financial_transaction
(
dim_financial_transaction_natural_key_hash_uuid,
financial_transaction_unique_id,
ref_financial_transaction_source_natural_key_hash_uuid,
ref_financial_transaction_type_natural_key_hash_uuid,
pay_group_nr_txt,
check_form_id,
transaction_dt,
check_status_cde,
account_nr_txt,
tax_reporting_cde,
original_check_nr,
distribution_cde,
source_payee_unique_id,
clear_dt,
clear_reference_nr_txt,
reversal_dt,
begin_dt,
begin_dtm,
row_process_dtm,
audit_id,
logical_delete_ind,
check_sum,
current_row_ind,
end_dt,
end_dtm,
source_system_id,
restricted_row_ind,
update_audit_id,
source_delete_ind,
source_transaction_key_txt,
routing_nr_txt,
payment_method_cde,
previous_source_transaction_key_txt,
effective_dt,
system_dt,
transaction_cde,
source_transaction_cde,
transaction_reversal_cde,
admin_fund_cde,
product_id,
company_cde,
source_company_cde,
pt1_kind_cde,
product_tier_cde,
fund_type_cde,
source_fund_type_cde,
coverage_type_cde,
coverage_occurance_nr,
transaction_source_id,
transaction_memo_cde,
rollover_cde,
source_rollover_cde,
gmib_status_cde,
administration_cde,
source_administration_cde,
disbursement_transaction_nr_txt,
replacement_transaction_nr_txt,
transaction_desc,
source_transaction_desc,
transaction_reporting_desc,
transaction_reporting_detail_desc
)

select 
uuid_gen(
clean_string(agreement_source_cde),
clean_string(agreement_type_cde),
clean_string(agreement_nr_pfx),
clean_string(agreement_nr),
clean_string(agreement_nr_sfx),
clean_string(replacement_transaction_nr_txt1),
clean_string(financial_transaction_source),
clean_string(financial_transaction_type))::uuid as dim_financial_transaction_natural_key_hash_uuid,

prehash_value(
clean_string(agreement_source_cde),
clean_string(agreement_type_cde),
clean_string(agreement_nr_pfx),
clean_string(agreement_nr),
clean_string(agreement_nr_sfx),
clean_string(replacement_transaction_nr_txt)) as financial_transaction_unique_id,

uuid_gen(
clean_string(financial_transaction_source))::uuid as ref_financial_transaction_source_natural_key_hash_uuid,

uuid_gen(
clean_string(financial_transaction_type))::uuid as ref_financial_transaction_type_natural_key_hash_uuid,

null as pay_group_nr_txt,
null as check_form_id,
null as transaction_dt,
null as check_status_cde,
null as account_nr_txt,
null as tax_reporting_cde,
null as original_check_nr,
null as distribution_cde,
null as source_payee_unique_id,
null as clear_dt,
null as clear_reference_nr_txt,
null as reversal_dt,
begin_dt,
begin_dtm,
row_process_dtm,
audit_id,
logical_delete_ind,
uuid_gen(source_delete_ind)::uuid as check_sum,
current_row_ind,
end_dt,
end_dtm,
source_system_id,
restricted_row_ind,
update_audit_id,
source_delete_ind,
null as source_transaction_key_txt,
null as routing_nr_txt,
null as payment_method_cde,
null as previous_source_transaction_key_txt,
null as effective_dt,
null as system_dt,
null as transaction_cde,
null as source_transaction_cde,
null as transaction_reversal_cde,
null as admin_fund_cde,
null as product_id,
null as company_cde,
null as source_company_cde,
null as pt1_kind_cde,
null as product_tier_cde,
null as fund_type_cde,
null as source_fund_type_cde,
null as coverage_type_cde,
null as coverage_occurance_nr,
null as transaction_source_id,
null as transaction_memo_cde,
null as rollover_cde,
null as source_rollover_cde,
null as gmib_status_cde,
null as administration_cde,
null as source_administration_cde,
null as disbursement_transaction_nr_txt,
null as replacement_transaction_nr_txt,
null as transaction_desc,
null as source_transaction_desc,
null as transaction_reporting_desc,
null as transaction_reporting_detail_desc
from (

select 
'Ipa' as agreement_type_cde,
ar.carr_admin_sys_cd as agreement_source_cde,
public.udf_isnum_lpad(ar.hldg_key_pfx, 20, '0', true) as agreement_nr_pfx,
lpad(ar.hldg_key::varchar, 20, '0') as agreement_nr,
public.udf_isnum_lpad(ar.hldg_key_sfx, 20, '0', true) as agreement_nr_sfx,
ar.repl_txn_nr as replacement_transaction_nr_txt,
null as replacement_transaction_nr_txt1,
'Rps' as financial_transaction_source,
'Replacement Transaction' as financial_transaction_type,
ar.agmt_repl_fr_dt::date as begin_dt,
ar.agmt_repl_fr_dt::timestamp as begin_dtm,
current_timestamp(6) as row_process_dtm,
'9999-12-31'::date as end_dt,
'9999-12-31'::timestamp as end_dtm,
false as restricted_row_ind,
false as logical_delete_ind,
266 as source_system_id,
ar.run_id as audit_id,
ar.updt_run_id as update_audit_id,
true as current_row_ind,
--needs to verified for other admins
case when ar.src_del_ind = 'N' then false
else true end  as source_delete_ind
from (
select	b.*,
row_number () over(partition by agmt_id order by agmt_repl_fr_dt asc) as rownumber
from prod_stnd_vw_tersun.agmt_repl_vw_aif_rps b
where b.src_sys_id =72 and b.agmt_id not in (53727909,54957911,55069911,56479917,61820911,68514915,69778912)
) ar where ar.rownumber =1 
)dim_financial_transaction;


insert into edw_financial_transactions.dim_financial_transaction
(
dim_financial_transaction_natural_key_hash_uuid,
financial_transaction_unique_id,
ref_financial_transaction_source_natural_key_hash_uuid,
ref_financial_transaction_type_natural_key_hash_uuid,
pay_group_nr_txt,
check_form_id,
transaction_dt,
check_status_cde,
account_nr_txt,
tax_reporting_cde,
original_check_nr,
distribution_cde,
source_payee_unique_id,
clear_dt,
clear_reference_nr_txt,
reversal_dt,
begin_dt,
begin_dtm,
row_process_dtm,
audit_id,
logical_delete_ind,
check_sum,
current_row_ind,
end_dt,
end_dtm,
source_system_id,
restricted_row_ind,
update_audit_id,
source_delete_ind,
source_transaction_key_txt,
routing_nr_txt,
payment_method_cde,
previous_source_transaction_key_txt,
effective_dt,
system_dt,
transaction_cde,
source_transaction_cde,
transaction_reversal_cde,
admin_fund_cde,
product_id,
company_cde,
source_company_cde,
pt1_kind_cde,
product_tier_cde,
fund_type_cde,
source_fund_type_cde,
coverage_type_cde,
coverage_occurance_nr,
transaction_source_id,
transaction_memo_cde,
rollover_cde,
source_rollover_cde,
gmib_status_cde,
administration_cde,
source_administration_cde,
disbursement_transaction_nr_txt,
replacement_transaction_nr_txt,
transaction_desc,
source_transaction_desc,
transaction_reporting_desc,
transaction_reporting_detail_desc
)

select 
uuid_gen(
clean_string(agreement_source_cde),
clean_string(agreement_type_cde),
clean_string(agreement_nr_pfx),
clean_string(agreement_nr),
clean_string(agreement_nr_sfx),
clean_string(replacement_transaction_nr_txt1),
clean_string(financial_transaction_source),
clean_string(financial_transaction_type))::uuid as dim_financial_transaction_natural_key_hash_uuid,

prehash_value(
clean_string(agreement_source_cde),
clean_string(agreement_type_cde),
clean_string(agreement_nr_pfx),
clean_string(agreement_nr),
clean_string(agreement_nr_sfx),
clean_string(replacement_transaction_nr_txt)) as financial_transaction_unique_id,

uuid_gen(
clean_string(financial_transaction_source))::uuid as ref_financial_transaction_source_natural_key_hash_uuid,

uuid_gen(
clean_string(financial_transaction_type))::uuid as ref_financial_transaction_type_natural_key_hash_uuid,

null as pay_group_nr_txt,
null as check_form_id,
null as transaction_dt,
null as check_status_cde,
null as account_nr_txt,
null as tax_reporting_cde,
null as original_check_nr,
null as distribution_cde,
null as source_payee_unique_id,
null as clear_dt,
null as clear_reference_nr_txt,
null as reversal_dt,
begin_dt,
begin_dtm,
row_process_dtm,
audit_id,
logical_delete_ind,
uuid_gen(source_delete_ind)::uuid as check_sum,
current_row_ind,
end_dt,
end_dtm,
source_system_id,
restricted_row_ind,
update_audit_id,
source_delete_ind,
null as source_transaction_key_txt,
null as routing_nr_txt,
null as payment_method_cde,
null as previous_source_transaction_key_txt,
null as effective_dt,
null as system_dt,
null as transaction_cde,
null as source_transaction_cde,
null as transaction_reversal_cde,
null as admin_fund_cde,
null as product_id,
null as company_cde,
null as source_company_cde,
null as pt1_kind_cde,
null as product_tier_cde,
null as fund_type_cde,
null as source_fund_type_cde,
null as coverage_type_cde,
null as coverage_occurance_nr,
null as transaction_source_id,
null as transaction_memo_cde,
null as rollover_cde,
null as source_rollover_cde,
null as gmib_status_cde,
null as administration_cde,
null as source_administration_cde,
null as disbursement_transaction_nr_txt,
null as replacement_transaction_nr_txt,
null as transaction_desc,
null as source_transaction_desc,
null as transaction_reporting_desc,
null as transaction_reporting_detail_desc
from (

select 
'Ipa' as agreement_type_cde,
ar.carr_admin_sys_cd as agreement_source_cde,
public.udf_isnum_lpad(ar.hldg_key_pfx, 20, '0', true) as agreement_nr_pfx,
lpad(ar.hldg_key::varchar, 20, '0') as agreement_nr,
public.udf_isnum_lpad(ar.hldg_key_sfx, 20, '0', true) as agreement_nr_sfx,
ar.repl_txn_nr as replacement_transaction_nr_txt,
null as replacement_transaction_nr_txt1,
'Rps' as financial_transaction_source,
'Replacement Transaction' as financial_transaction_type,
ar.agmt_repl_fr_dt::date as begin_dt,
ar.agmt_repl_fr_dt::timestamp as begin_dtm,
current_timestamp(6) as row_process_dtm,
ar.agmt_repl_to_dt::date as end_dt,
ar.agmt_repl_to_dt::timestamp as end_dtm,
false as restricted_row_ind,
false as logical_delete_ind,
266 as source_system_id,
ar.run_id as audit_id,
ar.updt_run_id as update_audit_id,
case when ar.curr_ind ='N' then false
else true end  as current_row_ind,
--needs to verified for other admins
case when ar.src_del_ind = 'N' then false
else true end  as source_delete_ind
from (
select	* from prod_stnd_vw_tersun.agmt_repl_vw_aif_rps b
where b.src_sys_id =72 and b.agmt_id in (53727909,54957911,55069911,56479917,61820911,68514915,69778912)
) ar 
)dim_financial_transaction;

