insert into edw_work.dim_financial_transaction_aifrps
(
    dim_financial_transaction_natural_key_hash_uuid,
    financial_transaction_unique_id,
    ref_financial_transaction_source_natural_key_hash_uuid,
    ref_financial_transaction_type_natural_key_hash_uuid,
    pay_group_nr_txt,
    check_form_id,
    transaction_dt,
    check_status_cde,
    account_nr_txt,
    tax_reporting_cde,
    original_check_nr,
    distribution_cde,
    source_payee_unique_id,
    clear_dt,
    clear_reference_nr_txt,
    reversal_dt,
    begin_dt,
    begin_dtm,
    row_process_dtm,
    audit_id,
    logical_delete_ind,
    check_sum,
    current_row_ind,
    end_dt,
    end_dtm,
    source_system_id,
    restricted_row_ind,
    --row_sid  IDENTITY ,
    update_audit_id,
    source_delete_ind,
    source_transaction_key_txt,
    previous_source_transaction_key_txt,
    effective_dt,
    system_dt,
    transaction_cde,
    source_transaction_cde,
    transaction_reversal_cde,
    admin_fund_cde,
    product_id,
    company_cde,
    source_company_cde,
    pt1_kind_cde,
    product_tier_cde,
    fund_type_cde,
    source_fund_type_cde,
    coverage_type_cde,
    coverage_occurance_nr,
    transaction_source_id,
    transaction_memo_cde,
    rollover_cde,
    source_rollover_cde,
    gmib_status_cde,
    administration_cde,
    source_administration_cde,
    disbursement_transaction_nr_txt,
    replacement_transaction_nr_txt,
    transaction_desc,
    source_transaction_desc,
    transaction_reporting_desc,
    transaction_reporting_detail_desc
)

SELECT DISTINCT
       UUID_GEN(
                PREHASH_VALUE(
               Clean_String(SRC.agreement_source_cde),
               Clean_String('Ipa'),
               Clean_String(SRC.agreement_nr_pfx),
               SRC.agreement_nr,
               Clean_String(SRC.agreement_nr_sfx),
               Clean_String(SRC.source_transaction_key_txt),
               SRC.transaction_dt),
				SRC.transaction_dt,
                Clean_String(SRC.financial_transaction_source),
                Clean_String(SRC.financial_transaction_type),
                SRC.reversal_dt,
                SRC.effective_dt,
                SRC.system_dt,
                Clean_String(SRC.transaction_cde),
                Clean_String(SRC.source_transaction_cde),
                Clean_String(SRC.transaction_reversal_cde),
                Clean_String(SRC.admin_fund_cde),
                Clean_String(SRC.product_id),
                Clean_String(SRC.company_cde),
                Clean_String(SRC.pt1_kind_cde),
				Clean_String(SRC.der_product_tier_cde),
                Clean_String(SRC.fund_type_cde),
                Clean_String(SRC.coverage_type_cde),
                SRC.coverage_occurance_nr
         )::UUID                                                       as dim_financial_transaction_natural_key_hash_uuid,
       PREHASH_VALUE(
               Clean_String(SRC.agreement_source_cde),
               Clean_String('Ipa'),
               Clean_String(SRC.agreement_nr_pfx),
               SRC.agreement_nr,
               Clean_String(SRC.agreement_nr_sfx),
               Clean_String(SRC.source_transaction_key_txt),
               SRC.transaction_dt)                      AS financial_transaction_unique_id,
       --NULL                                                              AS financial_transaction_unique_id,
       UUID_GEN(
                Clean_String(SRC.financial_transaction_source)
               )::UUID                                                   AS ref_financial_transaction_source_natural_key_hash_uuid,
       UUID_GEN(
                Clean_String(SRC.financial_transaction_type)
               )::UUID                                                   AS ref_financial_transaction_type_natural_key_hash_uuid,
        SRC.pay_group_nr_txt,
        SRC.check_form_id,
        SRC.transaction_dt,
        SRC.check_status_cde,
        SRC.account_nr_txt,
        SRC.tax_reporting_cde,
        SRC.original_check_nr,
        SRC.distribution_cde,
        SRC.source_payee_unique_id,
        SRC.clear_dt,
        SRC.clear_reference_nr_txt,
        SRC.reversal_dt,
        SRC.begin_dt,
        SRC.begin_dtm,
        SRC.row_process_dtm,
        SRC.audit_id,
        SRC.logical_delete_ind,
        SRC.check_sum,
        SRC.current_row_ind,
        SRC.end_dt,
        SRC.end_dtm,
        SRC.source_system_id,
        SRC.restricted_row_ind,
        SRC.update_audit_id,
        SRC.source_delete_ind,
        SRC.source_transaction_key_txt,
        SRC.previous_source_transaction_key_txt,
        SRC.effective_dt,
        SRC.system_dt,
        SRC.transaction_cde,
        SRC.source_transaction_cde,
        SRC.transaction_reversal_cde,
        SRC.admin_fund_cde,
        SRC.product_id,
        SRC.company_cde,
        SRC.source_company_cde,
        SRC.pt1_kind_cde,
        SRC.product_tier_cde,
        SRC.fund_type_cde,
        SRC.source_fund_type_cde,
        SRC.coverage_type_cde,
        SRC.coverage_occurance_nr,
        SRC.transaction_source_id,
        SRC.transaction_memo_cde,
        SRC.rollover_cde,
        SRC.source_rollover_cde,
        SRC.gmib_status_cde,
        SRC.administration_cde,
        SRC.source_administration_cde,
        SRC.disbursement_transaction_nr_txt,
        SRC.replacement_transaction_nr_txt,
        SRC.transaction_desc,
        SRC.source_transaction_desc,
        SRC.transaction_reporting_desc,
        SRC.transaction_reporting_detail_desc

FROM
(
    SELECT
    dim_fintxn.carr_admin_sys_cd                        as financial_transaction_source,
    'Financial Transaction'                             as financial_transaction_type,
    dim_fintxn.carr_admin_sys_cd                        as agreement_source_cde,
    dim_fintxn.hldg_key_pfx                             as agreement_nr_pfx,
    dim_fintxn.hldg_key                                 as agreement_nr,
    dim_fintxn.hldg_key_sfx                             as agreement_nr_sfx,
    NULL                                                as pay_group_nr_txt,
    NULL                                                as check_form_id,
    dim_fintxn.cycle_dt                                 as transaction_dt,
    NULL                                                as check_status_cde,
    NULL                                                as account_nr_txt,
    NULL                                                as tax_reporting_cde,
    NULL                                                as original_check_nr,
    NULL                                                as distribution_cde,
    NULL                                                as source_payee_unique_id,
    NULL                                                as clear_dt,
    NULL                                                as clear_reference_nr_txt,
    dim_fintxn.rvrsl_dt                                 as reversal_dt,
    dim_fintxn.trans_dt :: date                         as begin_dt,
    dim_fintxn.trans_dt :: timestamp                    as begin_dtm,
    current_timestamp(6)                                as row_process_dtm,
    dim_fintxn.run_id                                   as audit_id,
    false::boolean                                      as logical_delete_ind,
    uuid_gen
        (
        null::varchar
        )::uuid                                         as check_sum,
    'true'::boolean                                     as current_row_ind,
    '9999-12-31':: date                                 as end_dt,
    '9999-12-31':: timestamp                            as end_dtm,
    '266'                                               as source_system_id,
    'false'::boolean                                    as restricted_row_ind,
    --row_sid  IDENTITY ,
    dim_fintxn.updt_run_id                              as update_audit_id,
    'false'::boolean                                    as source_delete_ind,
    dim_fintxn.src_txn_nr                               as source_transaction_key_txt,
    dim_fintxn.prev_src_txn_nr                          as previous_source_transaction_key_txt,
    dim_fintxn.eff_dt                                   as effective_dt,
    dim_fintxn.sys_dt                                   as system_dt,
    dim_fintxn.txn_cd                                   as transaction_cde,
    dim_fintxn.src_txn_cd                               as source_transaction_cde,
    dim_fintxn.rvrsl_ind                                as transaction_reversal_cde,
    dim_fintxn.admin_fnd_nr                             as admin_fund_cde,
    dim_fintxn.prod_id                                  as product_id,
    dim_fintxn.carrier_cd                               as company_cde,
    dim_fintxn.src_co_cd                                as source_company_cde,
    dim_fintxn.kind_cd                                  as pt1_kind_cde,
    dim_fintxn.prod_tier_cd                             as product_tier_cde,
    CASE
         when trim(dim_fintxn.prod_tier_cd)='' then '0'
         when dim_fintxn.prod_tier_cd is null then '0'
         when regexp_ilike(dim_fintxn.prod_tier_cd, '[A-Z]')
                then dim_fintxn.prod_tier_cd
    ELSE
                    ((dim_fintxn.prod_tier_cd::int)::Varchar)
    END                                                 as der_product_tier_cde,

    dim_fintxn.fnd_typ_cd                               as fund_type_cde,
    dim_fintxn.src_fnd_typ_cd                           as source_fund_type_cde,
    dim_fintxn.cvg_typ_cd                               as coverage_type_cde,
    case
        when dim_fintxn.cvg_occur_nr is null then NULL--::int
        --when dim_fintxn.cvg_occur_nr = ''    then NULL::int
            else
             dim_fintxn.cvg_occur_nr::int
    end                                                 as coverage_occurance_nr,
    dim_fintxn.txn_src_cd                               as transaction_source_id,
    dim_fintxn.txn_memo_cd                              as transaction_memo_cde,
    dim_fintxn.rollover_cd                              as rollover_cde,
    dim_fintxn.src_rollover_cd                          as source_rollover_cde,
    dim_fintxn.gmib_ind                                 as gmib_status_cde,
    dim_fintxn.administration_cd                        as administration_cde,
    dim_fintxn.src_administration_cd                    as source_administration_cde,
    dim_fintxn.distributor_txn_id                       as disbursement_transaction_nr_txt,
    dim_fintxn.repl_txn_nr                              as replacement_transaction_nr_txt,
    dim_fintxn.txn_desc                                 as transaction_desc,
    dim_fintxn.src_txn_desc                             as source_transaction_desc,
    dim_fintxn.txn_reporting_ctgy                       as transaction_reporting_desc,
    dim_fintxn.txn_reporting_dtl_ctgy                   as transaction_reporting_detail_desc

from (
		  SELECT * FROM (
			SELECT FIN_TX.*,
			       ROW_NUMBER() OVER (PARTITION BY AGMT_ID,CARR_ADMIN_SYS_CD,HLDG_KEY_PFX,HLDG_KEY,HLDG_KEY_SFX,SRC_TXN_NR,TXN_CD,SRC_TXN_CD,EFF_DT,RVRSL_DT,RVRSL_IND,CREDIT_DEBIT_IND,TXN_AMT_TYP_CD,FND_ID,TRANS_DT ORDER BY TXN_ID DESC) AS RNO
		    FROM  PROD_STND_VW_TERSUN.AGMT_FIN_TXN_VW_AIF_RPS FIN_TX WHERE FIN_TX.SRC_SYS_ID=72
		            AND TXN_AMT_TYP_CD IN ('TGA','FTA')
			            ) A
		  WHERE RNO=1
	 )dim_fintxn
) Src;
